Calc.lang = 'ru';
lang = {
	search : {
		not_found:'Ничего не найдено',
		no_quality:'Не указано качество предмета',
		no_type:'Не указан ранг предмета'
	},
	manalevels : {
		common : 'Маг.камень %1 ур.',
		level : 'Можно усилить магическими камнями %1-го уровня и ниже.'
	},
	godench : {
		name : 'Божественное зачарование (%1/%2)',
		lvl0 : 'Без зачарования',
		lvl1 : 'Бож. зачарование 1 ур.',
		lvl2 : 'Бож. зачарование 2 ур.'
	},
	magench : {
		name : 'Магическое зачарование (%1/%2)',
		lvl0 : 'Без зачарования',
		lvl1 : 'Маг. зачарование 1 ур.',
		lvl2 : 'Маг. зачарование 2 ур.'
	},
	set : {
		'bonus_1' : '1 предмет',
		'bonus_2' : '2 предмета',
		'bonus_3' : '3 предмета',
		'bonus_4' : '4 предмета',
		'bonus_5' : '5 предметов',
		'bonus_6' : '6 предметов',
		'bonus_full' : 'Полный комплект'
	},
	itemicons : {
		depositchar:'Невозможно положить на склад', // STR_TOOLTIP_CHARACTERWAREHOUSE
		depositaccount:'Невозможно положить на склад аккаунта', // STR_TOOLTIP_ACCOUNTWAREHOUSE
		depositguild:'Невозможно положить на склад легиона', // STR_TOOLTIP_ACCOUNTWAREHOUSE
		cannotsale:'Нельзя продать торговцу', // STR_TOOLTIP_CANNOT_SELL_TO_NPC
		noextract:'Невозможно извлечь волшебные камни', // STR_TOOLTIP_CANNOT_EXTRACTION
		noskin:'Невозможно заимствовать внешний вид', // STR_TOOLTIP_NO_SKIN_EXTRACT
		nomultiskin:'Невозможно повторно заимствовать внешний вид', // STR_TOOLTIP_NO_SKIN_EXTRACT_REPEAT
		noarmfusion:'Совмещение невозможно', // STR_TOOLTIP_CANT_COMPOUND
		apextract:'Можно извлечь очки бездны',
		noenchant:'Невозможно усилить волшебными камнями', // STR_TOOLTIP_CANNOT_MATTER_ENCHANT
		nomodify:'Нельзя модифицировать' // STR_TOOLTIP_NO_ENCHANT
	},
	bonusnames : {
		other : 'Другие',
		magical_skill_boost: 'Сила магии',
		magical_hit_accuracy: 'Маг. точность',
		magical_resist: 'Маг. защита',
		attack: 'Атака',
		physical_defend: 'Физ. защита',
		dodge: 'Уклонение',
		parry: 'Парирование',
		block: 'Блок щитом',
		hit_accuracy: 'Точность',
		hitaccuracy: 'Точность',
		critical: 'Физ. крит',
		attack_delay: 'Скор. атаки',
		damage_reduce: 'Блок урона',
		attackdelay: 'Скор. атаки',
		boostcastingtime: 'Скор. магии',
		boosthate: 'Агрессия',
		concentration: 'Концентрация',
		elementaldefendair: 'Защ. от воздуха',
		elementaldefendearth: 'Защ. от земли',
		elementaldefendfire: 'Защ. от огня',
		elementaldefendwater: 'Защ. от воды',
		flyspeed: 'Скор. полёта',
		healskillboost: 'Сила исцеления',
		magicalattack: 'Маг. атака',
		magicalcritical: 'Маг. крит.',
		magicalcriticaldamagereduce: 'Защита от м.крит.',
		magicalcriticalreducerate: 'Блок м.крит.',
		magicalhitaccuracy: 'Маг. точность',
		magicalresist: 'Маг. защита',
		magicalskillboost: 'Сила магии',
		magical_resist: 'Маг. защита',
		maxfp: 'Время полёта',
		maxhp: 'Макс. HP',
		maxmp: 'Макс. MP',
		phyattack: 'Атака',
		physicalcriticaldamagereduce: 'Защ. от ф.крит.',
		physicalcriticalreducerate: 'Блок ф.крит.',
		physicaldefend: 'Физ. защита',
		pvpattackratio: 'Урон в ПвП',
		pvpattackratio_magical: 'Урон в ПвП (маг.)',
		pvpattackratio_physical: 'Урон в ПвП (физ.)',
		pvpdefendratio: 'Защита в ПвП',
		pvpdefendratio_magical: 'Защита в ПвП (маг.)',
		pvpdefendratio_physical: 'Защита в ПвП (физ.)',
		speed: 'Скорость бега',
		level: 'Уровень',
		manastones: 'Маг. камень ур. %1',
		arparalyze: 'Сопр. параличу',
		arsilence: 'Сопр. немоте',
		paralyze_arp: 'Точн. паралича',
		whitehp: 'Макс. HP',
		silence_arp: 'Точн. немоты',
		magicalskillboostresist : 'Отмена магии',
		magicaldefend : 'Блок магии',
		arstumble:'Сопр. опрокидыванию',
		arstagger:'Сопр. отталкиванию',
		arstun:'Сопр. оглушению',
		arroot:'Сопр. оковам',
		arsnare:'Сопр. замедлению',
		arstunlike : 'Сопротивление оглушению, отталкиванию, опрокидыванию, развороту, воздушным оковам',
		arfear : 'Сопр. страху',
		arsleep : 'Сопр. сну',
		elementaldefendall : 'Защита от стихий',
		activedefend : 'Уклонение, парирование, блок щитом',
		hpregen : 'Восстановление HP',
		mpregen : 'Восстановление MP'
	},
	slotnames : {
		weapon : 'Основная рука',
		armfusion : 'Совмещённое оружие',
		shield : 'Вторая рука',
		wing : 'Крылья',
		headgear : 'Головной убор',
		necklace : 'Ожерелье',
		earring_r : 'Правая серьга',
		earring_l : 'Левая серьга',
		armor : 'Броня',
		shoulder : 'Наплечники',
		legs : 'Набедренники',
		gloves : 'Перчатки',
		ring_r : 'Правое кольцо',
		ring_l : 'Левое кольцо',
		boots : 'Ботинки',
		belt : 'Пояс'
	},
	item_ranks : {
		rank: 'Ранг',
		abyss: 'Предмет бездны',
		draconic: 'Драконический',
		devanion: 'Даэванион'
	},
	equipment_types : {
		equipment_type : 'Тип',
		all : 'Все типы',
		'1h_sword' : 'Одноручный меч',
		'1h_mace' : 'Булава',
		'1h_dagger' : 'Кинжал',
		'2h_orb' : 'Орб',
		'2h_book' : 'Гримуар',
		'2h_sword' : 'Двуручный меч',
		'2h_polearm' : 'Копьё',
		'2h_staff' : 'Посох',
		'shield' : 'Щит',
		bow : 'Лук',
		'1h_gun':'Пистолет',
		'2h_cannon':'Пушка',
		'2h_harp':'Арфа',
		'2h_keyblade':'Ключ',
		robe : 'Роба',
		leather : 'Кожаная броня',
		chain : 'Кольчуга',
		plate : 'Латный доспех',
		clothes : 'Одежда',
		head : 'Головной убор',
		necklace : 'Ожерелье',
		earring : 'Серьга',
		ring : 'Кольцо',
		belt : 'Пояс'
	},
	classes : {
		all : 'Все классы',
		assassin : 'Убийца',
		ranger : 'Стрелок',
		chanter : 'Чародей',
		priest : 'Целитель',
		fighter : 'Гладиатор',
		knight : 'Страж',
		wizard : 'Волшебник',
		elementalist : 'Заклинатель',
		bard : 'Бард',
		gunner : 'Снайпер',
		rider : 'Пилот',
		thunderer : 'Revenant'
	},
	abyssranks : {
		'rank_min': 'Мин. ранг бездны: %1',
		'rank_max': 'Макс. ранг бездны: %1',
		'rank1' : 'Воин 9-го ранга',
		'rank2' : 'Воин 8-го ранга',
		'rank3' : 'Воин 7-го ранга',
		'rank4' : 'Воин 6-го ранга',
		'rank5' : 'Воин 5-го ранга',
		'rank6' : 'Воин 4-го ранга',
		'rank7' : 'Воин 3-го ранга',
		'rank8' : 'Воин 2-го ранга',
		'rank9' : 'Воин 1-го ранга',
		'rank10' : 'Офицер 1-го ранга',
		'rank11' : 'Офицер 2-го ранга',
		'rank12' : 'Офицер 3-го ранга',
		'rank13' : 'Офицер 4-го ранга',
		'rank14' : 'Офицер 5-го ранга',
		'rank15' : 'Генерал',
		'rank16' : 'Великий генерал',
		'rank17' : 'Командующий',
		'rank18' : 'Военачальник'
	},
	interface : {
		equipment:'Экипировка',
		compare:'Сравнение',
		slot:'Слот',
		level:'Ур',
		itemname:'Название предмета',
		quality:'Качество',
		rank:'Ранг',
		rank1:'Обычный',
		rank2:'Редкий',
		rank3:'Легендарный',
		rank4:'Уникальный',
		rank5:'Эпический',
		rank6:'Мифический',
		abyss:'Предмет бездны',
		draconic:'Драконический',
		devanion:'Деванион',
		normal:'Обычный',
		version:'Версия игры',
		ver4:'4.0.2',
		type:'Тип',
		all:'[Все]',
		robe:'Роба',
		leather:'Кожаная броня',
		chain:'Кольчуга',
		plate:'Латы',
		sword:'Одноручный меч',
		mace:'Боевой молот',
		dagger:'Кинжал',
		orb:'Орб',
		book:'Гримуар',
		sword2h:'Двуручный меч',
		polearm:'Копьё',
		staff:'Посох',
		bow:'Лук',
		shield:'Щит',
		attribute:'[Параметр]',
		addtocompare:'Добавить в сравнение',
		comparename:'Введите короткое название для набора предметов (будет отображатсья на экране сравнения)',
		search:'Поиск...',
		notfound:'Ничего не найдено',
		removeitem:"Удалить предмет\nCtrl+Клик - удалить все предметы",
		enchantitem:'Усиление',
		set:'Комплект',
		entersetname:'Введите название комплекта',
		beta:'Патч 4.0 находится в процессе тестирования.<br>Параметры предмета могут быть изменены.',
		changes:'Обновления',
		all_req:'Можно использовать с %1 уровня',
		all_req_max:'Можно использовать до %1 уровня',
		class_req:'%1 %2 ур.',
		class_req_max:'%1 не выше %2 ур.',
		telescopic:'Дистанция ударов ближнего боя увеличена',
		enchantment:'Усиление',
		authorize:'Пробуждение',
		minimizelink:'Сократить ссылку с помощью TinyURL.com',
		hasrandomset:'Этот предмет имеет случайные бонусы.',
		selectrandomset:'Выберите набор бонусов',
		charstat:'Характеристики',
		price:'Стоимость',
		share:'Ссылка',
		copylink:'Скопируйте ссылку чтобы поделиться с друзьями',
		copybblink:'BB-код для вставки на форум',
		loading:'Загрузка...',
		close:'Закрыть',
		nomanastone:'Нет камня',
		tradable:'Возможна передача предмета',
		accountbound:'Можно положить на склад аккаунта',
		isset:'Предмет комплекта экипировки',
		ispvp:'Имеет ПвП бонус',
		'delete':'Удалить',
		showdiff:'[Показать различия]',
		hidediff:'[Скрыть различия]',
		stigmacalc:'Калькулятор стигм',
		craftcalc:'Калькулятор крафта',
		equipcalc:'Экипировка',
		copyright:'Aion® зарегистрированная торговая марка NCSOFT Corporation.<br>Разработка: ASPirine и Guimera. Background image by Jonnyjonsen.'
	},
	iteminfo : {
		hitcount_veryslow:'Очень медленное оружие, кол-во ударов: %1',
		hitcount_slow:'Медленное оружие, кол-во ударов: %1',
		hitcount_normal:'Обычное оружие, кол-во ударов: %1',
		hitcount_fast:'Быстрое оружие, кол-во ударов: %1',
		untradable:'Обмен невозможен'
	},
	tooltips : {
		setbutton : 'Нажмите чтобы переключиться на комплект<br>Ctrl+Клик - Переименовать',
		setadd : 'Добавить комплект<br>Ctrl+Клик - Добавить с копией текущего',
		deleteitem:'Удалить предмет<br>Ctrl+Клик - Удалить все предметы',
		randomizeitem:'Выбрать случайные бонусы',
		modifyitem:'Усиление, зачарование и вставка маг. камней',
		enchant:'Выберите уровень усиления<br>Ctrl+Клик - Усилить все предметы',
		augment:'Выберите уровень маг. зачарования',
		conditioning:'Выберите уровень волш. зачарования',
		manastone:'Гнездо для маг. камня<br>Щёлкните чтобы выбрать камень',
		deletemanastone:'Удалить маг. камень<br>Alt+Клик - Удалить все камни из предмета<br>Ctrl+Клик - Удалить все камни',
		pickmanastone:'Вставить маг. камень<br>Alt+Клик - Вставить во все гнёзда предмета<br>Ctrl+Клик - Вставить во все предметы'
	}
};