Calc.lang = 'de';
lang = {
	search : {
		not_found:'Nothing found',
		no_quality:'No item quality selected',
		no_type:'No item rank selected'
	},
	manalevels : {
		common : 'Manastones lvl %1',
		level : 'Manastone socketing (for manastones of level %1 or lower)'
	},
	godench : {
		name : 'Conditioning Effect (%1/%2)',
		lvl0 : 'No Conditioning',
		lvl1 : 'Cond. Effect 1 lvl',
		lvl2 : 'Cond. Effect 2 lvl'
	},
	magench : {
		name : 'Augment Effect (%1/%2)',
		lvl0 : 'No Augment',
		lvl1 : 'Augment Effect 1 lvl',
		lvl2 : 'Augment Effect 2 lvl'
	},
	set : {
		'bonus_1' : 'Equip Effect 1 piece',
		'bonus_2' : 'Equip Effect 2 pieces',
		'bonus_3' : 'Equip Effect 3 pieces',
		'bonus_4' : 'Equip Effect 4 pieces',
		'bonus_5' : 'Equip Effect 5 pieces',
		'bonus_6' : 'Equip Effect 6 pieces',
		'bonus_full' : 'Set Effect'
	},
	itemicons : {
		depositchar:'Unstorable',
		depositaccount:'Unstorable in Account Warehouse',
		depositguild:'Unstorable in Legion Warehouse',
		cannotsale:'Unsellable',
		noextract:'Not extractable',
		noskin:'Unable to extract appearance',
		nomultiskin:'Can only be used once for appearance remodeling',
		noarmfusion:'Armsfusion not allowed', //
		apextract:'Abyss Points extractable',
		noenchant:'Cannot be enchanted',
		nomodify:'Unenhanceable'
	},
	bonusnames : {
		level:'Level',
		other:'Other',
		attack:'Attack',
		physicaldefend:'Defense',
		dodge:'Evasion',
		parry:'Parry',
		block:'Block',
		hitaccuracy:'Accuracy',
		critical:'Crit Strike',
		attackdelay:'Atk Speed',
		damage_reduce:'Damage Reduction',
		boostcastingtime:'Casting Speed',
		boosthate:'Enmity Boost',
		concentration:'Concentration',
		elementaldefendair:'Wind Resist',
		elementaldefendearth:'Earth Resist',
		elementaldefendfire:'Fire Resist',
		elementaldefendwater:'Water Resist',
		flyspeed:'Flight Speed',
		healskillboost:'Healing Boost',
		magicalattack:'Magical Attack',
		magicalcritical:'Crit Spell',
		magicalcriticaldamagereduce:'Spell Fortitude',
		magicalcriticalreducerate:'Spell Resist',
		magicalhitaccuracy:'Magical Acc',
		magicalresist:'Magic Resist',
		magicalskillboost:'Magic Boost',
		maxfp:'Flight Time',
		maxhp:'Max HP',
		maxmp:'Max MP',
		phyattack:'Attack',
		physicalcriticaldamagereduce:'Strike Fortitude',
		physicalcriticalreducerate:'Strike Resist',
		pvpattackratio:'PVP Attack',
		pvpattackratio_magical: 'PVP Attack (Magical)',
		pvpattackratio_physical: 'PVP Attack (Phisical)',
		pvpdefendratio:'PVP Defense',
		pvpdefendratio_magical: 'PVP Defense (Magical)',
		pvpdefendratio_physical: 'PVP Defense (Phisical)',
		speed:'Speed',
		manastones:'Manastone lvl %1',
		arparalyze:'Paralysis Res.',
		arsilence:'Silence Res.',
		paralyze_arp:'Paralysis R.P.',
		maxhp_disp:'HP',
		silence_arp:'Silence R.P.',
		magicalskillboostresist:'Magic Suppr.',
		magicaldefend:'Magical Defense',
		arstumble:'Stumble Resist',
		arstagger:'Knock Back Resist',
		arstun:'Stun Resist',
		arroot:'Root Resist',
		arsnare:'Snare Resist',
		arstunlike : 'Shock Resist',
		arfear : 'Fear Resist',
		arsleep : 'Sleep Resist',
		elementaldefendall : 'All Elemental Defenses',
		activedefend : 'Dodge, Parry, Block',
		hpregen : 'HP Regeneration',
		mpregen : 'MP Regeneration'
	},
	slotnames : {
		weapon:'Main Hand',
		armfusion:'Combine',
		shield:'Off Hand',
		wing:'Wings',
		headgear:'Head',
		necklace:'Necklace',
		earring_r:'Earrings',
		earring_l:'Earrings',
		armor:'Jacket',
		shoulder:'Pauldrons',
		legs:'Pants',
		gloves:'Gloves',
		ring_r:'Ring',
		ring_l:'Ring',
		boots:'Shoes',
		belt:'Belt'
	},
	item_ranks : {
		rank:'Rank',
		abyss:'Abyss',
		draconic:'Balic',
		devanion:'Daevanion'
	},
	equipment_types : {
		equipment_type:'Type',
		all : 'All types',
		'1h_sword':'Sword',
		'1h_mace':'Mace',
		'1h_dagger':'Dagger',
		'2h_orb':'Orb',
		'2h_book':'Spellbook',
		'2h_sword':'Greatsword',
		'2h_polearm':'Polearm',
		'2h_staff':'Staff',
		'shield' : 'Shield',
		bow:'Bow',
		'1h_gun':'Pistol',
		'2h_cannon':'Aethercannon',
		'2h_harp':'Harp',
		'2h_keyblade':'Cipher-Blade',
		robe:'Cloth',
		leather:'Leather',
		chain:'Chain',
		plate:'Plate',
		clothes:'Clothing',
		head : 'Head',
		necklace : 'Necklace',
		earring : 'Earring',
		ring : 'Ring',
		belt : 'Belt'
	},
	classes : {
		all : 'All classes',
		assassin : 'Assassin',
		ranger : 'Ranger',
		chanter : 'Chanter',
		priest : 'Cleric',
		fighter : 'Gladiator',
		knight : 'Templar',
		wizard : 'Sorcerer',
		elementalist : 'Spiritmaster',
		bard : 'Songweaver',
		gunner : 'Gunslinger',
		rider : 'Aethertech',
		thunderer : 'Revenant'
	},
	abyssranks : {
		'rank_min': 'Min. abyss rank: %1',
		'rank_max': 'Max. abyss rank: %1',
		'rank1' : 'Soldier, Rank 9',
		'rank2' : 'Soldier, Rank 8',
		'rank3' : 'Soldier, Rank 7',
		'rank4' : 'Soldier, Rank 6',
		'rank5' : 'Soldier, Rank 5',
		'rank6' : 'Soldier, Rank 4',
		'rank7' : 'Soldier, Rank 3',
		'rank8' : 'Soldier, Rank 2',
		'rank9' : 'Soldier, Rank 1',
		'rank10' : '1-Star Officer',
		'rank11' : '2-Star Officer',
		'rank12' : '3-Star Officer',
		'rank13' : '4-Star Officer',
		'rank14' : '5-Star Officer',
		'rank15' : 'General',
		'rank16' : 'Great General',
		'rank17' : 'Commander',
		'rank18' : 'Governor'
	},
	interface : {
		equipment:'Equipment',
		compare:'Comparison',
		slot:'Slot',
		level:'L',
		itemname:'Item Name',
		quality:'Grade',
		rank:'Rank',
		rank1:'Common',
		rank2:'Rare',
		rank3:'Superior',
		rank4:'Fabled',
		rank5:'Eternal',
		rank6:'Mythic',
		abyss:'Abyss',
		draconic:'Balic',
		devanion:'Daevanion',
		normal:'Normal',
		version:'Game version',
		ver4:'4.0 (NA server)',
		type:'Type',
		all:'[All types]',
		robe:'Cloth',
		leather:'Leather',
		chain:'Chain',
		plate:'Plate',
		sword:'Sword',
		mace:'Mace',
		dagger:'Dagger',
		orb:'Orb',
		book:'Spellbook',
		sword2h:'Greatsword',
		polearm:'Polearm',
		staff:'Staff',
		bow:'Bow',
		shield:'Shield',
		attribute:'[Attribute]',
		addtocompare:'Add to compare',
		comparename:'Enter equipment set title (used in comparison bookmark)',
		search:'Searching...',
		notfound:'Nothing found',
		removeitem:"Remove item \nCtrl+click - remove all items",
		enchantitem:'Enchant item',
		set:'Set',
		entersetname:'Enter set name',
		beta:'4.0 game update is currently testing.<br>Item properties may be changed.',
		all_req:'Available for level %1 or higher',
		all_req_max:'Available for level %1 or lower',
		class_req:'%1 %2 level',
		class_req_max:'%1 up to %2 level',
		telescopic:'Extends when attacking',
		enchantment:'Enchantment',
		authorize:'Awakening',
		minimizelink:'Minimize link with TinyURL.com',
		hasrandomset:'This item has random bonuses.',
		charstat:'Char stats',
		price:'Price',
		share:'Share',
		copylink:'Copy this link to share equipment with your friends',
		copybblink:'BB-code',
		loading:'Loading...',
		close:'Close',
		nomanastone:'No manastone',
		tradable:'Can be traded',
		accountbound:'Can be stored in account warehouse',
		isset:'Set item',
		ispvp:'Has PvP bonuses',
		'delete':'Delete',
		showdiff:'[Show difference]',
		hidediff:'[Hide difference]',
		stigmacalc:'Stigma calc',
		craftcalc:'Craft calc [Ru]',
		equipcalc:'Equipment calc',
		copyright:'Aion® is a registered trademark of NCSOFT Corporation.<br>Designed by ASPirine and Guimera. Background image by Jonnyjonsen.'
	},
	iteminfo : {
		hitcount_veryslow:'Very Slow %1 Strike Weapon',
		hitcount_slow:'Slow %1 Strike Weapon',
		hitcount_normal:'Normal %1 Strike Weapon',
		hitcount_fast:'Fast %1 Strike Weapon',
		untradable:'Untradable'
	},
	tooltips : {
		setbutton : 'Click to display this set<br>Ctrl+Click - Rename',
		setadd : 'Click to add new set<br>Ctrl+Click - Duplicate current set',
		deleteitem:'Delete item<br>Ctrl+Click - Delete all items',
		randomizeitem:'Choose a random bonuses',
		modifyitem:'Enchantment, augment and manastones',
		enchant:'Choose an enchantment level<br>Ctrl+Click - Enchant all items',
		augment:'Choose augment level',
		conditioning:'Choose conditioning level',
		manastone:'Manastone slot<br>Click to modify',
		deletemanastone:'Delete manastone<br>Alt+Click - Delete all manastones from item<br>Ctrl+Click - Delete all manastones',
		pickmanastone:'Insert manastone<br>Alt+Click - Insert into all item slots<br>Ctrl+Click - Insert into all items'
	}
};