Calc.lang = 'fr';
lang = {
	search : {
		not_found:'Nothing found',
		no_quality:'No item quality selected',
		no_type:'No item rank selected'
	},
	manalevels : {
		common : 'Manastones lvl %1',
		level : 'Manastone socketing (for manastones of level %1 or lower)'
	},
	godench : {
		name : 'Conditioning Effect (%1/%2)',
		lvl0 : 'No Conditioning',
		lvl1 : 'Cond. Effect 1 lvl',
		lvl2 : 'Cond. Effect 2 lvl'
	},
	magench : {
		name : 'Augment Effect (%1/%2)',
		lvl0 : 'No Augment',
		lvl1 : 'Augment Effect 1 lvl',
		lvl2 : 'Augment Effect 2 lvl'
	},
	set : {
		'bonus_1' : 'Equip Effect 1 piece',
		'bonus_2' : 'Equip Effect 2 pieces',
		'bonus_3' : 'Equip Effect 3 pieces',
		'bonus_4' : 'Equip Effect 4 pieces',
		'bonus_5' : 'Equip Effect 5 pieces',
		'bonus_6' : 'Equip Effect 6 pieces',
		'bonus_full' : 'Set Effect'
	},
	itemicons : {
		depositchar:'Unstorable',
		depositaccount:'Unstorable in Account Warehouse',
		depositguild:'Unstorable in Legion Warehouse',
		cannotsale:'Unsellable',
		noextract:'Not extractable',
		noskin:'Unable to extract appearance',
		nomultiskin:'Can only be used once for appearance remodeling',
		noarmfusion:'Armsfusion not allowed', //
		apextract:'Abyss Points extractable',
		noenchant:'Cannot be enchanted',
		nomodify:'Unenhanceable'
	},
	bonusnames : {
		level:'Niveau',
		other:'Autre',
		attack:'Attaque',
		physicaldefend:'Défense',
		dodge:'Esquive',
		parry:'Parade',
		block:'Blocage',
		hitaccuracy:'Précision',
		critical:'Crit. Physique',
		attackdelay:'Vit. d\'attaque',
		damage_reduce:'Réduction des dégâts',
		boostcastingtime:'Vit. d\'Incantation',
		boosthate:'Augmentation de l\'hostilité',
		concentration:'Concentration',
		elementaldefendair:'Résistance à l\'Air',
		elementaldefendearth:'Résistance à la Terre',
		elementaldefendfire:'Résistance au Feu',
		elementaldefendwater:'Résistance à l\'Eau',
		flyspeed:'Vit. de vol',
		healskillboost:'Augmentation des soins',
		magicalattack:'Attaque Magique',
		magicalcritical:'Crit. Magique',
		magicalcriticaldamagereduce:'Spell Fortitude',
		magicalcriticalreducerate:'Spell Resist',
		magicalhitaccuracy:'Précision Magique',
		magicalresist:'Rés. Magique',
		magicalskillboost:'Puissance Magique',
		maxfp:'Temps de vol',
		maxhp:'PV Max',
		maxmp:'PM Max',
		phyattack:'Attaque physique',
		physicalcriticaldamagereduce:'Strike Fortitude',
		physicalcriticalreducerate:'Strike Resist',
		pvpattackratio:'Attaque PVP',
		pvpattackratio_magical: 'Attaque PVP (Magique)',
		pvpattackratio_physical: 'Attaque PVP (Physique)',
		pvpdefendratio:'Défense PVP',
		pvpdefendratio_magical: 'Défense PVP (Magique)',
		pvpdefendratio_physical: 'Défense PVP (Physique)',
		speed:'Vitesse',
		manastones:'Pierre de Mana Niv. %1',
		arparalyze:'Rés. à la Paralysie',
		arsilence:'Rés. au Silence',
		paralyze_arp:'Paralysis R.P.',
		maxhp_disp:'PV',
		silence_arp:'Silence R.P.',
		magicalskillboostresist:'Suppr. Magique',
		magicaldefend:'Défense Magique',
		arstumble:'Stumble Resist',
		arstagger:'Knock Back Resist',
		arstun:'Résistance à l\'Étourdissement',
		arroot:'Résistance à l\'Enracinement',
		arsnare:'Résistance au Ralentissement',
		arstunlike : 'Résistance aux Chocs',
		arfear : 'Fear Resist',
		arsleep : 'Sleep Resist',
		elementaldefendall : 'Toutes les Défenses Élémentaires',
		activedefend : 'Esquive, Parade, Blocage',
		hpregen : 'Régeneration des PV',
		mpregen : 'Régeneration des PM'
	},
	slotnames : {
		weapon:'Main Hand',
		armfusion:'Combine',
		shield:'Off Hand',
		wing:'Wings',
		headgear:'Head',
		necklace:'Necklace',
		earring_r:'Earrings',
		earring_l:'Earrings',
		armor:'Jacket',
		shoulder:'Pauldrons',
		legs:'Pants',
		gloves:'Gloves',
		ring_r:'Ring',
		ring_l:'Ring',
		boots:'Shoes',
		belt:'Belt'
	},
	item_ranks : {
		rank:'Rank',
		abyss:'Abyss',
		draconic:'Balic',
		devanion:'Daevanion'
	},
	equipment_types : {
		equipment_type:'Type',
		all : 'All types',
		'1h_sword':'Sword',
		'1h_mace':'Mace',
		'1h_dagger':'Dagger',
		'2h_orb':'Orb',
		'2h_book':'Spellbook',
		'2h_sword':'Greatsword',
		'2h_polearm':'Polearm',
		'2h_staff':'Staff',
		'shield' : 'Shield',
		bow:'Bow',
		'1h_gun':'Pistol',
		'2h_cannon':'Aethercannon',
		'2h_harp':'Harp',
		'2h_keyblade':'Cipher-Blade',
		robe:'Cloth',
		leather:'Leather',
		chain:'Chain',
		plate:'Plate',
		clothes:'Clothing',
		head : 'Head',
		necklace : 'Necklace',
		earring : 'Earring',
		ring : 'Ring',
		belt : 'Belt'
	},
	classes : {
		all : 'All classes',
		assassin : 'Assassin',
		ranger : 'Rôdeur',
		chanter : 'Aède',
		priest : 'Clerc',
		fighter : 'Gladiateur',
		knight : 'Templier',
		wizard : 'Sorcier',
		elementalist : 'Spiritualiste',
		bard : 'Barde',
		gunner : 'Pistolero',
		rider : 'Éthertech',
		thunderer : 'Revenant'
	},
	abyssranks : {
		'rank_min': 'Min. abyss rank: %1',
		'rank_max': 'Max. abyss rank: %1',
		'rank1' : 'Soldier, Rank 9',
		'rank2' : 'Soldier, Rank 8',
		'rank3' : 'Soldier, Rank 7',
		'rank4' : 'Soldier, Rank 6',
		'rank5' : 'Soldier, Rank 5',
		'rank6' : 'Soldier, Rank 4',
		'rank7' : 'Soldier, Rank 3',
		'rank8' : 'Soldier, Rank 2',
		'rank9' : 'Soldier, Rank 1',
		'rank10' : '1-Star Officer',
		'rank11' : '2-Star Officer',
		'rank12' : '3-Star Officer',
		'rank13' : '4-Star Officer',
		'rank14' : '5-Star Officer',
		'rank15' : 'General',
		'rank16' : 'Great General',
		'rank17' : 'Commander',
		'rank18' : 'Governor'
	},
	interface : {
		equipment:'Equipment',
		compare:'Comparison',
		slot:'Slot',
		level:'L',
		itemname:'Item Name',
		quality:'Grade',
		rank:'Rank',
		rank1:'Common',
		rank2:'Rare',
		rank3:'Superior',
		rank4:'Fabled',
		rank5:'Eternal',
		rank6:'Mythic',
		abyss:'Abyss',
		draconic:'Balic',
		devanion:'Daevanion',
		normal:'Normal',
		version:'Game version',
		ver4:'4.0 (NA server)',
		type:'Type',
		all:'[All types]',
		robe:'Cloth',
		leather:'Leather',
		chain:'Chain',
		plate:'Plate',
		sword:'Sword',
		mace:'Mace',
		dagger:'Dagger',
		orb:'Orb',
		book:'Spellbook',
		sword2h:'Greatsword',
		polearm:'Polearm',
		staff:'Staff',
		bow:'Bow',
		shield:'Shield',
		attribute:'[Attribute]',
		addtocompare:'Add to compare',
		comparename:'Enter equipment set title (used in comparison bookmark)',
		search:'Searching...',
		notfound:'Nothing found',
		removeitem:"Remove item \nCtrl+click - remove all items",
		enchantitem:'Enchant item',
		set:'Set',
		entersetname:'Enter set name',
		beta:'4.0 game update is currently testing.<br>Item properties may be changed.',
		all_req:'Available for level %1 or higher',
		all_req_max:'Available for level %1 or lower',
		class_req:'%1 %2 level',
		class_req_max:'%1 up to %2 level',
		telescopic:'Extends when attacking',
		enchantment:'Enchantment',
		authorize:'Awakening',
		minimizelink:'Minimize link with TinyURL.com',
		hasrandomset:'This item has random bonuses.',
		charstat:'Char stats',
		price:'Price',
		share:'Share',
		copylink:'Copy this link to share equipment with your friends',
		copybblink:'BB-code',
		loading:'Loading...',
		close:'Close',
		nomanastone:'No manastone',
		tradable:'Can be traded',
		accountbound:'Can be stored in account warehouse',
		isset:'Set item',
		ispvp:'Has PvP bonuses',
		'delete':'Delete',
		showdiff:'[Show difference]',
		hidediff:'[Hide difference]',
		stigmacalc:'Stigma calc',
		craftcalc:'Craft calc [Ru]',
		equipcalc:'Equipment calc',
		copyright:'Aion® est une marque enregistrée par NCSOFT Corporation. Copyright © NCSOFT Corporation.<br>Conçu par ASPirine et Guimera. Image de fond par Jonnyjonsen.'
	},
	iteminfo : {
		hitcount_veryslow:'Very Slow %1 Strike Weapon',
		hitcount_slow:'Slow %1 Strike Weapon',
		hitcount_normal:'Normal %1 Strike Weapon',
		hitcount_fast:'Fast %1 Strike Weapon',
		untradable:'Untradable'
	},
	tooltips : {
		setbutton : 'Click to display this set<br>Ctrl+Click - Rename',
		setadd : 'Click to add new set<br>Ctrl+Click - Duplicate current set',
		deleteitem:'Delete item<br>Ctrl+Click - Delete all items',
		randomizeitem:'Choose a random bonuses',
		modifyitem:'Enchantment, augment and manastones',
		enchant:'Choose an enchantment level<br>Ctrl+Click - Enchant all items',
		augment:'Choose augment level',
		conditioning:'Choose conditioning level',
		manastone:'Manastone slot<br>Click to modify',
		deletemanastone:'Delete manastone<br>Alt+Click - Delete all manastones from item<br>Ctrl+Click - Delete all manastones',
		pickmanastone:'Insert manastone<br>Alt+Click - Insert into all item slots<br>Ctrl+Click - Insert into all items'
	}
};