lang = $.extend(lang, {
    base: {
        'every': 'каждые',
        'sec': 'сек.',
        'min': 'мин.',
        'hour': 'ч.',
        'novalue': '[нет значения]',
        'reqlvl': 'Доступно с %1 уровня',
        'lvl': 'Ур.',
        'shards': 'Требуется %1 осколков стигм',
        'nodesc': 'Нет описания умения',
        'cost': 'Стоимость',
        'cooltime': 'Откат',
        'casttime': 'Подготовка',
        'instant': 'Мгновенно',
        'stage': 'Этап %1',
        'dist': 'Расстояние',
        'target': 'Действие',
        'selected': 'На цель',
        'self': 'На себя',
        'pet': 'Питомец',
        'targetpoint': 'Указанное место',
        'targetarea': 'Зона действия  (%1 человек)',
        'area': 'Зона',
        'aroundcaster': 'Площадь вокруг ролика (%1 человек)',
        'ally': 'Член группы',
        'enmity': 'Enmity',
        'pvpdmgratio': 'PvP Damage',
        'pvpremaintimeratio': 'PvP Duration',
        'candispel': 'Dispelable',
        'canmove': 'Can move while casting',
        'canjumpshot': 'Can jumpshot',
        'cancelrate': 'Cancel rate',
        'critprob': 'Crit rate',
        'slow': 'Slow',
        'dispeldebuff': 'Removes %1 HP from %2 %3 effect(s) of level %4 maximum',
        'dispelbuff': 'Removes %1 HP from %2 buff(s) of level %3 maximum',
        'mag': 'magical',
        'phy': 'physical',
        'neg': 'negative',
        'true': 'Да',
        'false': 'Нет',
        'version': 'версия',
        'title': 'Aion Classic Stigma Calculator - %1'
    },
    other: {
        everyhit: 'все виды атак',
        stumble: 'опрокидывания',
        openaerial: 'воздушные оковы',
        nmlatk: 'атака на цель',
        phhit: 'физическая атака',
        magical: 'магических атак',
        attackrange: 'Радиус атаки',
        bow: 'Луки',
        physical: 'Физ. атака',
        pmdefend: 'Физическая защита и защита от всех стихий',
        pmattack: 'Физическая и магическая атака'
    },
    'skillnames': {
        "as_assaultslash": "Кровоточащий порез",
        "as_backblow": "Обратный сокрушительный удар",
        "as_blindingburst": "Туманная завеса",
        "as_blindside": "Засада",
        "as_carvesignetchain": "Нанесение сложного клейма",
        "as_chainsignetburst": "Вспышка сложного клейма",
        "as_defendroar_dark": "Перевоплощение: Убийца",
        "as_defendroar_light": "Перевоплощение: Убийца",
        "as_explosionpoison": "Порох",
        "as_flashslash": "Рассекающая молния",
        "as_hitmanmind": "Клятва точности",
        "as_mirrorattack": "Бросок сюрикена",
        "as_quickmove": "Клятва скорости",
        "as_runnersstance": "Спасение",
        "as_senseboost": "Обострение чувств",
        "as_shadowdodge": "Теневая иллюзия",
        "as_shadowdrop": "Падение в тень",
        "as_signetflare": "Разрушение клейма",
        "as_signetwave": "Нанесение клейма на расстоянии",
        "as_silentburst": "Вспышка клейма молчания",
        "as_stabstance": "Готовность",
        "as_stigma_demonicburst_dark": "[Древняя стигма] Воспламенение клейма тьмы",
        "as_stigma_moonburst_dark": "Воспламенение клейма черного пекла",
        "as_stigma_novaburst_light": "[Древняя стигма] Вспышка клейма света",
        "as_stigma_shadowwalk": "Теневой шаг",
        "as_stigma_sunburst_light": "Вспышка клейма небес",
        "as_stunburst": "Блистательная вспышка",
        "as_stuningintention": "Применение смертельных ядов",
        "as_tigerassault": "Чудовищный шрам",
        "as_venomslash": "Клинок обморока",
        "as_venomstab": "Атака ядом",
        "as_visiouseye": "Око гнева",
        "as_whisperofgale": "Клятва уклонения",
        "as_windslash": "Стремительный рассекающий удар",
        "ba_delayparalyze": "Эхо паралича",
        "ba_focusdefence": "Мотив железа",
        "ba_lullaby": "Танец шута",
        "ba_playingstyleschangea": "Закон исцеления",
        "ba_playingstyleschangeb": "Закон усиления",
        "ba_sanctuary": "Аккорд снежинки",
        "ba_songofbind": "Захватывающий грохот",
        "ba_songofbless": "Мотив освобождения",
        "ba_songofbrave": "Мотив отваги",
        "ba_songofearth": "Пчелиный марш",
        "ba_songoffirm": "Мотив самообладания",
        "ba_songofgale": "Аккорд дисгармонии",
        "ba_songofmanareverse": "Рапсодия забвения",
        "ba_songofmassheal": "Мелодия исцеления",
        "ba_songofpain": "Рапсодия мушки",
        "ba_songofregeneration": "Мотив рождения",
        "ba_songofresurrection": "Небесный реквием",
        "ba_songofserenity": "Мелодия невозмутимости",
        "ba_songogpeace": "Ноктюрн мира",
        "ch_blessprotect": "Благословение стойкости",
        "ch_chakra": "Восстановление жизненной силы",
        "ch_chant_improvedcritical": "Заклятие удачи",
        "ch_chant_improvedresiststun": "Заклятие усиления",
        "ch_chant_invincible": "Заклятие неуязвимости",
        "ch_encouragerun": "Воодушевление исступления",
        "ch_harshthrust": "Смертельный удар",
        "ch_healingtank": "Обряд поглощения",
        "ch_heroicstrike": "Фатальный удар",
        "ch_imbuepower": "Благословение ветра",
        "ch_improvedallattack": "Обряд вдохновения",
        "ch_improvedalldefend": "Обряд защиты",
        "ch_improvedbody": "Обряд неприступности",
        "ch_improvedlifestream": "Обряд жизни",
        "ch_mountaincrash": "Разрушающий удар",
        "ch_mpheal": "Магическое восстановление",
        "ch_nightwish": "Обряд ярости",
        "ch_phoenixstep": "Управление небесами",
        "ch_protectself": "Самозащита",
        "ch_shockwave": "Атакующая волна",
        "ch_slowcrash": "Шоковый удар",
        "ch_soaredrock": "Удар земли",
        "ch_splashswing": "Разящий взмах",
        "ch_stigma_angelicwall_light": "Защитный покров",
        "ch_stigma_angelicwish_light": "[Древняя стигма] Обряд преграды",
        "ch_stigma_demonicwall_dark": "Эфирный покров",
        "ch_stigma_demonicwish_dark": "[Древняя стигма] Обряд границы",
        "ch_stigma_recoverword": "Обряд восстановления",
        "ch_surperiorheal": "Длань восстановления",
        "ch_swordbind": "Бросок оков",
        "ch_thruststrike": "Буйство",
        "ch_triplethrust": "Шквал уколов",
        "cl_imbuemana": "Клятва эфира",
        "el_bind": "Заточение плоти",
        "el_dimisspolymorph": "Атака элементаля",
        "el_drainenergy": "Поглощение жизненной силы",
        "el_earthguardiance": "Страж земли",
        "el_elementalboost": "Исцеление разума",
        "el_elementalcharge": "Усиление элементаля: Исцеление",
        "el_elementtransfer": "Переход энергии",
        "el_enchantarmor": "Усиление элементаля: Усиленные доспехи",
        "el_enchantmentburst": "Магическое возгорание",
        "el_enervationcurse": "Проклятие тьмы",
        "el_enfeeblement": "Замедляющие кандалы",
        "el_escape": "Герб маскировки",
        "el_ethercharge": "Усиление элементаля: Восстановление",
        "el_fireaid": "Благословение огня",
        "el_hellcurse": "Загробное проклятие",
        "el_hellpain": "Невыносимые муки",
        "el_manareverse": "Сжечь чары",
        "el_order_elementalfield": "Команда: Стена защиты",
        "el_order_omen": "Команда: Гипноз",
        "el_order_protect": "Команда: Защита",
        "el_order_sacrifice": "Команда: Замена",
        "el_silence": "Блокирование магии",
        "el_slave_stormservent_dark": "Призыв: Энергия урагана",
        "el_slave_stormservent_light": "Призыв: Энергия урагана",
        "el_sleepingspirit": "Узы сна",
        "el_soulsteal": "Кража души",
        "el_stigma_order_destructimpact": "Команда: Сокрушающая атака",
        "el_stigma_order_etheremission_light": "[Древняя стигма] Команда: Жертва",
        "el_stigma_order_ethereruption_light": "Команда: Сжечь дотла",
        "el_stigma_order_etherimpact_dark": "[Древняя стигма] Команда: Самоуничтожение",
        "el_stigma_order_shadoweruption_dark": "Команда: Вспышка",
        "el_stigma_stormblade": "Ураган гнева",
        "el_sympatheticswitch": "Жертва элементаля",
        "el_terrorspirit": "Вопль ужаса",
        "fi_anklegrab": "Захват ног",
        "fi_anklesnatcher": "Связывание ног",
        "fi_berserkstance": "Стойка берсерка",
        "fi_blademode": "Подготовка к бою",
        "fi_burserklance": "Затаптывание",
        "fi_charginghit": "Разрушающий удар",
        "fi_chargingshock": "Уничтожающий удар",
        "fi_cripplingcut": "Нисходящий удар",
        "fi_drainsword": "Меч вампира",
        "fi_enfeeblehit": "Истощающий удар",
        "fi_heavyimpact": "Волна землетрясения",
        "fi_howling": "Угрожающий рев",
        "fi_jumpattack": "Удар с воздуха",
        "fi_kneecrash": "Порез ног",
        "fi_lockdownimpact": "Изоляция",
        "fi_magicalbarrier": "Защита маг.энергией",
        "fi_potentialhealth": "Оздоровление",
        "fi_ragespirit": "Бесстрашие",
        "fi_revengeslash": "Удар мести",
        "fi_seismicdrain": "Вампирическая волна",
        "fi_sharpnesshit": "Колющий удар",
        "fi_spinningparry": "Концентрация на развороте",
        "fi_stigma_draincut": "Выпить крови",
        "fi_stigma_forceblast_light": "[Древняя стигма] Ударная мощь меча",
        "fi_stigma_forceburst_light": "Бойня",
        "fi_stigma_shockburst_dark": "Резня",
        "fi_stigma_shockimpulse_dark": "[Древняя стигма] Волна боевого безумия",
        "fi_survivorstance": "Второе дыхание",
        "fi_technicalcounter": "Мастер контратаки",
        "fi_vorpalhit": "Рубящий удар",
        "fi_whirldrain": "Иссушающая волна",
        "fi_whirltornado": "Восстанавливающая волна",
        "gu_antigravitycannon": "Сковывающее ядро",
        "gu_armorbreak": "Ядро разлома",
        "gu_bullseye": "Сосредоточенность",
        "gu_empowerammo": "Усиление магического взрыва",
        "gu_empowermagic": "Мудрость магии",
        "gu_firechainrefresh": "Зарядка магического взрыва",
        "gu_flamecannon": "Огненный залп",
        "gu_icecannon": "Удар заморозки",
        "gu_magicalbreathing": "Магическое дыхание",
        "gu_mentaliccannon": "Рассекающая пушка",
        "gu_mentalsnatcher": "Поглощающий выстрел",
        "gu_onepointrapidfire": "Быстрый выстрел",
        "gu_rapidstance": "Ускорение стрельбы",
        "gu_shockcannon": "Шоковая пушка",
        "gu_silenceshot": "Заряд немоты",
        "gu_soulbreakcannon": "Призрачная пушка",
        "gu_sunningshot": "Оглушающий выстрел",
        "gu_survivalinstinct": "Инстинкт жизни",
        "gu_vassblaster": "Вызов канонады",
        "gu_veinsnipe": "Проникающий выстрел",
        "kn_absolutescare": "Крик ужаса",
        "kn_brainstorm": "Разрушение сознания",
        "kn_breakpower": "Подсечка",
        "kn_conquestmind": "Способность восстановления",
        "kn_destructshield": "Щит сокрушения",
        "kn_destructwish": "Жажда разрушения",
        "kn_divinepower": "Возмущение",
        "kn_divineslash": "Наказание",
        "kn_executionalstrike": "Устраняющий удар",
        "kn_fortitudewave": "Волна оков",
        "kn_grandprotection": "Защита союзников",
        "kn_highprovoke": "Вызов гнева",
        "kn_holywrath": "Охранный щит",
        "kn_intimidation": "Угроза",
        "kn_invinsibleprotect": "Защита богов",
        "kn_invinsibleshield": "Прочный щит",
        "kn_massiveprovoke": "Издевательский хохот",
        "kn_movingstance": "Нижняя защита",
        "kn_powersink": "Разрушительный магический удар",
        "kn_recover": "Реанимация",
        "kn_reflectshield": "Отражающая защита",
        "kn_revivaltouch": "Восстанавливающая длань",
        "kn_sentinel": "Доспехи покровительства",
        "kn_stigma_demonpunishment_dark": "Правосудие тьмы",
        "kn_stigma_drainsword_dark": "[Древняя стигма] Правосудие бога смерти",
        "kn_stigma_godjudgement_light": "[Древняя стигма] Правосудие богов",
        "kn_stigma_godpunishment_light": "Правосудие света",
        "kn_stigma_resistarmor": "Защитный блок",
        "kn_stunningsnacher": "Перехват",
        "kn_thunderblade": "Раскат грома",
        "kn_triplesnacher": "Иллюзорный захват",
        "p_equip_dual": "Парное оружие: практика",
        "pr_bindingheal": "Исцеляющее сочувствие",
        "pr_blindinglight": "Блик",
        "pr_calllightning": "Раскаты грома",
        "pr_coursewound": "Запрет восстановления",
        "pr_eternalservent_dark": "Призыв: Святая энергия",
        "pr_eternalservent_light": "Призыв: Святая энергия",
        "pr_firstaid": "Мерцание восстановления",
        "pr_graceofgod": "Благословение богов",
        "pr_healershand": "Право на жизнь",
        "pr_healinggrace": "Покровительство целителя",
        "pr_healingservent_dark": "Призыв: Энергия исцеления",
        "pr_healingservent_light": "Призыв: Энергия исцеления",
        "pr_massdispel": "Сияние очищения",
        "pr_massemergentheal": "Сияние восстановления",
        "pr_memoryblur": "Рассеивание памяти",
        "pr_offensivemode": "Право на уничтожение",
        "pr_painlinks": "Цепь страданий",
        "pr_powersmite": "Правосудие земли",
        "pr_purgatory": "Натиск земли",
        "pr_regeneraitionshine": "Сияние регенерации",
        "pr_restorelife": "Спасительная длань",
        "pr_reversecondition": "Реверс",
        "pr_revivehand": "Возрождающая длань",
        "pr_sageswisdom": "Молитва скорости",
        "pr_sprint": "Резкое ускорение",
        "pr_stigma_abysalcircle_dark": "[Древняя стигма] Свет Маркутана",
        "pr_stigma_abysalsanctuary_dark": "Сияние Маркутана",
        "pr_stigma_divinecircle_light": "[Древняя стигма] Свет Юстиэля",
        "pr_stigma_divinesanctuary_light": "Сияние Юстиэля",
        "pr_stigma_suggestion": "Устойчивость",
        "pr_suffermemory": "Ослабляющее клеймо",
        "pr_thunderofpunishment": "Молния возмездия",
        "pr_tranquility": "Волна святости",
        "ra_backdashstab": "Отступление",
        "ra_blazingtrap_dark": "Неистовая ловушка",
        "ra_blazingtrap_light": "Неистовая ловушка",
        "ra_breathofnature": "Дыхание матери-природы",
        "ra_callcompanion_dark": "Призыв симурга",
        "ra_callcompanion_light": "Призыв симурга",
        "ra_draineye": "Поглощение магии",
        "ra_enchantbow": "Благословенная стрела",
        "ra_explosionarrow": "Разрывная стрела",
        "ra_fairyflare_dark": "Ловушка ясновидения",
        "ra_fairyflare_light": "Ловушка ясновидения",
        "ra_heavenstrap_dark": "Опутывающая ловушка",
        "ra_heavenstrap_light": "Опутывающая ловушка",
        "ra_huntermind": "Уловка охотника",
        "ra_instantsprint": "Молниеносный шаг",
        "ra_lightningshot": "Молниеносная стрела",
        "ra_marksmanmode": "Изготовка к стрельбе",
        "ra_massexplosionarrow": "Стрела ярости",
        "ra_movingshot": "Стрела ветра",
        "ra_painarrow": "Стрела страданий",
        "ra_panthermove": "Бешеный ветер",
        "ra_paralyzearrow": "Усыпляющая стрела",
        "ra_rapidshot": "Вопящая стрела",
        "ra_resistmind": "Решительное сопротивление",
        "ra_sealingarrow": "Сковывающий выстрел",
        "ra_shadowarrow": "Стрела яростного ветра",
        "ra_silentarrow": "Стрела молчания",
        "ra_snakebitetrap_dark": "Ловушка злого духа",
        "ra_snakebitetrap_light": "Ловушка злого духа",
        "ra_spoutarrow": "Ливень стрел",
        "ra_stigma_ancientarrow_light": "Стрела Грифонии",
        "ra_stigma_destructarrow_dark": "[Древняя стигма] Стрела кондора",
        "ra_stigma_mysticarrow_dark": "Стрела Консиода",
        "ra_stigma_phoenixarrow_light": "[Древняя стигма] Стрела грифона",
        "ra_stigma_tigereye": "Тигриный глаз",
        "ra_throwingtrap_dark": "Замедляющая ловушка",
        "ra_throwingtrap_light": "Замедляющая ловушка",
        "ra_trackermind": "Усиление стрел",
        "ri_bindingslam": "Электрические оковы",
        "ri_chainfire": "Непрерывный огонь",
        "ri_eathiumblast": "Идиумовая канонада",
        "ri_eathiumcompress": "Магическая компрессия",
        "ri_eathiumcurtain": "Защитное поле",
        "ri_eathiumreactive": "Магическая перезарядка",
        "ri_eathiumwall": "Барьер ида",
        "ri_flamethrow": "Идиумовая кара",
        "ri_forwardstrike": "Сокрушающая волна",
        "ri_itheumreflector": "Амортизирующая мембрана",
        "ri_magneticfield": "Энергетический барьер",
        "ri_overcharge": "Максимальная отдача",
        "ri_poweroverdrive": "Повышение боеспособности",
        "ri_powerslam": "Сокрушительный прорыв",
        "ri_rapidattack": "Град атак",
        "ri_rapidcharge": "Быстрая перезарядка",
        "ri_shielddestroyer": "Разрушение барьеров",
        "ri_speedoverdrive": "Повышение подвижности",
        "ri_tunesensor": "Регулировка",
        "ri_weaponsmash": "Изнуряющая атака",
        "sc_trueshotmind": "Яростный взгляд",
        "wa_gatecrush": "Уничтожение ворот",
        "wa_steadiness": "Броня баланса",
        "wi_arcaneboost": "Мудрость Байзела",
        "wi_arcanepower": "Мудрость Джикела",
        "wi_arcanewisdom": "Мудрость Румиэля",
        "wi_countermagic": "Проклятие слабости",
        "wi_cursedtree": "Проклятие: Дерево",
        "wi_cyclonestrike": "Штормовой удар",
        "wi_deepsleep": "Направленный сон",
        "wi_elementalseal": "Стихийный барьер",
        "wi_flamestrike": "Ярость огня",
        "wi_frostpillar_dark": "Ледяной столп",
        "wi_frostpillar_light": "Ледяной столп",
        "wi_hibernation": "Ледяные оковы",
        "wi_hpmpexchange": "Обмен жизненной силой",
        "wi_icebarrier": "Барьер разделения",
        "wi_icyshield": "Ледяные доспехи",
        "wi_icyveins_dark": "Дар скорости",
        "wi_icyveins_light": "Дар усиления",
        "wi_illusiondance": "Иллюзия",
        "wi_illusionstorm": "Ураган иллюзий",
        "wi_massexplosion": "Огненная вспышка",
        "wi_rockfall": "Призыв скалы",
        "wi_sleepingstorm": "Шторм сна",
        "wi_soulgain": "Мольба концентрации",
        "wi_stigma_atomicenergy_dark": "[Древняя стигма] Лавовое цунами",
        "wi_stigma_atomicenergy_light": "[Древняя стигма] Вулканическая вспышка",
        "wi_stigma_icelance": "Ледяной гарпун",
        "wi_stigma_lavawave_dark": "Лавовый тайфун",
        "wi_stigma_volcanicflame_light": "Мощная вулканическая вспышка",
        "wi_stormshock": "Падение молнии",
        "wi_summontornado_dark": "Торнадо",
        "wi_summontornado_light": "Торнадо",
        "wi_wakeup": "Отмена сна",
        "wi_windcutter": "Лезвие ветра",
        "wi_zeropoint": "Ледяной удар"
    },
    'skilldesc': {
        "as_assaultslash": "Делает рывок к противнику в радиусе [%First_Target_Valid_Distance] м и наносит ему [%e1.DashATK.MinDamage]-[%e1.DashATK.MaxDamage] ед. урона.",
        "as_backblow": "Физическая атака, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона при маскировке. Моментально оглушает цель. ",
        "as_blindingburst": "Ослепляет врагов в радиусе 15 м. [%e2.StatDown.StatName] -[%e2.StatDown.Value]. Время действия: [%e1.Blind.RandomTime]-[%e1.Blind.RemainTime]",
        "as_blindside": "Перемещает за спину цели. Радиус действия: [%First_Target_Valid_Distance] м. Физическая атака, наносит [%e1.MoveBehindATK.MinDamage]-[%e1.MoveBehindATK.MaxDamage] ед. урона. Есть вероятность оглушить цель.",
        "as_carvesignetchain": "Физическая атака, наносит [%e1.CarveSignet.MinDamage]-[%e1.CarveSignet.MaxDamage] ед. урона. Наносит на цель клеймо вплоть до [%e1.CarveSignet.SignetGrade]-го уровня. \n2-е умение в серии\nНанесение клейма - Нанесение сложного клейма",
        "as_chainsignetburst": "Атака магией огня, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.\n2-е умение в серии\nМассовая вспышка клейма - Вспышка сложного клейма",
        "as_defendroar_dark": "Превращает в убийцу на [%e1.ShapeChange.RemainTime] В состоянии перевоплощения [%e2.StatUp.StatName] +[%e2.StatUp.Value], [%e2.StatUp.StatName2] +[%e2.StatUp.Value2], [%e2.StatUp.StatName3] +[%e2.StatUp.Value3]. MP восстанавливаются быстрее.",
        "as_defendroar_light": "Превращает в убийцу на [%e1.ShapeChange.RemainTime] В состоянии перевоплощения [%e2.StatUp.StatName] +[%e2.StatUp.Value], [%e2.StatUp.StatName2] +[%e2.StatUp.Value2], [%e2.StatUp.StatName3] +[%e2.StatUp.Value3]. MP восстанавливаются быстрее.",
        "as_explosionpoison": "Покрывает оружие ядом. Требуется яд скорпиона (5 шт.). При каждой атаке наносит цели дополнительно [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] ед. урона с вероятностью [%e1.Provoker.ConditionProb]%. Время действия: [%e1.Provoker.RemainTime]",
        "as_flashslash": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. [%e2.StatDown.StatName] цели -[%e2.StatDown.Value]. Время действия: [%e2.StatDown.RemainTime]\n2-е умение в серии\nСтремительный удар - Рассекающая молния",
        "as_hitmanmind": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. Время действия: [%e1.StatUp.RemainTime]",
        "as_mirrorattack": "Физическая атака, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона цели в воздушных оковах. Радиус действия: [%First_Target_Valid_Distance] м.",
        "as_quickmove": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. Время действия: [%e1.StatUp.RemainTime]",
        "as_runnersstance": "Отменяет все наложенные на персонажа негативные эффекты передвижения. На 7 сек. увеличивает сопротивляемость к оглушению, отталкиванию, опрокидыванию, развороту и воздушным оковам на 500.",
        "as_senseboost": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e2.StatUp.StatName2] +[%e2.StatUp.Value2]. Время действия: [%e1.StatUp.RemainTime]",
        "as_shadowdodge": "Позволяет мгновенно переместиться вперед на [%e1.RandomMoveLoc.Distance] м. Снимает эффекты обездвиживания и замедления.",
        "as_shadowdrop": "Физическая атака, опрокидывает оглушенную цель и наносит ей [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона.",
        "as_signetflare": "Активирует клеймо, наносящее урон цели в радиусе [%First_Target_Valid_Distance] м. Клеймо активируется вплоть до [%e1.SignetBurst.SignetGrade]-го уровня.\nНаносимый урон зависит от уровня клейма цели.",
        "as_signetwave": "Физическая атака, наносит [%e1.CarveSignet.MinDamage]-[%e1.CarveSignet.MaxDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м. Ставит на цель клеймо вплоть до [%e1.CarveSignet.SignetGrade]-го уровня. ",
        "as_silentburst": "Активирует клеймо вплоть до [%e1.SignetBurst.SignetGrade]-го уровня, которое наносит цели урон и накладывает на нее немоту на 30 с. Радиус действия: [%First_Target_Valid_Distance] м. \nШанс вызова немоты зависит от уровня клейма цели.",
        "as_stabstance": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. [%e2.StatDown.StatName] -[%e2.StatDown.Value]. Время действия: [%e1.StatUp.RemainTime]",
        "as_stigma_demonicburst_dark": "Стигма древнего даэва. Активирует на цели клеймо вплоть до [%e1.SignetBurst.SignetGrade]-го уровня, враги в радиусе [%First_Target_Valid_Distance] м получают урон от взрыва, часть которого идет на восстановление HP персонажа.",
        "as_stigma_moonburst_dark": "Активирует на цели клеймо вплоть до [%e1.SignetBurst.SignetGrade]-го уровня, враги в радиусе [%First_Target_Valid_Distance] м получают урон от взрыва, часть которого идет на восстановление HP персонажа.",
        "as_stigma_novaburst_light": "Стигма древнего даэва. Активирует клеймо вплоть до [%e1.SignetBurst.SignetGrade]-го уровня, которое наносит цели урон взрывом, на время снижает скорость атаки и накладывает немоту. Радиус действия: [%First_Target_Valid_Distance] м.",
        "as_stigma_shadowwalk": "Вы в состоянии улучшенной маскировки. Время действия: [%e1.Hide.RemainTime] Скорость движения в состоянии маскировки: [%e1.Hide.Speed]%.\nПри маскировке можно применять усиливающую магию не более 3 раз.\nНельзя использовать во время боя.",
        "as_stigma_sunburst_light": "Активирует клеймо вплоть до [%e1.SignetBurst.SignetGrade]-го уровня, которое наносит цели урон взрывом, на время снижает скорость атаки и накладывает немоту. Радиус действия: [%First_Target_Valid_Distance] м.",
        "as_stunburst": "Магическая атака огнем, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона и оглушает ее. Радиус действия: [%First_Target_Valid_Distance] м.",
        "as_stunburst_2": "Магическая атака огнем, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона и оглушает ее. Радиус действия: [%First_Target_Valid_Distance] м.",
        "as_stuningintention": "Покрывает оружие ядом. Требуется яд скорпиона (2 шт.). При каждой атаке в течение [%e1.Provoker.RemainTime] есть вероятность [%e1.Provoker.ConditionProb]% оглушить противника.",
        "as_tigerassault": "Физическая атака, наносит [%e1.CarveSignet.MinDamage]-[%e1.CarveSignet.MaxDamage] ед. урона. Наносит на цель клеймо вплоть до [%e1.CarveSignet.SignetGrade]-го уровня. \n4-е умение в серии\nБросок зверя - Чудовищный шрам",
        "as_venomslash": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Если цель отравлена, дополнительно наносит [%e1.SkillATK_Instant.AddDamage] ед. урона и на короткое время оглушает ее.",
        "as_venomstab": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. При нападении со спины наносит дополнительно [%e1.SkillATK_Instant.AddDamage] ед. физического урона и отравляет цель на [%e2.Poison.RemainTime]",
        "as_visiouseye": "После использования умения атакует критическим ударом. Количество атак: [%e1.OneTimeBoostSkillCritical.BoostCount]. Время действия: [%e1.OneTimeBoostSkillCritical.RemainTime] [%e2.StatDown.StatName] -[%e2.StatDown.Value].",
        "as_whisperofgale": "Позволяет отразить магические атаки. Количество отражений: [%e1.AlwaysResist.Count]. Время действия: [%e1.AlwaysResist.RemainTime]",
        "as_windslash": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. [%e2.StatDown.StatName] -[%e2.StatDown.Value]. [%e3.StatDown.StatName] -[%e3.StatDown.Value]. Время действия: [%e2.StatDown.RemainTime]\n2-е умение в серии\nСтремительный удар - Стремительный рассекающий удар",
        "ba_delayparalyze": "Через 8 сек. после активации умения парализует цель в радиусе [%First_Target_Valid_Distance] м на 5 сек.",
        "ba_focusdefence": "[%e1.StatUp.StatName]% +[%e1.StatUp.Value]. Время действия: [%e1.StatUp.RemainTime] Уменьшает урон от атак других персонажей.",
        "ba_lullaby": "Усыпляет цель. [%e3.StatUp.StatName] +[%e3.StatUp.Value]. Время действия: [%e2.Sleep.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "ba_playingstyleschangea": "[%e1.StatBoost.StatName]% +[%e1.StatBoost.fixValue]%.",
        "ba_playingstyleschangeb": "[%e1.StatBoost.StatName]% +[%e1.StatBoost.fixValue]%.",
        "ba_sanctuary": "С вероятностью 100% создает защитный барьер, поглощающий 3000 ед. урона при атаке противника на персонажа в течение 30 сек. Восстанавливает 141 HP/MP каждые 3 сек. в течение 30 сек.",
        "ba_songofbind": "Запрещает цели использовать физические умения в течение 5 сек.",
        "ba_songofbless": "Снимает злые чары, действующие на персонажа и членов его группы в радиусе 25 м, и восстанавливает по [%e2.Heal.CheckTimeHeal] HP с интервалом в [%e2.Heal.CheckTime] Время действия: [%e2.Heal.RemainTime]",
        "ba_songofbrave": "[%e1.StatUp.StatName]% +[%e1.StatUp.Value]%. [%e1.StatUp.StatName2] и [%e1.StatUp.StatName3]% +[%e1.StatUp.Value2]%. Время действия: [%e1.StatUp.RemainTime]",
        "ba_songofearth": "Удар магией земли, наносит цели в радиусе [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] ед. урона. При этом ее [%e2.StatDown.StatName] -[%e2.StatDown.Value]. Время действия: [%e2.StatDown.RemainTime]",
        "ba_songoffirm": "[%e1.StatUp.StatName]% и [%e1.StatUp.StatName3]% +[%e1.StatUp.Value]%. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. Время действия: [%e1.StatUp.RemainTime]",
        "ba_songofgale": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.",
        "ba_songofmanareverse": "Отменяет 2 магических усиления цели.",
        "ba_songofmassheal": "Восстанавливает [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м.",
        "ba_songofmassheal_2": "Восстанавливает [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м.",
        "ba_songofmassheal_3": "Восстанавливает [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м.",
        "ba_songofpain": "Наносит дополнительно [%e1.SpellATK.Damage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м раз в [%e1.SpellATK.CheckTime] Время действия: [%e1.SpellATK.RemainTime] Через [%e2.SpellATK.RemainTime] наносит дополнительно [%e2.SpellATK.Damage] ед. урона.",
        "ba_songofregeneration": "Восстанавливает по [%e1.Heal.CheckTimeHeal] HP цели с интервалом в [%e1.Heal.CheckTime] Время действия: [%e1.Heal.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "ba_songofresurrection": "Возрождает цель в радиусе [%First_Target_Valid_Distance] м.",
        "ba_songofserenity": "Восстанавливает [%e1.MpHeal_Instant.Heal] МP цели в радиусе [%First_Target_Valid_Distance] м.",
        "ba_songofserenity_2": "Восстанавливает [%e1.MpHeal_Instant.Heal] MP персонажа или цели в радиусе [%First_Target_Valid_Distance] м.",
        "ba_songofserenity_3": "Восстанавливает [%e1.MpHeal_Instant.Heal] MP цели в радиусе [%First_Target_Valid_Distance] м от персонажа и 6 союзникам в 10 м от нее.",
        "ba_songogpeace": "Уменьшает враждебность цели.",
        "ch_blessprotect": "[%e1.StatUp.StatName] цели +[%e1.StatUp.Value]%. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e3.StatUp.StatName] +[%e3.StatUp.Value]%. [%e1.StatUp.StatName2]% +[%e1.StatUp.Value2]. Радиус действия: [%First_Target_Valid_Distance] м. Время действия: [%e1.StatUp.RemainTime]",
        "ch_chakra": "Восстанавливает [%e1.Heal_Instant.Heal] HP и [%e2.MPHeal_Instant.Heal] MP.",
        "ch_chant_improvedcritical": "Увеличивает параметры персонажа и членов его группы: [%e1.Aura.OtherSkill.e1.StatUp.StatName]%+[%e1.Aura.OtherSkill.e1.StatUp.Value], [%e1.Aura.OtherSkill.e1.StatUp.StatName2]% +[%e1.Aura.OtherSkill.e1.StatUp.Value2], [%e1.Aura.OtherSkill.e2.StatUp.StatName]% +[%e1.Aura.OtherSkill.e2.StatUp.Value], [%e1.Aura.OtherSkill.e2.StatUp.StatName2]% +[%e1.Aura.OtherSkill.e2.StatUp.Value2]. Радиус действия: [%e1.Aura.Range] м.\nАктивное умение.",
        "ch_chant_improvedresiststun": "[%e1.Aura.OtherSkill.e1.StatUp.StatName] +[%e1.Aura.OtherSkill.e1.StatUp.Value]. Действует на персонажа и членов его группы, находящихся в радиусе [%e1.Aura.Range] м.\nАктивное умение",
        "ch_chant_invincible": "Восстанавливает [%e1.Aura.OtherSkill.e1.MPHeal.CheckTimeHeal] MP персонажа и членов группы в радиусе [%e1.Aura.Range] м. [%e1.Aura.OtherSkill.e2.StatUp.StatName], [%e1.Aura.OtherSkill.e3.StatUp.StatName] и [%e1.Aura.OtherSkill.e4.StatUp.StatName] увеличиваются.\nАктивное умение",
        "ch_encouragerun": "[%e1.StatUp.StatName] союзника в радиусе [%First_Target_Valid_Distance] м увеличивается на [%e1.StatUp.Value]%. Время действия: 7 сек. Расходует HP.",
        "ch_harshthrust": "Сильная физическая атака, требующая подготовки. Наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона.",
        "ch_harshthrust_2": "Сильная физическая атака, требующая подготовки. Наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона.",
        "ch_harshthrust_3": "Сильная физическая атака, требующая подготовки. Наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона.",
        "ch_healingtank": "Восстанавливает [%e1.HealCastorOnAttacked.HealPoint] HP персонажа и членов его группы при каждом нанесении урона. Время действия: [%e1.HealCastorOnAttacked.RemainTime] Радиус действия: [%e1.HealCastorOnAttacked.EffectArea] м.",
        "ch_heroicstrike": "Физическая атака, наносит оглушенному врагу [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона и вводит его в состояние [%e1.SkillATK_Instant.AddEffect].",
        "ch_imbuepower": "Наносит цели дополнительно [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] ед. урона с вероятностью [%e1.Provoker.ConditionProb]%. Необходимое условие: [%e1.Provoker.Condition]. Время действия: [%e1.Provoker.RemainTime]",
        "ch_improvedallattack": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e3.StatUp.StatName] +[%e3.StatUp.Value]%. Действует на членов группы в радиусе 20 м. Время действия: [%e1.StatUp.RemainTime]",
        "ch_improvedalldefend": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. Действует на всех членов группы в радиусе 20 м. Время действия: [%e1.StatUp.RemainTime]",
        "ch_improvedbody": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. Действует на вашего персонажа и 6 членов альянса в 20 м от него. Время действия: [%e1.StatUp.RemainTime]",
        "ch_improvedlifestream": "Восстанавливает по [%e1.Heal.CheckTimeHeal] HP вашего персонажа и членов его группы, находящихся в радиусе 20 м, с интервалом в [%e1.Heal.CheckTime] Время действия: [%e1.Heal.RemainTime]",
        "ch_mountaincrash": "Наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м. Наносит дополнительно [%e2.SpellATK.Damage] ед. урона с интервалом в [%e2.SpellATK.CheckTime] Время действия: [%e2.SpellATK.RemainTime]",
        "ch_mpheal": "Восстанавливает [%e1.MPHeal_Instant.Heal] MP персонажа или цели в радиусе [%First_Target_Valid_Distance] м.",
        "ch_nightwish": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. Время действия: [%e1.StatUp.RemainTime] Время подготовки лечащих умений увеличивается на 20%.",
        "ch_phoenixstep": "Снимает состояния оглушения, отталкивания, опрокидывания, разворота и воздушных оков. [%e2.StatUp.StatName] +[%e2.StatUp.Value] на [%e2.StatUp.RemainTime]\n1-е умение в серии",
        "ch_protectself": "Защитный барьер, с вероятностью [%e1.Shield.ConditionProb]% поглощает урон. Необходимое условие: [%e1.Shield.Condition] на персонажа. Пока барьер действует, сопротивление опрокидыванию увеличивается. Время действия: [%e1.Shield.RemainTime] (Поглощает при каждом ударе [%e1.Shield.CoverValue]% урона.)",
        "ch_shockwave": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона и приводит ее в состояние [%e1.SkillATK_Instant.AddEffect].\nТребуется стигма",
        "ch_slowcrash": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Уменьшает скорость атаки. Также понижает скорость магии на 50%. Время действия: [%e2.Slow.RemainTime]",
        "ch_soaredrock": "Наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона оглушенному или сбитому с ног противнику в радиусе [%First_Target_Valid_Distance] м и блокирует его физические умения на [%e2.bind.RemainTime]",
        "ch_splashswing": "После успешного парирования наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона.",
        "ch_stigma_angelicwall_light": "Создает защитный барьер, восстанавливающий по [%e2.Heal.CheckTimeHeal] HP с интервалом в [%e2.Heal.CheckTime] С вероятностью [%e1.Shield.ConditionProb]% предотвращает [%e1.Shield.CoverValue]% урона, наносимого персонажу и максимум 6 союзникам в радиусе 20 м от него. Условие: [%e1.Shield.Condition] на персонажа. Защитный барьер сохраняется до получения [%e1.Shield.ShieldValue] ед. урона. Время действия: [%e1.Shield.RemainTime]",
        "ch_stigma_angelicwish_light": "Стигма древнего даэва. Создает защитный барьер, восстанавливающий по [%e2.Heal.CheckTimeHeal] HP с интервалом в [%e2.Heal.CheckTime] С вероятностью [%e1.Shield.ConditionProb]% предотвращает [%e1.Shield.CoverValue]% урона, наносимого персонажу и его союзникам в радиусе 20 м от него. Условие: [%e1.Shield.Condition] на персонажа. Защитный барьер сохраняется до получения [%e1.Shield.ShieldValue] ед. урона. Время действия: [%e1.Shield.RemainTime]",
        "ch_stigma_demonicwall_dark": "Создает защитный барьер, который каждый раз, когда на персонажа проводится [%e1.Shield.Condition], с вероятностью [%e1.Shield.ConditionProb]% поглощает урон, получаемый персонажем и его союзниками в радиусе 20 м от него. Защитный барьер сохраняется каждый раз при получении [%e1.Shield.CoverValue]% урона, максимум до [%e1.Shield.ShieldValue]. Время действия: [%e1.Shield.RemainTime]",
        "ch_stigma_demonicwish_dark": "Стигма древнего даэва. Создает защитный барьер, который каждый раз при получении [%e1.Shield.Condition] с вероятностью [%e1.Shield.ConditionProb]% поглощает урон, получаемый персонажем и союзниками в радиусе 20 м от него. Защитный барьер сохраняется каждый раз при получении [%e1.Shield.CoverValue]% урона, максимум до [%e1.Shield.ShieldValue]. Время действия: [%e1.Shield.RemainTime]",
        "ch_stigma_recoverword": "Восстанавливает [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м, а также дополнительно восстанавливает [%e2.Heal.CheckTimeHeal] HP с интервалом в [%e2.Heal.CheckTime] Время действия: [%e2.Heal.RemainTime]",
        "ch_surperiorheal": "Восстанавливает [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м.",
        "ch_swordbind": "Запрещает цели в радиусе [%First_Target_Valid_Distance] м использовать физические умения и снижает ее скорость движения. Время действия: [%e1.Bind.RemainTime]",
        "ch_thruststrike": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона и оглушает ее.\n2-е умение в серии\nШквал уколов (х3) - Буйство",
        "ch_triplethrust": "Наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона.\n3 повтора\n1-е умение в серии",
        "cl_imbuemana": "При каждой атаке в течение [%e1.Provoker.RemainTime] есть вероятность [%e1.Provoker.ConditionProb]% восстановить MP персонажа.",
        "el_bind": "Запрещает цели использовать физические умения. Радиус действия: [%First_Target_Valid_Distance] м. Время действия: [%e1.Bind.RandomTime]-[%e1.Bind.RemainTime]",
        "el_dimisspolymorph": "Атака магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона в радиусе [%First_Target_Valid_Distance] м. Наносит [%e1.SpellATK_Instant.AddDamage] ед. дополнительного урона, если целью является элементаль.",
        "el_drainenergy": "Удар магией огня, наносит [%e1.SpellATKDrain_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м. Переводит [%e1.SpellATKDrain_Instant.HPHeal]% нанесенного урона в HP.",
        "el_earthguardiance": "Снимает с вашего персонажа все негативные эффекты, связанные с передвижением, и повышает защиту от них на 800. Время действия: 10 сек.",
        "el_elementalboost": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. [%e1.StatUp.StatName3] +[%e1.StatUp.Value3]. Действует на призывателя и элементаля. Время действия: [%e1.StatUp.RemainTime]",
        "el_elementalcharge": "В радиусе [%First_Target_Valid_Distance] м восстанавливает [%e1.Heal_Instant.Heal]% HP элементаля и снимает все наложенные на него злые чары.",
        "el_elementtransfer": "Восстанавливает [%e1.MPHeal_Instant.Heal] МР находящемуся в радиусе 25 м союзнику за счет 10% собственных НР.",
        "el_enchantarmor": "Изменяет следующие параметры элементаля: [%e1.StatUp.StatName] +[%e1.StatUp.Value]%, [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]%, [%e1.StatUp.StatName3] +[%e1.StatUp.Value3], [%e2.StatUp.StatName] +[%e2.StatUp.Value]%, [%e2.StatUp.StatName2] +[%e2.StatUp.Value2], [%e2.StatUp.StatName3] +[%e2.StatUp.Value3]. Радиус действия: [%First_Target_Valid_Distance] м. Время действия: [%e1.StatUp.RemainTime]",
        "el_enchantmentburst": "Отменяет усиливающую магию на цели (максимум до [%e1.DispelBuffCounterATK.DispelCount] шт.). При отмене одного эффекта наносит [%e1.DispelBuffCounterATK.Damage] ед. урона. В случае отмены более одного эффекта наносит по [%e1.DispelBuffCounterATK.AddDamage] ед. дополнительного урона.\n1-е умение в серии",
        "el_enervationcurse": "Уменьшает на [%e1.Curse.Value] максимальное количество НР и МР цели. Время действия: [%e1.Curse.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.\nМожно снять при помощи умения &quot;Снятие злых чар&quot;.",
        "el_enfeeblement": "Уменьшает скорость атаки и увеличивает время подготовки магических умений цели в радиусе [%First_Target_Valid_Distance] м. При этом [%e2.StatDown.StatName] -[%e2.StatDown.Value]. Время действия: [%e1.Slow.RemainTime] Можно удалить при помощи умений &quot;Снятие усиливающих чар&quot; или &quot;Снятие злых чар&quot;.",
        "el_escape": "На всех членов группы в радиусе 20 м накладывается базовая маскировка. Время действия: [%e1.Hide.RemainTime] Уменьшает скорость передвижения.\nНевозможно использовать во время боя.",
        "el_ethercharge": "Восстанавливает 100% HP элементаля.",
        "el_fireaid": "Ваш персонаж и члены группы в радиусе 20 м наносят врагам дополнительно [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] ед. урона с вероятностью [%e1.Provoker.ConditionProb]%. Необходимое условие: [%e1.Provoker.Condition]. Время действия: [%e1.Provoker.RemainTime]",
        "el_hellcurse": "Изменяет следующие параметры цели: [%e1.StatDown.StatName] -[%e1.StatDown.Value], [%e2.StatDown.StatName] -[%e2.StatDown.Value], [%e2.StatDown.StatName2] -[%e2.StatDown.Value2]. Время действия: [%e1.StatDown.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "el_hellpain": "Удар магией земли, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м. Наносит дополнительно [%e2.SpellATK.Damage] ед. урона с интервалом в [%e2.SpellATK.CheckTime] Время действия: [%e2.SpellATK.RemainTime] Можно удалить при помощи умений &quot;Снятие усиливающих чар&quot; или &quot;Снятие злых чар&quot;.",
        "el_manareverse": "Отменяет усиливающую магию на цели (максимум до [%e1.DispelBuffCounterATK.DispelCount] шт.) При отмене одного эффекта наносит [%e1.DispelBuffCounterATK.Damage] ед. урона. В случае отмены более одного эффекта наносит по [%e1.DispelBuffCounterATK.AddDamage] ед. дополнительного урона. Цель дополнительно получает [%e2.SkillLauncher.OtherSkill.e1.SpellATK.Damage] ед. урона с интервалом в [%e2.SkillLauncher.OtherSkill.e1.SpellATK.CheckTime] Время действия: [%e2.SkillLauncher.OtherSkill.e1.SpellATK.RemainTime] Можно удалить при помощи умений &quot;Снятие усиливающих чар&quot; или &quot;Снятие злых чар&quot;.\n1-е умение в серии",
        "el_order_elementalfield": "Приказывает элементалю использовать усиливающую магию. Действует на всех союзников в радиусе 15 м.\n\nЭлементаль воды: Увеличивает маг. защиту и точность.\nЭлементаль ветра: Увеличивает точность и уклонение.\nЭлементаль земли: Восстанавливает HP, снимает физ./маг. негативные эффекты.\nЭлементаль огня: Усиливает физ. атаку, отражает атаку.\nЭлементаль магмы: Восстанавливает HP, увеличивает физ. атаку.\nЭлементаль тайфуна: Увеличивает точность магии, маг. защиту, точность, шанс уклонения.",
        "el_order_omen": "Приказывает элементалю использовать злые чары, которыми обладает сам персонаж. Элементаль, приводя цель в состояние одержимости, усыпляет ее, уменьшает скорость ее атаки и усиливает ее защиту от всех стихий, а затем исчезает.",
        "el_order_protect": "Приказывает элементалю защищать цель.\nЭлементаль создает вокруг цели магический барьер и получает вместо нее весь наносимый ей урон с шансом 100%. Радиус действия: 20 м. Барьер действует 20 сек.",
        "el_order_sacrifice": "Приказывает элементалю использовать защитные умения. Элементаль получает весь урон вместо его хозяина.",
        "el_silence": "Накладывает на цель в радиусе [%First_Target_Valid_Distance] м эффект немоты. Время действия: [%e1.Silence.RandomTime]-[%e1.Silence.RemainTime]",
        "el_slave_stormservent_dark": "Атака магией воздуха, призывает элементалей ветра ([%e1.SummonHoming.UnitNumber] шт.), которые наносят урон врагу в радиусе [%First_Target_Valid_Distance] м.",
        "el_slave_stormservent_light": "Атака магией воздуха, призывает элементалей ветра ([%e1.SummonHoming.UnitNumber] шт.), которые наносят урон врагу в радиусе [%First_Target_Valid_Distance] м.",
        "el_sleepingspirit": "Усыпляет цель. [%e2.StatUp.StatName] увеличивается. Время действия: [%e1.Sleep.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "el_soulsteal": "Удар магией воды, наносит цели в радиусе [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] ед. урона.\n5 повторов",
        "el_stigma_order_destructimpact": "Приказывает элементалю атаковать умениями. Каждый элементаль атакует той стихией, частью которой является.\n\nЭлементаль воды: Атакует магией воды.\nЭлементаль ветра: Атакует магией воздуха, нанося продолжительный урон.\nЭлементаль земли: Атакует магией земли, нанося продолжительный урон, снижает скорость движения.\nЭлементаль огня: Атакует магией огня.\nЭлементаль магмы: Атакует магией огня.\nЭлементаль тайфуна: Атакует магией воздуха.",
        "el_stigma_order_etheremission_light": "Стигма древнего даэва. Приказывает элементалю использовать атакующие умения, расходуя HP. Каждый элементаль может атаковать собственной стихией по площади вокруг себя. Если цель атаки - асмодианин или балаур, то ей наносится дополнительный урон.\n\nЭлементаль воды: Атакует магией воды.\nЭлементаль ветра: Атакует магией воздуха.\nЭлементаль земли: Атакует магией земли.\nЭлементаль огня: Атакует магией огня.\nЭлементаль тайфуна: Атакует магией воды.",
        "el_stigma_order_ethereruption_light": "Приказывает элементалю использовать атакующие умения, расходуя HP. Каждый элементаль может атаковать собственной стихией по площади вокруг себя. Если цель атаки - асмодианин или балаур, то ей наносится дополнительный урон.\n\nЭлементаль воды: Атакует магией воды.\nЭлементаль ветра: Атакует магией воздуха.\nЭлементаль земли: Атакует магией земли.\nЭлементаль огня: Атакует магией огня.\nЭлементаль тайфуна: Атакует магией воды.",
        "el_stigma_order_etherimpact_dark": "Стигма древнего даэва. Приказывает элементалю использовать атакующие умения, расходуя HP. Каждый элементаль может атаковать собственной стихией по площади вокруг себя. Если цель атаки - элиец или балаур, то ей наносится дополнительный урон.\n\nЭлементаль воды: Атакует магией воды.\nЭлементаль ветра: Атакует магией воздуха.\nЭлементаль земли: Атакует магией земли.\nЭлементаль огня: Атакует магией огня.\nЭлементаль магмы: Атакует магией земли.",
        "el_stigma_order_shadoweruption_dark": "Приказывает элементалю использовать атакующие умения, расходуя HP. Каждый элементаль может атаковать собственной стихией по площади вокруг себя. Если цель атаки - элиец или балаур, то ей наносится дополнительный урон.\n\nЭлементаль воды: Атакует магией воды.\nЭлементаль ветра: Атакует магией воздуха.\nЭлементаль земли: Атакует магией земли.\nЭлементаль огня: Атакует магией огня.\nЭлементаль магмы: Атакует магией земли.",
        "el_stigma_stormblade": "Удар магией воздуха, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона и [%e2.SpellATK.Damage] ед. урона с интервалом в [%e2.SpellATK.CheckTime] Радиус действия: [%First_Target_Valid_Distance] м. Время действия: [%e2.SpellATK.RemainTime]",
        "el_sympatheticswitch": "Враждебность цели к персонажу меняется на враждебность к элементалю. Радиус действия: [%First_Target_Valid_Distance] м.",
        "el_terrorspirit": "Превращает врагов в радиусе 15 м в элементалей огня, обращает их в бегство и снижает их скорость движения на [%e1.Fear.RandomTime]-[%e1.Fear.RemainTime]",
        "fi_anklegrab": "Обездвиживает цель, находящуюся в радиусе [%First_Target_Valid_Distance] м. [%e2.StatDown.StatName] цели -[%e2.StatDown.Value]. Время действия: [%e1.Root.RemainTime]",
        "fi_anklesnatcher": "Обездвиживает цель. Радиус действия: [%First_Target_Valid_Distance] м. Время действия: [%e1.Root.RemainTime]",
        "fi_berserkstance": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. При этом [%e2.StatDown.StatName] -[%e2.StatDown.Value], а [%e3.StatDown.StatName] -[%e3.StatDown.Value]%. Время действия: [%e1.StatUp.RemainTime]",
        "fi_blademode": "При нападении на другого персонажа урон увеличивается на 25%, а [%e2.StatBoost.StatName] - на [%e2.StatBoost.FixValue].\nАктивное умение",
        "fi_burserklance": "С вероятностью 100% наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона.\n1-е умение в серии",
        "fi_burserklance_2": "Наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона.\n1-е умение в серии",
        "fi_burserklance_3": "С вероятностью 100% наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона.\n1-е умение в серии",
        "fi_charginghit": "Обязательно попадает в цель и наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона.",
        "fi_charginghit_2": "Наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона.",
        "fi_charginghit_3": "Обязательно попадает в цель и наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона.",
        "fi_chargingshock": "Широкий взмах оружием, в радиусе 7 м наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Поражает до 6 целей. С определенной вероятностью вводит цель в состояние [%e1.SkillATK_Instant.AddEffect].\n1-е умение в серии",
        "fi_chargingshock_2": "Широкий взмах оружием, в радиусе 7 м наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона.\n1-е умение в серии",
        "fi_chargingshock_3": "Широкий взмах оружием, в радиусе 7 м наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Поражает до 6 целей. С определенной вероятностью вводит цель в состояние [%e1.SkillATK_Instant.AddEffect].\n1-е умение в серии",
        "fi_cripplingcut": "Физическая атака, наносит упавшему врагу [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона.",
        "fi_drainsword": "Наносит цели [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] ед. физического урона. С определенной вероятностью переводит [%e1.SkillATKDrain_Instant.HPHeal]% нанесенного урона в HP.\n3-е умение в серии\nРубящий удар - Меч вампира",
        "fi_enfeeblehit": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. [%e2.StatDown.StatName] -[%e2.StatDown.Value]. [%e3.StatDown.StatName] -[%e3.StatDown.Value]. Время действия: [%e2.StatDown.RemainTime]\n1-е умение в серии",
        "fi_heavyimpact": "Физическая атака, наносит противникам в радиусе 10 м [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона и снижает их скорость движения. Время действия: [%e2.Snare.RandomTime]-[%e2.Snare.RemainTime]",
        "fi_howling": "[%e1.StatDown.StatName] врагов в радиусе 7 м понижается на [%e1.StatDown.Value]. Время действия: [%e1.StatDown.RemainTime]",
        "fi_jumpattack": "Делает рывок к противнику в радиусе [%First_Target_Valid_Distance] м и наносит ему [%e1.DashATK.MinDamage]-[%e1.DashATK.MaxDamage] ед. урона.",
        "fi_kneecrash": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона и обездвиживает ее на [%e2.Root.RemainTime]",
        "fi_lockdownimpact": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Запрещает цели использовать физические умения. Время действия: [%e2.Bind.RemainTime]",
        "fi_magicalbarrier": "Отмена магии +[%e1.StatUp.Value]. Маг. защита -[%e2.StatDown.Value]. Время действия: [%e1.StatUp.RemainTime]",
        "fi_potentialhealth": "Восстанавливает [%e1.Heal_Instant.Heal]% HP в течение [%e2.StatUp.RemainTime] [%e2.StatUp.StatName] +[%e2.StatUp.Value]%. [%e3.StatUp.StatName] +[%e3.StatUp.Value]. [%e4.StatUp.StatName] +[%e4.StatUp.Value].",
        "fi_ragespirit": "Создает защитный барьер, блокирующий урон с вероятностью [%e1.Shield.ConditionProb]%. Необходимое условие: [%e1.Shield.Condition]. Время действия: [%e1.Shield.RemainTime] (Защитный барьер сохраняется до нанесения персонажу [%e1.Shield.CoverValue] ед. урона.)",
        "fi_revengeslash": "После успешного парирования наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона.",
        "fi_seismicdrain": "Наносит [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] ед. урона в радиусе 7 м. Переводит [%e1.SkillATKDrain_Instant.HPHeal]% нанесенного урона в HP.\n1-е умение в серии",
        "fi_sharpnesshit": "Наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона.\n1-е умение в серии",
        "fi_spinningparry": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Время действия: [%e1.StatUp.RemainTime]",
        "fi_stigma_draincut": "Физическая атака, наносит поверженной цели [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] ед. урона. Переводит [%e1.SkillATKDrain_Instant.HPHeal]% нанесенного урона в HP.",
        "fi_stigma_forceblast_light": "Стигма древнего даэва. Физическая атака, наносит цели в радиусе [%First_Target_Valid_Distance] м и 5 противникам в радиусе 10 м от цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. [%e2.StatDown.StatName] целей -[%e2.StatDown.Value] на [%e2.StatDown.RemainTime]",
        "fi_stigma_forceburst_light": "Физическая атака, наносит цели в радиусе [%First_Target_Valid_Distance] м и 18 противникам в радиусе 10 м от цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. [%e2.StatDown.StatName] целей -[%e2.StatDown.Value] на [%e2.StatDown.RemainTime]",
        "fi_stigma_shockburst_dark": "Физическая атака, наносит 18 врагам в радиусе 10 м [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. [%e2.StatDown.StatName] целей -[%e2.StatDown.Value] на [%e2.StatDown.RemainTime]",
        "fi_stigma_shockimpulse_dark": "Стигма древнего даэва. Физическая атака, наносит 12 врагам в радиусе 10 м [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. [%e2.StatDown.StatName] целей -[%e2.StatDown.Value] на [%e2.StatDown.RemainTime]",
        "fi_survivorstance": "Восстанавливает [%e1.Heal_Instant.Heal]% HP. [%e2.StatUp.StatName] +[%e2.StatUp.Value]%. [%e3.StatUp.StatName] +[%e3.StatUp.Value]. Время действия: [%e2.StatUp.RemainTime]",
        "fi_technicalcounter": "Физическая атака, после успешного парирования наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Вводит цель в состояние [%e1.SkillATK_Instant.AddEffect].",
        "fi_vorpalhit": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона.\n2-е умение в серии\nКолющий удар - Рубящий удар",
        "fi_whirldrain": "Наносит [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] ед. урона в радиусе 7 м. Переводит [%e1.SkillATKDrain_Instant.HPHeal]% нанесенного урона в HP.\n3 повтора\n1-е умение в серии",
        "fi_whirltornado": "Наносит [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] ед. урона в радиусе 7 м. Переводит [%e1.SkillATKDrain_Instant.HPHeal]% нанесенного урона в HP.\n2-е умение в серии\nИссушающая волна (х3) - Восстанавливающая волна",
        "gu_antigravitycannon": "Магическая атака земли, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона и вводит ее в состояние [%e1.SpellATK_Instant.AddEffect]. Радиус действия: [%First_Target_Valid_Distance] м.",
        "gu_armorbreak": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м. [%e2.StatDown.StatName] -[%e2.StatDown.Value]%. Эффективность магии исцеления -50%. Время действия: [%e2.StatDown.RemainTime]",
        "gu_bullseye": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. Время действия: [%e1.StatUp.RemainTime]",
        "gu_empowerammo": "Наносит цели дополнительно [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] ед. урона с вероятностью [%e1.Provoker.ConditionProb]%. Уменьшает силу атаки персонажа. Необходимое условие: [%e1.Provoker.Condition]. Время действия: [%e1.Provoker.RemainTime]",
        "gu_empowermagic": "[%e1.OneTimeBoostSkillAttack.AttackType] +[%e1.OneTimeBoostSkillAttack.BonusRate]%. Количество атак: [%e1.OneTimeBoostSkillAttack.AttackCount]. Время действия: [%e1.OneTimeBoostSkillAttack.RemainTime] Уменьшает силу атаки персонажа.",
        "gu_firechainrefresh": "Сбрасывает время перезарядки умений &quot;Пальба из пистолета&quot;, &quot;В яблочко&quot;, &quot;Рассекающий огонь&quot;.",
        "gu_flamecannon": "Удар магией огня, наносит цели в радиусе [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] ед. урона. При этом ее [%e2.StatDown.StatName] уменьшается на [%e2.StatDown.Value]%. Время действия: [%e2.StatDown.RemainTime]",
        "gu_flamecannon_2": "Удар магией огня, наносит цели в радиусе [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] ед. урона. При этом ее [%e2.StatDown.StatName] уменьшается на [%e2.StatDown.Value]%. Время действия: [%e2.StatDown.RemainTime]",
        "gu_flamecannon_3": "Удар магией огня, наносит цели в радиусе [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] ед. урона. При этом ее [%e2.StatDown.StatName] уменьшается на [%e2.StatDown.Value]%. Время действия: [%e2.StatDown.RemainTime]",
        "gu_icecannon": "Удар магией воды, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона в радиусе [%First_Target_Valid_Distance] м. Обездвиживает противника на [%e2.Root.RemainTime]",
        "gu_magicalbreathing": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. Время действия: [%e1.StatUp.RemainTime]",
        "gu_mentaliccannon": "Удар магией ветра, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м. MP -[%e2.MPAttack_Instant.Damage]%.",
        "gu_mentaliccannon_2": "Удар магией ветра, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м. MP -[%e2.MPAttack_Instant.Damage]%.",
        "gu_mentaliccannon_3": "Удар магией ветра, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м. MP -[%e2.MPAttack_Instant.Damage]%.",
        "gu_mentalsnatcher": "Атака магией воды, наносит [%e1.SpellATKDrain_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м. Переводит [%e1.SpellATKDrain_Instant.HPHeal]% нанесенного урона в HP и [%e1.SpellATKDrain_Instant.MPHeal]% - в MP.",
        "gu_onepointrapidfire": "Удар магией земли, наносит цели в радиусе [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] ед. урона.\n5 повторов",
        "gu_rapidstance": "[%e1.StatBoost.StatName] +[%e1.StatBoost.RateValue]%.\nАктивное умение",
        "gu_shockcannon": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м. Оглушает противника на [%e2.Stun.RemainTime]",
        "gu_shockcannon_2": "Магическая атака ветром, наносит цели и 2 противникам в радиусе 2 м от нее [%e1.SpellATK_Instant.FixDamage] ед. урона и отталкивает их. Радиус действия: [%First_Target_Valid_Distance] м.",
        "gu_shockcannon_3": "Магическая атака ветром, наносит цели и 3 противникам в радиусе 4 м от нее [%e1.SpellATK_Instant.FixDamage] ед. урона и отталкивает их на 4 сек. Радиус действия: [%First_Target_Valid_Distance] м.",
        "gu_silenceshot": "Магическая атака ветром, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона и вызывает немоту. Время действия: [%e2.Silence.RandomTime]-[%e2.Silence.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "gu_soulbreakcannon": "Удар магией воды, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона в радиусе [%First_Target_Valid_Distance] м.",
        "gu_soulbreakcannon_2": "Удар магией воды, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона в радиусе [%First_Target_Valid_Distance] м.",
        "gu_soulbreakcannon_3": "Удар магией воды, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона в радиусе [%First_Target_Valid_Distance] м.",
        "gu_sunningshot": "Удар магией огня, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона и оглушает ее на [%e2.Stun.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "gu_survivalinstinct": "Отменяет 2 негативных физических эффекта. [%e2.StatUp.StatName]% +[%e2.StatUp.Value]%. Время действия: [%e2.StatUp.RemainTime]",
        "gu_vassblaster": "Удар магией огня, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м от вашего персонажа и 3 противникам в радиусе 10 м от выбранной цели.",
        "gu_vassblaster_2": "Удар магией огня, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м от вашего персонажа и 4 противникам в радиусе 10 м от выбранной цели.",
        "gu_vassblaster_3": "Удар магией огня, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м от вашего персонажа и 5 противникам в радиусе 10 м от выбранной цели.",
        "gu_veinsnipe": "Удар магией земли, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м. Также вызывает кровотечение на [%e2.Bleed.RemainTime]",
        "kn_absolutescare": "Провоцирует максимум 4 противников в радиусе 10 м и увеличивает их враждебность, повергая их в страх и снижая скорость движения. Время действия: [%e2.Fear.RemainTime]",
        "kn_brainstorm": "Удар магией земли, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона и оглушает ее на [%e2.Stun.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "kn_breakpower": "Физическая атака, наносит упавшей цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. [%e2.StatDown.StatName] цели -[%e2.StatDown.Value]. Время действия: [%e2.StatDown.RemainTime] [%e0.KN_BreakPower_G1_Buff.e1.StatUp.StatName] +[%e0.KN_BreakPower_G1_Buff.e1.StatUp.Value].",
        "kn_conquestmind": "Восстанавливает [%e1.Heal.CheckTimeHeal] HP вашего персонажа с интервалом в [%e1.Heal.CheckTime] Время действия: [%e1.Heal.RemainTime]",
        "kn_destructshield": "Гарантированно наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона и опрокидывает ее.\nНеобходим щит.",
        "kn_destructwish": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e3.StatUp.StatName] +[%e3.StatUp.Value]. Время действия: [%e1.StatUp.RemainTime]",
        "kn_divinepower": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. Время действия: [%e1.StatUp.RemainTime]",
        "kn_divineslash": "Физическая атака, наносит противнику [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона.",
        "kn_executionalstrike": "Наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона.",
        "kn_fortitudewave": "Наносит максимум 6 противникам в радиусе 7 м вокруг себя [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. физического урона и обездвиживает их на [%e2.Root.RemainTime]",
        "kn_grandprotection": "Вы получаете [%e1.Protect.Value]% урона вместо члена вашей группы. Необходимое условие: [%e1.Protect.Condition] на союзника. Радиус действия: [%e1.Protect.Range] м. Время действия: [%e1.Protect.RemainTime]",
        "kn_highprovoke": "Провоцирует цель на расстоянии [%First_Target_Valid_Distance] м и увеличивает враждебность цели к персонажу. Эффект повышенной враждебности действует 5 сек.",
        "kn_holywrath": "Отражает [%e1.Reflector.FixedDamage] ед. урона обратно в противника. Необходимое условие: [%e1.Reflector.Condition] на вашего персонажа. Радиус действия: [%e1.Reflector.MaxRange] м. Время действия: [%e1.Reflector.RemainTime]",
        "kn_intimidation": "Провоцирует цель на расстоянии [%First_Target_Valid_Distance] м, увеличивает враждебность цели к персонажу и на короткое время уменьшает скорость атаки врага.",
        "kn_invinsibleprotect": "Создает защитный барьер, способный с вероятностью [%e1.Shield.ConditionProb]% блокировать урон. Необходимое условие: [%e1.Shield.Condition] на персонажа или членов его группы в радиусе 30 м вокруг него. Время действия: [%e1.Shield.RemainTime] [%e2.StatUp.StatName] +[%e2.StatUp.Value]. (Защитный барьер может на [%e1.Shield.CoverValue]% блокировать урон, наносимый персонажу за 1 раз.)",
        "kn_invinsibleshield": "Блокирует щитом атаки противника. Количество блокировок: [%e1.AlwaysBlock.Count]. Время действия: [%e1.AlwaysBlock.RemainTime]\nНеобходим щит.",
        "kn_massiveprovoke": "Провоцирует от 1 до 5 целей, насмехаясь над ними. Радиус действия: 10 м.",
        "kn_movingstance": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]%. [%e1.StatUp.StatName3] +[%e1.StatUp.Value3]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e2.StatUp.StatName2] +[%e2.StatUp.Value2]. [%e2.StatUp.StatName3] +[%e2.StatUp.Value3].\nИспользование других умений прерывает действие этого умения. Невозможно выполнять прыжки.\nНеобходим щит.\nАктивное умение",
        "kn_powersink": "Удар магией земли, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.\n3-е умение в серии\nКритический удар - Разрушительный магический удар",
        "kn_recover": "Восстанавливает [%e1.Heal_Instant.Heal] HP.",
        "kn_reflectshield": "[%e2.StatBoost.StatName] +[%e2.StatBoost.FixValue]. [%e3.StatBoost.StatName] +[%e3.StatBoost.RateValue]%. [%e4.StatBoost.StatName] +[%e4.StatBoost.FixValue]. Отражает [%e1.Reflector.FixedDamage] ед. урона во врага, использующего действие [%e1.Reflector.Condition] на вашего персонажа, в радиусе [%e1.Reflector.MaxRange] м.\nИспользование других умений прерывает действие этого умения, невозможно выполнять прыжки.\nНеобходим щит.\nАктивное умение",
        "kn_revivaltouch": "Восстанавливает за счет своих HP [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м.",
        "kn_sentinel": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Действует на вас и 6 ваших союзников в радиусе 30 м от вас. Время действия: [%e1.StatUp.RemainTime]",
        "kn_stigma_demonpunishment_dark": "Наносит цели [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] ед. урона. Переводит [%e1.SkillATKDrain_Instant.HPHeal]% нанесенного урона в HP.",
        "kn_stigma_drainsword_dark": "Стигма древнего даэва. Наносит цели [%e1.SkillATKDrain_Instant.MinDamage]-[%e1.SkillATKDrain_Instant.MaxDamage] ед. урона. Переводит [%e1.SkillATKDrain_Instant.HPHeal]% нанесенного урона в HP.",
        "kn_stigma_godjudgement_light": "Стигма древнего даэва. Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона и оглушает ее. Время действия: [%e2.Stun.RemainTime]",
        "kn_stigma_godpunishment_light": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона и оглушает ее. Время действия: [%e2.Stun.RemainTime]",
        "kn_stigma_resistarmor": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Время действия: [%e1.StatUp.RemainTime]",
        "kn_stunningsnacher": "Притягивает врага в радиусе [%First_Target_Valid_Distance] м к персонажу, увеличивает его враждебность и снижает его скорость движения. Время действия: [%e2.Snare.RemainTime]",
        "kn_thunderblade": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м.",
        "kn_triplesnacher": "Притягивает цель и еще 2 врагов в радиусе [%First_Target_Valid_Distance] м к персонажу, увеличивает их враждебность и снижает их скорость движения. Время действия: [%e2.Snare.RemainTime]",
        "p_equip_dual": "Улучшает мастерство владения парным оружием.",
        "pr_bindingheal": "Восстанавливает [%e1.Heal_Instant.Heal] HP вашего персонажа и выбранного члена вашей группы, находящегося в радиусе [%First_Target_Valid_Distance] м. Действует только на членов вашей группы.",
        "pr_blindinglight": "Ослепляет цель. Время действия: [%e1.Blind.RemainTime]",
        "pr_calllightning": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.",
        "pr_coursewound": "Удар магией воды, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона в радиусе [%First_Target_Valid_Distance] м. Снижает полученный целью эффект магического восстановления на 50%. Время действия: [%e2.DeboostHealAmount.RemainTime]",
        "pr_eternalservent_dark": "Призывает святую мощь. Дух не может двигаться. Атакует цель в радиусе 30 м, нанося дистанционно [%e0.EternalServent_G1.e1.SpellATK_Instant.FixDamage] ед. урона магией огня. Исчезает через некоторое время. При каждой атаке тратит свои HP.",
        "pr_eternalservent_light": "Призывает святую мощь. Дух не может двигаться. Атакует цель в радиусе 30 м, нанося дистанционно [%e0.EternalServent_G1.e1.SpellATK_Instant.FixDamage] ед. урона магией огня. Исчезает через некоторое время. При каждой атаке тратит свои HP.",
        "pr_firstaid": "Восстанавливает [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м.",
        "pr_graceofgod": "Позволяет применять умение без затрат MP. Время действия: [%e1.BoostSkillCost.RemainTime]",
        "pr_healershand": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Во время действия умения расход МР увеличивается на 10%.\nАктивное умение",
        "pr_healinggrace": "На 50% увеличивает эффект восстановления у членов группы в радиусе 25 м от произносящего заклинание. Время действия: [%e1.DeboostHealAmount.RemainTime]",
        "pr_healingservent_dark": "Призывает духа исцеления. Дух неподвижен. Действует на персонажей в радиусе 30 метров и восстанавливает HP 6 членов альянса на [%e0.PR_Dark_Totem_HealingServent_G1.e1.Heal_Instant.Heal]. Дух исчезает через определенное время.",
        "pr_healingservent_light": "Призывает духа исцеления. Дух неподвижен. Действует на персонажей в радиусе 30 метров и восстанавливает HP 6 членов альянса на [%e0.PR_Light_Totem_HealingServent_G1.e1.Heal_Instant.Heal]. Дух исчезает через определенное время.",
        "pr_massdispel": "Снимает все злые чары с вашего персонажа и членов вашей группы, находящихся в радиусе 25 м.",
        "pr_massemergentheal": "Восстанавливает [%e1.Heal_Instant.Heal] HP персонажа и членов группы. Радиус действия: 25 м.",
        "pr_memoryblur": "Уменьшает враждебность цели к персонажу. Радиус действия: [%First_Target_Valid_Distance] м.",
        "pr_offensivemode": "[%e1.StatBoost.StatName] +[%e1.StatBoost.FixValue]. [%e2.StatBoost.StatName] +[%e2.StatBoost.FixValue]. [%e3.StatDown.StatName] - 150.\nАктивное умение",
        "pr_painlinks": "Удар магией земли, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м. Наносит дополнительно [%e2.SpellATK.Damage] ед. урона с интервалом в [%e2.SpellATK.CheckTime] Время действия: [%e2.SpellATK.RemainTime] [%e4.StatDown.StatName] -[%e4.StatDown.Value]. Если цель умрет во время действия эффекта, она возродится у своего кибелиска или ники.",
        "pr_powersmite": "Удар магией земли, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона в радиусе [%First_Target_Valid_Distance] м.\n1-е умение в серии",
        "pr_purgatory": "Удар магией земли, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона и [%e2.SpellATK.Damage] ед. урона с интервалом в [%e2.SpellATK.CheckTime] Радиус действия: [%First_Target_Valid_Distance] м. Время действия: [%e2.SpellATK.RemainTime]",
        "pr_regeneraitionshine": "Восстанавливает [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м, а также дополнительно восстанавливает [%e2.Heal.CheckTimeHeal] HP с интервалом в [%e2.Heal.CheckTime] [%e3.StatUp.StatName] +[%e3.StatUp.Value]. Время действия: [%e2.Heal.RemainTime]",
        "pr_restorelife": "Восстанавливает [%e1.CaseHeal.Heal] ед. HP цели, если они понизятся до 50% и ниже. Время действия: 1 мин.",
        "pr_reversecondition": "Меняет местами ваши MP и HP.",
        "pr_revivehand": "Благословляет члена группы, находящегося в радиусе [%First_Target_Valid_Distance] м. Время действия: [%e1.Rebirth.RemainTime] При смерти во время действия умения цель воскресает с [%e1.Rebirth.CurrentHPMP]% HP и MP.",
        "pr_sageswisdom": "Уменьшает время подготовки умений на [%e1.BoostSkillCastingTime.CastingBonus]%. Время действия: [%e1.BoostSkillCastingTime.RemainTime]",
        "pr_sprint": "Повышает скорость движения на 30%. Максимальное время действия: 10 сек.",
        "pr_stigma_abysalcircle_dark": "Стигма древнего даэва. Восстанавливает [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м и HP 6 союзников в радиусе 25 м от цели. Также создает защитный барьер, предотвращающий урон на [%e2.Shield.CoverValue] каждый раз при получении [%e2.Shield.Condition]. Максимум предотвращаемого урона: [%e2.Shield.ShieldValue]. Время действия: [%e2.Shield.RemainTime]",
        "pr_stigma_abysalsanctuary_dark": "Восстанавливает [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м и 6 союзников в радиусе 25 м от цели. Также создает защитный барьер, предотвращающий урон на [%e2.Shield.CoverValue] каждый раз, когда на персонажа проводится [%e2.Shield.Condition]. Максимум предотвращаемого урона: [%e2.Shield.ShieldValue]. Время действия: [%e2.Shield.RemainTime]",
        "pr_stigma_divinecircle_light": "Стигма древнего даэва. Восстанавливает [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м и 6 союзников в радиусе 25 м от цели, а также дополнительно восстанавливает [%e2.Heal.CheckTimeHeal] HP с интервалом в [%e2.Heal.CheckTime] Время действия: [%e2.Heal.RemainTime]",
        "pr_stigma_divinesanctuary_light": "Восстанавливает [%e1.Heal_Instant.Heal] HP цели в радиусе [%First_Target_Valid_Distance] м и 6 союзников в радиусе 25 м от цели, а также дополнительно восстанавливает [%e2.Heal.CheckTimeHeal] HP с интервалом в [%e2.Heal.CheckTime] Время действия: [%e2.Heal.RemainTime]",
        "pr_stigma_suggestion": "Уменьшает враждебность цели и 6 врагов в радиусе 20 м от нее к персонажу. Радиус действия: [%First_Target_Valid_Distance] м.",
        "pr_suffermemory": "Удар магией воздуха, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона сразу, затем наносит по [%e2.SpellATK.Damage] ед. урона магией земли в течение [%e2.SpellATK.RemainTime] с интервалом в [%e2.SpellATK.CheckTime] [%e3.StatDown.StatName] цели -[%e3.StatDown.Value]. Радиус действия: [%First_Target_Valid_Distance] м.",
        "pr_thunderofpunishment": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.",
        "pr_tranquility": "Снимает до 3 злых чар с персонажа и 6 его союзников в радиусе 20 м, а также восстанавливает [%e2.Heal.CheckTimeHeal] HP.",
        "ra_backdashstab": "Наносит противнику [%e1.BackDashATK.MinDamage]-[%e1.BackDashATK.MaxDamage] ед. урона, отбрасывая вашего персонажа на 25 м назад. Дает шанс оглушить противника на [%e2.Stun.RemainTime]",
        "ra_blazingtrap_dark": "Для установки ловушки требуется семя трипида (20 шт.). При приближении противника мина взрывается. Радиус действия: 5 м. Время действия ловушки: [%e1.SummonTrap.SummonTime]",
        "ra_blazingtrap_light": "Для установки ловушки требуется семя трипида (20 шт.). При приближении противника мина взрывается. Радиус действия: 5 м. Время действия ловушки: [%e1.SummonTrap.SummonTime]",
        "ra_breathofnature": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. Время действия: [%e1.StatUp.RemainTime]",
        "ra_callcompanion_dark": "Призывает симургов ([%e1.SummonHoming.UnitNumber] шт.), которые наносят физический урон противникам в радиусе [%First_Target_Valid_Distance] м. Каждая атака симурга снижает скорость движения цели.",
        "ra_callcompanion_light": "Призывает симургов ([%e1.SummonHoming.UnitNumber] шт.), которые наносят физический урон противникам в радиусе [%First_Target_Valid_Distance] м. Каждая атака симурга снижает скорость движения цели.",
        "ra_draineye": "При каждой атаке в течение [%e1.Provoker.RemainTime] есть вероятность [%e1.Provoker.ConditionProb]% восстановить MP персонажа.",
        "ra_enchantbow": "[%e1.WeaponStatUp.StatName] +[%e1.WeaponStatUp.Value]%. Оружие: [%e1.WeaponStatUp.WeaponCategory]. Время действия: [%e1.WeaponStatUp.RemainTime]",
        "ra_explosionarrow": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ra_fairyflare_dark": "Ставит дистанционную ловушку в радиусе [%First_Target_Valid_Distance] м. При приближении противника ловушка взрывается и снимает с него маскировку. Время действия ловушки: [%e1.SummonTrap.SummonTime] Радиус действия: 10 м.",
        "ra_fairyflare_light": "Ставит дистанционную ловушку в радиусе [%First_Target_Valid_Distance] м. При приближении противника ловушка взрывается и снимает с него маскировку. Время действия ловушки: [%e1.SummonTrap.SummonTime] Радиус действия: 10 м.",
        "ra_heavenstrap_dark": "Для установки ловушки требуется семя трипида (3 шт.). При приближении противника ловушка взрывается, и цель попадает в воздушные оковы. Время действия ловушки: [%e1.SummonTrap.SummonTime] Радиус действия: 5 м.",
        "ra_heavenstrap_light": "Для установки ловушки требуется семя трипида (3 шт.). При приближении противника ловушка взрывается, и цель попадает в воздушные оковы. Время действия ловушки: [%e1.SummonTrap.SummonTime] Радиус действия: 5 м.",
        "ra_huntermind": "После использования умения атакует критическим ударом. Количество атак: [%e1.OneTimeBoostSkillCritical.BoostCount]. Время действия: [%e1.OneTimeBoostSkillCritical.RemainTime] [%e2.WeaponStatUp.StatName] уменьшается на 5 м. Оружие: [%e2.WeaponStatUp.WeaponCategory].",
        "ra_instantsprint": "Снимает все эффекты, связанные с перемещением, и мгновенно перемещает на 10 м вперед.",
        "ra_lightningshot": "Физическая атака, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м и оглушает ее.",
        "ra_marksmanmode": "[%e1.WeaponStatBoost.StatName] +[%e1.WeaponStatBoost.RateValue]%. Оружие: [%e1.WeaponStatBoost.WeaponCategory]. В это время вы передвигаетесь очень медленно.\nАктивное умение",
        "ra_massexplosionarrow": "Физическая атака, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ra_movingshot": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ra_painarrow": "Посылает стрелу в цель в радиусе [%First_Target_Valid_Distance] м, наносит ей [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] физического урона и отравляет ее на [%e2.Poison.RemainTime]",
        "ra_panthermove": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. [%e3.WeaponStatUp.StatName] +[%e3.WeaponStatUp.Value]%. Требуемое оружие: [%e3.WeaponStatUp.WeaponCategory]. Время действия: [%e1.StatUp.RemainTime]",
        "ra_paralyzearrow": "Усыпляет цель в радиусе [%First_Target_Valid_Distance] м. Время действия: [%e1.Sleep.RemainTime] Однако [%e2.StatUp.StatName] увеличивается на [%e2.StatUp.Value].",
        "ra_rapidshot": "Физическая атака, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона оглушенной, опрокинутой или повернутой цели; цели, которую оттолкнули или заключили в воздушные оковы. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ra_resistmind": "Снимает одни злые чары и рассеивает урон от магии. Количество раз: [%e2.AlwaysResist.Count]. Время действия: [%e2.AlwaysResist.RemainTime]",
        "ra_sealingarrow": "Наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м. На [%e2.BoostSkillCastingTime.RandomTime]-[%e2.BoostSkillCastingTime.RemainTime] увеличивает время подготовки умений на 100% и уменьшает скорость атаки.",
        "ra_shadowarrow": "Физическая атака, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона с большим шансом критической атаки. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ra_silentarrow": "Физическая атака, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м и вводит ее в состояние немоты. Время действия: [%e2.Silence.RandomTime]-[%e2.Silence.RemainTime]",
        "ra_snakebitetrap_dark": "Устанавливает ловушку около персонажа. При приближении противника ловушка взрывается, нанося урон 4 противникам и заключая их в воздушные оковы. Время действия ловушки: [%e1.SummonTrap.SummonTime] Радиус действия: 10 м.",
        "ra_snakebitetrap_light": "Устанавливает ловушку около персонажа. При приближении противника ловушка взрывается, нанося урон 4 противникам и заключая их в воздушные оковы. Время действия ловушки: [%e1.SummonTrap.SummonTime] Радиус действия: 10 м.",
        "ra_spoutarrow": "Физическая атака, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона цели и противникам, находящимся на расстоянии до 5 м от нее. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ra_stigma_ancientarrow_light": "Физическая атака с небольшой точностью, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ra_stigma_destructarrow_dark": "Стигма древнего даэва. Физическая атака с небольшой точностью, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ra_stigma_mysticarrow_dark": "Физическая атака с небольшой точностью, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ra_stigma_phoenixarrow_light": "Стигма древнего даэва. Физическая атака с небольшой точностью, наносит [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ra_stigma_tigereye": "[%e1.WeaponStatUp.StatName] -10 м. [%e2.WeaponStatUp.StatName] +[%e2.WeaponStatUp.Value]%. [%e3.WeaponStatUp.StatName] +[%e3.WeaponStatUp.Value]%. Оружие: [%e1.WeaponStatUp.WeaponCategory]. Время действия: [%e1.WeaponStatUp.RemainTime]",
        "ra_throwingtrap_dark": "Для установки ловушки необходимы семена трипида (3 шт.). При активации ловушки цель обездвиживается, ее способность к уклонению снижается. Время действия: [%e1.SummonTrap.SummonTime] Радиус действия: 5 м.",
        "ra_throwingtrap_light": "Для установки ловушки необходимы семена трипида (3 шт.). При активации ловушки цель обездвиживается, ее способность к уклонению снижается. Время действия: [%e1.SummonTrap.SummonTime] Радиус действия: 5 м.",
        "ra_trackermind": "[%e1.WeaponStatUp.StatName] +[%e1.WeaponStatUp.Value]%. Оружие: [%e1.WeaponStatUp.WeaponCategory]. Во время действия умения расход МР увеличивается на 10%.\nАктивное умение",
        "ri_bindingslam": "Удар магией ветра, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона и сковывает ее. Время действия: [%e2.Root.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "ri_chainfire": "Удар магией огня, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.\n2 повтора\n2-е умение в серии\nОгненный шквал - Непрерывный огонь",
        "ri_eathiumblast": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.",
        "ri_eathiumblast_2": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.",
        "ri_eathiumblast_3": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели и максимум 6 противникам, находящимся на расстоянии до 5 м от нее. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ri_eathiumcompress": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. [%e1.StatUp.StatName3] +[%e1.StatUp.Value3]. Время действия: [%e1.StatUp.RemainTime] ",
        "ri_eathiumcurtain": "Защищает от следующей магической атаки 1 раз или 1 раз парирует физическую атаку. Время действия: [%e1.AlwaysResist.RemainTime]",
        "ri_eathiumreactive": "Восстанавливает [%e1.MpHeal_Instant.Heal] MP.",
        "ri_eathiumreactive_2": "Восстанавливает [%e1.MpHeal_Instant.Heal] MP.",
        "ri_eathiumreactive_3": "Восстанавливает [%e1.MpHeal_Instant.Heal] MP.",
        "ri_eathiumwall": "Создает защитный барьер, с вероятностью [%e1.MPShield.ConditionProb]% блокирующий [%e1.MPShield.CoverValue]% урона. Необходимое условие: [%e1.MPShield.Condition]. Время действия: 30 сек. Защитный барьер сохраняется до нанесения персонажу [%e1.MPShield.ShieldValue] ед. урона. Также расходуется [%e1.MPShield.LoseMP]% MP в зависимости от полученного урона.\nВо время действия защитного барьера сопротивление шоку +[%e2.StatUp.Value], [%e2.StatUp.StatName2] +[%e2.StatUp.Value2], а сопротивление усыплению -[%e3.StatDown.Value].\nАктивное умение",
        "ri_flamethrow": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона максимум 3 врагам в радиусе 15 м от передней полусферы.",
        "ri_flamethrow_2": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона максимум 4 врагам в радиусе 15 м от передней полусферы и с определенным шансом оглушает их.",
        "ri_flamethrow_3": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона максимум 6 врагам в радиусе 15 м от передней полусферы и с определенным шансом оглушает их.",
        "ri_forwardstrike": "Атака магией воды, наносит целям в радиусе 15 м от передней полусферы [%e1.SpellATK_Instant.FixDamage] ед. урона.\n2-е умение в серии\nОхлаждающий удар - Сокрушающая волна",
        "ri_itheumreflector": "При каждом получении урона отнимает [%e1.Provoker.OtherSkill.e1.MPAttack_Instant.Damage] MP цели. Время действия: [%e1.Provoker.RemainTime]",
        "ri_magneticfield": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Сопротивление оглушению, запрету на использование физических умений и страху +[%e2.StatUp.Value]. Снижает урон, получаемый в PvP. Время действия: [%e1.StatUp.RemainTime]",
        "ri_overcharge": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. Наносит дополнительный урон в PvP. Время действия: [%e1.StatUp.RemainTime]",
        "ri_poweroverdrive": "Снимает с персонажа наложенные эффекты снижения скорости атаки. На 30 сек. сопротивление шоку +[%e1.StatUp.Value], [%e1.StatUp.StatName2] +[%e1.StatUp.Value2], сопротивление отрицательным эффектам передвижения +[%e2.StatUp.Value].\nАктивное умение",
        "ri_powerslam": "Удар магией огня, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.",
        "ri_rapidattack": "Атака магией земли, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.\n3 повтора\n2-е умение в серии\nДробящий удар - Град атак",
        "ri_rapidcharge": "Восстанавливает [%e1.MPHeal_Instant.Heal] MP.",
        "ri_shielddestroyer": "Удар магией земли, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона, оглушает ее и снимает защитные эффекты. Радиус действия: [%First_Target_Valid_Distance] м.",
        "ri_speedoverdrive": "Скорость передвижения и полета +[%e1.StatUp.Value]%. [%e3.StatUp.StatName] +[%e3.Statup.Value]. [%e2.StatDown.StatName] -[%e2.StatDown.Value]. [%e2.StatDown.StatName3] -[%e2.StatDown.Value3]. Время действия: 10 сек.\nАктивное умение",
        "ri_tunesensor": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]%. Время действия: [%e1.StatUp.RemainTime]",
        "ri_weaponsmash": "Удар магией воздуха, наносит цели в радиусе [%First_Target_Valid_Distance] м [%e1.SpellATK_Instant.FixDamage] ед. урона. При этом ее [%e2.StatDown.StatName] -[%e2.StatDown.Value], [%e2.StatDown.StatName2] -[%e2.StatDown.Value2]. Время действия: [%e2.StatDown.RemainTime]",
        "sc_trueshotmind": "[%e1.OneTimeBoostSkillAttack.AttackType] +[%e1.OneTimeBoostSkillAttack.BonusRate]%. Количество атак: [%e1.OneTimeBoostSkillAttack.AttackCount]. Время действия: [%e1.OneTimeBoostSkillAttack.RemainTime] [%e2.StatDown.StatName] -[%e2.StatDown.Value]%.",
        "wa_gatecrush": "Физическая атака, наносит цели [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] ед. урона. Если цель - ворота, то дополнительно наносит [%e1.SkillATK_Instant.AddDamage] ед. урона.",
        "wa_steadiness": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Время действия: [%e1.StatUp.RemainTime]",
        "wi_arcaneboost": "Уменьшает время подготовки магических умений на [%e1.BoostSkillCastingTime.CastingBonus]%. Время действия: [%e1.BoostSkillCastingTime.RemainTime]",
        "wi_arcanepower": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Время действия: [%e1.StatUp.RemainTime]",
        "wi_arcanewisdom": "Снижает расход MP на [%e1.BoostSkillCost.BonusRate]%. Время действия: [%e1.BoostSkillCost.RemainTime]",
        "wi_countermagic": "Каждый раз, когда цель использует магические умения, она наносит себе [%e1.MagicCounterATK.Damage]% урона от своих макс. HP. Радиус действия: [%First_Target_Valid_Distance] м. (Наносимый урон не может превышать [%e1.MagicCounterATK.MaxDamage].) Время действия: [%e1.MagicCounterATK.RemainTime]",
        "wi_cursedtree": "Превращает цель в дерево. Время действия: [%e1.Deform.RemainTime] В превращенном состоянии цель не может передвигаться и совершать любые действия. [%e3.StatUp.StatName] цели увеличивается. Эффект исчезает при получении урона.",
        "wi_cyclonestrike": "Удар магией воздуха, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.",
        "wi_deepsleep": "Усыпляет цель. [%e3.StatUp.StatName] увеличивается. Время действия: [%e2.Sleep.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "wi_deepsleep_2": "Усыпляет цель. [%e3.StatUp.StatName] увеличивается. Время действия: [%e2.Sleep.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "wi_deepsleep_3": "Усыпляет цель. [%e3.StatUp.StatName] увеличивается. Время действия: [%e2.Sleep.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "wi_elementalseal": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e2.StatUp.StatName] +[%e2.StatUp.Value]. Время действия: [%e1.StatUp.RemainTime] ",
        "wi_flamestrike": "Удар магией огня, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м.",
        "wi_frostpillar_dark": "Удар магией воды, в течение 20 сек. наносит урон в определенном радиусе максимум 6 противникам, снижая их скорость движения.",
        "wi_frostpillar_light": "Удар магией воды, в течение 20 сек. наносит урон в определенном радиусе максимум 6 противникам, снижая их скорость движения.",
        "wi_hibernation": "Замораживает цель в радиусе [%First_Target_Valid_Distance] м, оглушая ее и делая невосприимчивой к атакам. Время действия: [%e1.stun.RandomTime]-[%e1.stun.RemainTime]",
        "wi_hpmpexchange": "Меняет местами ваши MP и HP.",
        "wi_icebarrier": "Создает защитный барьер, поглощающий [%e1.Shield.CoverValue] ед. урона. Необходимое условие: [%e1.Shield.Condition] на персонажа. Время действия: [%e1.Shield.RemainTime] Вы оглушены на время действия данного умения.",
        "wi_icyshield": "Отражает [%e1.Reflector.FixedDamage] ед. урона во врага в радиусе [%e1.Reflector.MaxRange] м. Необходимое условие: [%e1.Reflector.Condition]. Время действия: [%e1.Reflector.RemainTime] Скорость движения и атаки врага уменьшается. Время действия: [%e2.Provoker.OtherSkill.e1.Snare.RemainTime]",
        "wi_icyveins_dark": "Уменьшает время подготовки умений на [%e1.BoostSkillCastingTime.CastingBonus]%. Время действия: [%e1.BoostSkillCastingTime.RemainTime]",
        "wi_icyveins_light": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. [%e1.StatUp.StatName2] +[%e1.StatUp.Value2]. Время действия: [%e1.StatUp.RemainTime]",
        "wi_illusiondance": "Снимает с вас 1 физический негативный эффект и позволяет уклониться от физических атак. Количество уклонений: [%e2.AlwaysDodge.Count]. Время действия: [%e2.AlwaysDodge.RemainTime]",
        "wi_illusionstorm": "Магическая атака огнем, наносит 6 целям в радиусе 10 м [%e1.SpellATK_Instant.FixDamage] ед. урона. Оглушает противника на [%e2.Stun.RemainTime]",
        "wi_massexplosion": "Удар магией огня, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона цели в радиусе [%First_Target_Valid_Distance] м от вашего персонажа и 6 противникам в радиусе 5 м от выбранной цели.",
        "wi_rockfall": "Удар магией земли, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона в радиусе [%First_Target_Valid_Distance] м.",
        "wi_sleepingstorm": "Усыпляет цель в радиусе [%First_Target_Valid_Distance] м от персонажа и 6 противников в радиусе 12 м вокруг нее. [%e2.StatUp.StatName] противников в зоне действия умения увеличивается. Время действия: [%e1.Sleep.RemainTime]",
        "wi_soulgain": "[%e1.StatUp.StatName] +[%e1.StatUp.Value]. Время действия: [%e1.StatUp.RemainTime]",
        "wi_stigma_atomicenergy_dark": "Стигма древнего даэва. Удар магией огня, через [%e1.DelayedSpellATK_Instant.DelayedTime] наносит [%e1.DelayedSpellATK_Instant.Damage] ед. урона цели, находящейся на расстоянии не более [%First_Target_Valid_Distance] м, и 6 противникам в радиусе 10 м от нее.",
        "wi_stigma_atomicenergy_light": "Стигма древнего даэва. Удар магией огня, через [%e1.DelayedSpellATK_Instant.DelayedTime] наносит [%e1.DelayedSpellATK_Instant.Damage] ед. урона цели, находящейся на расстоянии не более [%First_Target_Valid_Distance] м, и 6 противникам в радиусе 10 м от нее.",
        "wi_stigma_icelance": "Удар магией воды, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона в радиусе [%First_Target_Valid_Distance] м.",
        "wi_stigma_lavawave_dark": "Удар магией огня, через [%e1.DelayedSpellATK_Instant.DelayedTime] наносит [%e1.DelayedSpellATK_Instant.Damage] ед. урона цели, находящейся на расстоянии не более [%First_Target_Valid_Distance] м, и 6 противникам в радиусе 10 м от нее.",
        "wi_stigma_volcanicflame_light": "Удар магией огня, через [%e1.DelayedSpellATK_Instant.DelayedTime] наносит [%e1.DelayedSpellATK_Instant.Damage] ед. урона цели, находящейся на расстоянии не более [%First_Target_Valid_Distance] м, и 6 противникам в радиусе 10 м от нее.",
        "wi_stormshock": "Магическая атака ветром, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона и на некоторое время оглушает ее. Радиус действия: [%First_Target_Valid_Distance] м.",
        "wi_summontornado_dark": "Появляется рядом с целью, находящейся в радиусе [%First_Target_Valid_Distance] м, наносит урон магией воздуха максимум 6 врагам в пределах 10 м, на короткое время вызывает оглушающий торнадо. Время действия: [%e1.SummonSkillArea.SummonTime]",
        "wi_summontornado_light": "Появляется рядом с целью, находящейся в радиусе [%First_Target_Valid_Distance] м, наносит урон магией воздуха максимум 6 врагам в пределах 10 м, на короткое время вызывает оглушающий торнадо. Время действия: [%e1.SummonSkillArea.SummonTime]",
        "wi_wakeup": "Пробуждает цель в радиусе [%First_Target_Valid_Distance] м.",
        "wi_windcutter": "Магическая атака ветром, наносит цели [%e1.SpellATK_Instant.FixDamage] ед. урона и вызывает кровотечение. Время действия: [%e2.Bleed.RemainTime] Радиус действия: [%First_Target_Valid_Distance] м.",
        "wi_zeropoint": "Удар магией воды, наносит [%e1.SpellATK_Instant.FixDamage] ед. урона в радиусе [%First_Target_Valid_Distance] м."
    }
});
