lang = $.extend(lang, {
    base: {
        'sec': 'sec',
        'min': 'min.',
        'hour': 'h.',
        'novalue': '[no value]',
        'reqlvl': 'Available at level %1',
        'lvl': 'Lvl.',
        'shards': 'Requires %1 shards',
        'nodesc': 'No description',
        'cost': 'Skill cost',
        'cooltime': 'Cooldown',
        'casttime': 'Cast time',
        'instant': 'Instant',
        'stage': 'Stage %1',
        'dist': 'Range',
        'target': 'Target',
        'selected': 'Selected target',
        'self': 'Self',
        'pet': 'Pet',
        'targetpoint': 'Designated area',
        'targetarea': 'Area within a Radius of Target (%1 people)',
        'area': 'Area',
        'aroundcaster': 'Area around caster (%1 people)',
        'ally': 'Group member',
        'enmity': 'Enmity',
        'pvpdmgratio': 'PvP Damage',
        'pvpremaintimeratio': 'PvP Duration',
        'candispel': 'Dispelable',
        'canmove': 'Can move while casting',
        'canjumpshot': 'Can jumpshot',
        'cancelrate': 'Cancel rate',
        'critprob': 'Crit rate',
        'slow': 'Slow',
        'dispeldebuff': 'Removes %1 HP from %2 %3 effect(s) of level %4 maximum',
        'dispelbuff': 'Removes %1 HP from %2 buff(s) of level %3 maximum',
        'mag': 'magical',
        'phy': 'physical',
        'neg': 'negative',
        'true': 'Yes',
        'false': 'No',
        'version': 'Version',
        'title': 'Aion Classic Stigma Calculator - %1'
    },
    other: {
        everyhit: 'attack',
        stumble: 'Stumble',
        openaerial: 'openaerial',
        nmlatk: 'attack',
        phhit: 'physical attack',
        magical: 'magical attacks',
        attackrange: 'Attack range',
        bow: 'Bow',
        physical: 'Physical attack',
        pmdefend: 'Physical defend and all elemental defenses',
        pmattack: 'Physical and magical attack'
    }
});
