lang = $.extend(lang, {
    base: {
        'sec': 'sec',
        'min': 'min.',
        'hour': 'h.',
        'novalue': '[no value]',
        'reqlvl': 'Available at level %1',
        'lvl': 'Lvl.',
        'shards': 'Requires %1 shards',
        'nodesc': 'No description',
        'cost': 'Skill cost',
        'cooltime': 'Cooldown',
        'casttime': 'Cast time',
        'instant': 'Instant',
        'stage': 'Stage %1',
        'dist': 'Range',
        'target': 'Target',
        'selected': 'Selected target',
        'self': 'Self',
        'pet': 'Pet',
        'targetpoint': 'Designated area',
        'targetarea': 'Area within a Radius of Target (%1 people)',
        'area': 'Area',
        'aroundcaster': 'Area around caster (%1 people)',
        'ally': 'Group member',
        'enmity': 'Enmity',
        'pvpdmgratio': 'PvP Damage',
        'pvpremaintimeratio': 'PvP Duration',
        'candispel': 'Dispelable',
        'canmove': 'Can move while casting',
        'canjumpshot': 'Can jumpshot',
        'cancelrate': 'Cancel rate',
        'critprob': 'Crit rate',
        'slow': 'Slow',
        'dispeldebuff': 'Removes %1 HP from %2 %3 effect(s) of level %4 maximum',
        'dispelbuff': 'Removes %1 HP from %2 buff(s) of level %3 maximum',
        'mag': 'magical',
        'phy': 'physical',
        'neg': 'negative',
        'true': 'Yes',
        'false': 'No',
        'version': 'Change version',
        'title': 'Aion Classic Stigma Calculator - %1'
    },
    other: {
        everyhit: 'attack',
        stumble: 'Stumble',
        openaerial: 'openaerial',
        nmlatk: 'attack',
        phhit: 'physical attack',
        magical: 'magical attacks',
        attackrange: 'Attack range',
        bow: 'Bow',
        physical: 'Physical attack',
        pmdefend: 'Physical defend and all elemental defenses',
        pmattack: 'Physical and magical attack'
    },
    'skillnames': {
        "as_assaultslash": "Dash and Slash",
        "as_backblow": "Searching Strike",
        "as_blindingburst": "Blinding Burst",
        "as_blindside": "Ambush",
        "as_carvesignetchain": "Sigil Strike",
        "as_chainsignetburst": "Agony Rune",
        "as_defendroar_dark": "Slayer Form",
        "as_defendroar_light": "Slayer Form",
        "as_explosionpoison": "Apply Lethal Venom",
        "as_flashslash": "Lightning Slash",
        "as_hitmanmind": "Oath of Accuracy",
        "as_mirrorattack": "Throw Shuriken",
        "as_quickmove": "Flurry",
        "as_runnersstance": "Break Away",
        "as_senseboost": "Sensory Boost",
        "as_shadowdodge": "Flash of Speed",
        "as_shadowdrop": "Shadowfall",
        "as_signetflare": "Rune Burst",
        "as_signetwave": "Rune Knife",
        "as_silentburst": "Signet Silence",
        "as_stabstance": "Deadly Abandon",
        "as_stigma_demonicburst_dark": "Ancestral Darkness Rune",
        "as_stigma_moonburst_dark": "Rune Swipe",
        "as_stigma_novaburst_light": "Ancestral Radiant Rune",
        "as_stigma_shadowwalk": "Shadow Walk",
        "as_stigma_sunburst_light": "Divine Rune",
        "as_stunburst": "Explosive Burst",
        "as_stuningintention": "Apply Deadly Poison",
        "as_tigerassault": "Beastly Scar",
        "as_venomslash": "Quickening Doom",
        "as_venomstab": "Venomous Strike",
        "as_visiouseye": "Eye of Wrath",
        "as_whisperofgale": "Aethertwisting",
        "as_windslash": "Agonizing Slash",
        "ba_delayparalyze": "Staggered Rest",
        "ba_focusdefence": "Mvt. 1: Spring ",
        "ba_lullaby": "Freestyle",
        "ba_playingstyleschangea": "Exultation",
        "ba_playingstyleschangeb": "Impassion",
        "ba_sanctuary": "Mvt. 4: Winter",
        "ba_songofbind": "Composer's Bar",
        "ba_songofbless": "Chorus of Blessing",
        "ba_songofbrave": "Mvt. 2: Summer",
        "ba_songofearth": "Stinging Note",
        "ba_songoffirm": "Mvt. 3: Autumn",
        "ba_songofgale": "Treble Cleave",
        "ba_songofmanareverse": "Half-Stop",
        "ba_songofmassheal": "Soothing Hymn",
        "ba_songofpain": "Paean of Pain",
        "ba_songofregeneration": "Hymn of Rejuvenation",
        "ba_songofresurrection": "Cherubim Call",
        "ba_songofserenity": "Resonant Hymn",
        "ba_songogpeace": "Ode to Friendship",
        "ch_blessprotect": "Blessing of Stone",
        "ch_chakra": "Stamina Restoration",
        "ch_chant_improvedcritical": "Hit Mantra",
        "ch_chant_improvedresiststun": "Enhancement Mantra",
        "ch_chant_invincible": "Invincibility Mantra",
        "ch_encouragerun": "Acceleration Cheer",
        "ch_harshthrust": "Leaping Flash",
        "ch_healingtank": "Healing Conduit",
        "ch_heroicstrike": "Soul Crush",
        "ch_imbuepower": "Blessing of Wind",
        "ch_improvedallattack": "Word of Inspiration",
        "ch_improvedalldefend": "Word of Protection",
        "ch_improvedbody": "Elemental Screen",
        "ch_improvedlifestream": "Word of Life",
        "ch_mountaincrash": "Mountain Crash",
        "ch_mpheal": "Magic Recovery",
        "ch_nightwish": "Rage Spell",
        "ch_phoenixstep": "Rise",
        "ch_protectself": "Protective Ward",
        "ch_shockwave": "Disorienting Blow",
        "ch_slowcrash": "Numbing Blow",
        "ch_soaredrock": "Soul Lock",
        "ch_splashswing": "Splash Swing",
        "ch_stigma_angelicwall_light": "Divine Curtain",
        "ch_stigma_angelicwish_light": "Ancestral Word of Spellstopping",
        "ch_stigma_demonicwall_dark": "Curtain of Aether",
        "ch_stigma_demonicwish_dark": "Ancestral Aetheric Field",
        "ch_stigma_recoverword": "Recovery Spell",
        "ch_surperiorheal": "Healing Burst",
        "ch_swordbind": "Binding Word",
        "ch_thruststrike": "Burst",
        "ch_triplethrust": "Annihilation",
        "cl_imbuemana": "Promise of Aether",
        "el_bind": "Body Root",
        "el_dimisspolymorph": "Weaken Spirit",
        "el_drainenergy": "Absorb Vitality",
        "el_earthguardiance": "Earthen Call",
        "el_elementalboost": "Sympathetic Mind",
        "el_elementalcharge": "Healing Spirit",
        "el_elementtransfer": "Transference",
        "el_enchantarmor": "Armor Spirit",
        "el_enchantmentburst": "Ignite Aether",
        "el_enervationcurse": "Withering Gloom",
        "el_enfeeblement": "Shackle of Vulnerability",
        "el_escape": "Cloaking Word",
        "el_ethercharge": "Spirit Recovery",
        "el_fireaid": "Blessing of Fire",
        "el_hellcurse": "Infernal Blight",
        "el_hellpain": "Infernal Pain",
        "el_manareverse": "Magic Implosion",
        "el_order_elementalfield": "Spirit Wall of Protection",
        "el_order_omen": "Spirit Hypnosis",
        "el_order_protect": "Command: Bodyguard",
        "el_order_sacrifice": "Spirit Substitution",
        "el_silence": "Sigil of Silence",
        "el_slave_stormservent_dark": "Summon Cyclone Servant",
        "el_slave_stormservent_light": "Summon Cyclone Servant",
        "el_sleepingspirit": "Hand of Torpor",
        "el_soulsteal": "Soul Torrent",
        "el_stigma_order_destructimpact": "Spirit Ruinous Offensive",
        "el_stigma_order_etheremission_light": "Ancestral Spirit Flow",
        "el_stigma_order_ethereruption_light": "Spirit Burn-to-Ashes",
        "el_stigma_order_etherimpact_dark": "Ancestral Spirit Self Destruct",
        "el_stigma_order_shadoweruption_dark": "Spirit Explosion",
        "el_stigma_stormblade": "Cyclone of Wrath",
        "el_sympatheticswitch": "Enmity Swap",
        "el_terrorspirit": "Fear Shriek",
        "fi_anklegrab": "Ankle Snare",
        "fi_anklesnatcher": "Fettertwine",
        "fi_berserkstance": "Berserking",
        "fi_blademode": "Slaughter",
        "fi_burserklance": "Sure Strike",
        "fi_charginghit": "Precision Cut",
        "fi_chargingshock": "Severe Precision Cut",
        "fi_cripplingcut": "Crippling Cut",
        "fi_drainsword": "Draining Sword",
        "fi_enfeeblehit": "Severe Weakening Blow",
        "fi_heavyimpact": "Earthquake Wave",
        "fi_howling": "Howl",
        "fi_jumpattack": "Whirling Strike",
        "fi_kneecrash": "Tendon Slice",
        "fi_lockdownimpact": "Lockdown",
        "fi_magicalbarrier": "Magical Defense",
        "fi_potentialhealth": "Improved Stamina",
        "fi_ragespirit": "Dauntless Spirit",
        "fi_revengeslash": "Vengeful Strike",
        "fi_seismicdrain": "Absorbing Fury",
        "fi_sharpnesshit": "Sharp Strike",
        "fi_spinningparry": "Spin Block",
        "fi_stigma_draincut": "Draining Blow",
        "fi_stigma_forceblast_light": "Ancestral Force Blast",
        "fi_stigma_forceburst_light": "Shattering Wave",
        "fi_stigma_shockburst_dark": "Piercing Rupture",
        "fi_stigma_shockimpulse_dark": "Ancestral Piercing Wave",
        "fi_survivorstance": "Second Wind",
        "fi_technicalcounter": "Spite Strike",
        "fi_vorpalhit": "Vicious Blow",
        "fi_whirldrain": "Exhausting Wave",
        "fi_whirltornado": "Revival Wave",
        "gu_antigravitycannon": "Paralysis Cannon",
        "gu_armorbreak": "Juggernaut Cannon",
        "gu_bullseye": "Sighting",
        "gu_empowerammo": "Pressurized Chamber",
        "gu_empowermagic": "Stopping Power",
        "gu_firechainrefresh": "Autoload",
        "gu_flamecannon": "Blazing Bombardment",
        "gu_icecannon": "Frozen Blitz",
        "gu_magicalbreathing": "Nature's Favor",
        "gu_mentaliccannon": "Shellshock",
        "gu_mentalsnatcher": "Power Grab",
        "gu_onepointrapidfire": "Steady Fire",
        "gu_rapidstance": "Stable Stance",
        "gu_shockcannon": "Shock and Awe",
        "gu_silenceshot": "Quieting Gale",
        "gu_soulbreakcannon": "Missile Guide",
        "gu_sunningshot": "Dazzling Fire",
        "gu_survivalinstinct": "Survival Instinct",
        "gu_vassblaster": "Fiery Blast",
        "gu_veinsnipe": "Hemorrhage Shot",
        "kn_absolutescare": "Terrible Howl",
        "kn_brainstorm": "Divine Justice",
        "kn_breakpower": "Break Power",
        "kn_conquestmind": "Power of Restoration",
        "kn_destructshield": "Shieldburst",
        "kn_destructwish": "Empyrean Fury",
        "kn_divinepower": "Divine Fury",
        "kn_divineslash": "Punishment",
        "kn_executionalstrike": "Punishing Thrust",
        "kn_fortitudewave": "Punishing Wave",
        "kn_grandprotection": "Bodyguard",
        "kn_highprovoke": "Incite Rage",
        "kn_holywrath": "Holy Shield",
        "kn_intimidation": "Threatening Taunt",
        "kn_invinsibleprotect": "Empyrean Providence",
        "kn_invinsibleshield": "Shield of Faith",
        "kn_massiveprovoke": "Provoking Roar",
        "kn_movingstance": "Stubborn Spirit",
        "kn_powersink": "Magic Smash",
        "kn_recover": "Prayer of Resilience",
        "kn_reflectshield": "Barricade of Steel",
        "kn_revivaltouch": "Restoration Sacrifice",
        "kn_sentinel": "Prayer of Victory",
        "kn_stigma_demonpunishment_dark": "Punishment of Darkness",
        "kn_stigma_drainsword_dark": "Ancestral Righteous Punishment",
        "kn_stigma_godjudgement_light": "Ancestral Holy Punishment",
        "kn_stigma_godpunishment_light": "Punishment of Light",
        "kn_stigma_resistarmor": "Aether Armor",
        "kn_stunningsnacher": "Doom Lure",
        "kn_thunderblade": "Inquisitor's Blow",
        "kn_triplesnacher": "Illusion Chains",
        "p_equip_dual": "Advanced Dual-Wielding",
        "pr_bindingheal": "Sympathetic Heal",
        "pr_blindinglight": "Blinding Light",
        "pr_calllightning": "Call Lightning",
        "pr_coursewound": "Festering Wound",
        "pr_eternalservent_dark": "Summon Noble Energy",
        "pr_eternalservent_light": "Summon Noble Energy",
        "pr_firstaid": "Flash of Recovery",
        "pr_graceofgod": "Grace of Empyrean Lord",
        "pr_healershand": "Benevolence",
        "pr_healinggrace": "Noble Grace",
        "pr_healingservent_dark": "Summon Healing Servant",
        "pr_healingservent_light": "Summon Healing Servant",
        "pr_massdispel": "Splendor of Purification",
        "pr_massemergentheal": "Splendor of Recovery",
        "pr_memoryblur": "Shatter Memory",
        "pr_offensivemode": "Sacrificial Power",
        "pr_painlinks": "Chain of Suffering",
        "pr_powersmite": "Punishing Earth",
        "pr_purgatory": "Earth's Wrath",
        "pr_regeneraitionshine": "Splendor of Rebirth",
        "pr_restorelife": "Saving Grace",
        "pr_reversecondition": "Reverse Condition",
        "pr_revivehand": "Hand of Reincarnation",
        "pr_sageswisdom": "Sage's Wisdom",
        "pr_sprint": "Power Sprint",
        "pr_stigma_abysalcircle_dark": "Ancestral Marchutan's Light",
        "pr_stigma_abysalsanctuary_dark": "Marchutan's Splendor",
        "pr_stigma_divinecircle_light": "Ancestral Yustiel's Light",
        "pr_stigma_divinesanctuary_light": "Yustiel's Splendor",
        "pr_stigma_suggestion": "Stability",
        "pr_suffermemory": "Enfeebling Burst",
        "pr_thunderofpunishment": "Retribution Lightning",
        "pr_tranquility": "Ripple of Purification",
        "ra_backdashstab": "Retreating Slash",
        "ra_blazingtrap_dark": "Blazing Trap",
        "ra_blazingtrap_light": "Blazing Trap",
        "ra_breathofnature": "Breath of Nature",
        "ra_callcompanion_dark": "Call Gryphu",
        "ra_callcompanion_light": "Call Gryphu",
        "ra_draineye": "Keen Cleverness",
        "ra_enchantbow": "Bow of Blessing",
        "ra_explosionarrow": "Explosive Arrow",
        "ra_fairyflare_dark": "Trap of Clairvoyance",
        "ra_fairyflare_light": "Trap of Clairvoyance",
        "ra_heavenstrap_dark": "Snare Trap",
        "ra_heavenstrap_light": "Snare Trap",
        "ra_huntermind": "Hunter's Might",
        "ra_instantsprint": "Feint",
        "ra_lightningshot": "Lightning Arrow",
        "ra_marksmanmode": "Sniper Stance",
        "ra_massexplosionarrow": "Lethal Arrow",
        "ra_movingshot": "Gale Arrow",
        "ra_painarrow": "Agonizing Arrow",
        "ra_panthermove": "Speed of the Wind",
        "ra_paralyzearrow": "Sleep Arrow",
        "ra_rapidshot": "Misery Shot",
        "ra_resistmind": "Nature's Resolve",
        "ra_sealingarrow": "Dilation Arrow",
        "ra_shadowarrow": "Heart Shot",
        "ra_silentarrow": "Silence Arrow",
        "ra_snakebitetrap_dark": "Skybound Trap",
        "ra_snakebitetrap_light": "Skybound Trap",
        "ra_spoutarrow": "Arrow Deluge",
        "ra_stigma_ancientarrow_light": "Holy Arrow",
        "ra_stigma_destructarrow_dark": "Ancestral Darkwing Arrow",
        "ra_stigma_mysticarrow_dark": "Deadly Arrow",
        "ra_stigma_phoenixarrow_light": "Ancestral Brightwing Arrow",
        "ra_stigma_tigereye": "Bestial Fury",
        "ra_throwingtrap_dark": "Trap of Slowing",
        "ra_throwingtrap_light": "Trap of Slowing",
        "ra_trackermind": "Sharpen Arrows",
        "ri_bindingslam": "Convulsion Beam",
        "ri_chainfire": "Gattling Gun",
        "ri_eathiumblast": "Steel Storm",
        "ri_eathiumcompress": "Life Support Trigger",
        "ri_eathiumcurtain": "Nullification Trigger",
        "ri_eathiumreactive": "Aether Recharge",
        "ri_eathiumwall": "Kinetic Bulwark",
        "ri_flamethrow": "Particle Whip",
        "ri_forwardstrike": "Riplash",
        "ri_itheumreflector": "Leeching Steel",
        "ri_magneticfield": "Trauma Plate Trigger",
        "ri_overcharge": "Aethercharged Steel",
        "ri_poweroverdrive": "Stability Thrusters",
        "ri_powerslam": "Meteor Strike",
        "ri_rapidattack": "Rain of Knuckles",
        "ri_rapidcharge": "Recharge",
        "ri_shielddestroyer": "Drillbore",
        "ri_speedoverdrive": "Mobility Thrusters",
        "ri_tunesensor": "Aimbot Assist",
        "ri_weaponsmash": "Debilitating Blade",
        "sc_trueshotmind": "Focused Shots",
        "wa_gatecrush": "Siegebreaker",
        "wa_steadiness": "Unwavering Devotion",
        "wi_arcaneboost": "Vaizel's Wisdom",
        "wi_arcanepower": "Zikel's Wisdom",
        "wi_arcanewisdom": "Lumiel's Wisdom",
        "wi_countermagic": "Curse of Weakness",
        "wi_cursedtree": "Curse of Roots",
        "wi_cyclonestrike": "Storm Strike",
        "wi_deepsleep": "Somnolence",
        "wi_elementalseal": "Elemental Ward",
        "wi_flamestrike": "Flame Spray",
        "wi_frostpillar_dark": "Ice Sheet",
        "wi_frostpillar_light": "Ice Sheet",
        "wi_hibernation": "Absolute Zero",
        "wi_hpmpexchange": "Exchange Vitality",
        "wi_icebarrier": "Barrier of Severance",
        "wi_icyshield": "Wintry Armor",
        "wi_icyveins_dark": "Boon of Quickness",
        "wi_icyveins_light": "Boon of Strength",
        "wi_illusiondance": "Illusion",
        "wi_illusionstorm": "Illusion Storm",
        "wi_massexplosion": "Fire Burst",
        "wi_rockfall": "Summon Rock",
        "wi_sleepingstorm": "Sleeping Storm",
        "wi_soulgain": "Supplication of Focus",
        "wi_stigma_atomicenergy_dark": "Ancestral Lava Tsunami",
        "wi_stigma_atomicenergy_light": "Ancestral Magma Eruption",
        "wi_stigma_icelance": "Ice Harpoon",
        "wi_stigma_lavawave_dark": "Lava Tempest",
        "wi_stigma_volcanicflame_light": "Big Magma Eruption",
        "wi_stormshock": "Arcane Thunderbolt",
        "wi_summontornado_dark": "Summon Whirlwind",
        "wi_summontornado_light": "Summon Whirlwind",
        "wi_wakeup": "Wake Up",
        "wi_windcutter": "Wind Cut Down",
        "wi_zeropoint": "Glacial Shard"
    },
    skilldesc: {
        "as_assaultslash": "Inflicts [%e1.DashATK.MinDamage]~[%e1.DashATK.MaxDamage] damage by charging the target within a [%First_Target_Valid_Distance]m radius.",
        "as_backblow": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on a target in hide mode. This temporarily stuns the target.",
        "as_blindingburst": "Blinds nearby enemies within a 15m radius of you for [%e1.Blind.RandomTime]~[%e1.Blind.RemainTime] and reduces their [%e2.StatDown.StatName]% by [%e2.StatDown.Value].",
        "as_blindside": "Jumps behind a target's back within [%First_Target_Valid_Distance]m to inflict [%e1.MoveBehindATK.MinDamage]~[%e1.MoveBehindATK.MaxDamage] physical damage. May also stun it.",
        "as_carvesignetchain": "Inflicts [%e1.CarveSignet.MinDamage]~[%e1.CarveSignet.MaxDamage] physical damage on the target and engraves a signet pattern on the target up to [%e1.CarveSignet.SignetGrade] level. \nChain Skill Level 2\nRune Carve – Sigil Strike\nStigma acquired",
        "as_chainsignetburst": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within a [%First_Target_Valid_Distance]m radius.\nChain Skill Level 2\nAll Pain Rune - Agony Rune",
        "as_defendroar_dark": "You transform into a Slayer for [%e1.ShapeChange.RemainTime]. While you are transformed, your [%e2.StatUp.StatName], [%e2.StatUp.StatName2], and [%e2.StatUp.StatName3] increase by [%e2.StatUp.Value], [%e2.StatUp.Value2], and [%e2.StatUp.Value3], respectively, and you recover MP quickly.",
        "as_defendroar_light": "You transform into a Slayer for [%e1.ShapeChange.RemainTime]. While you are transformed, your [%e2.StatUp.StatName], [%e2.StatUp.StatName2], and [%e2.StatUp.StatName3] increase by [%e2.StatUp.Value], [%e2.StatUp.Value2], and [%e2.StatUp.Value3], respectively, and you recover MP quickly.",
        "as_explosionpoison": "Uses 5 Scolopen Poison to apply poison to your weapon. For [%e1.Provoker.RemainTime], there is a [%e1.Provoker.ConditionProb]% chance of inflicting additional [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] damage to the target with each attack.",
        "as_flashslash": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage to the target. The target's [%e2.StatDown.StatName] decreases by [%e2.StatDown.Value] for [%e2.StatDown.RemainTime].\nChain Skill Level 2\nSwift Edge - Lightning Slash",
        "as_hitmanmind": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value] and [%e2.StatUp.StatName] by [%e2.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "as_mirrorattack": "Inflicts [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] physical damage on a target within a [%First_Target_Valid_Distance]m radius that is immobilized in mid-air.",
        "as_quickmove": "Your [%e1.StatUp.StatName] increases by [%e1.StatUp.Value]% for [%e1.StatUp.RemainTime].",
        "as_runnersstance": "Removes any abnormal conditions related to movement and increases your resistance to Stuns, Knock Backs, Stumbles, Spins, and Aerial Thrusts by 500 points for 7 seconds.",
        "as_senseboost": "Increases [%e1.StatUp.StatName]% by [%e1.StatUp.Value], [%e2.StatUp.StatName]% by [%e2.StatUp.Value], and [%e2.StatUp.StatName2]% by [%e2.StatUp.Value2] for [%e1.StatUp.RemainTime].",
        "as_shadowdodge": "You move [%e1.RandomMoveLoc.Distance]m forward instantly, and all immobilization and Speed reduction debuffs are removed.",
        "as_shadowdrop": "Grabs a stunned target and inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage, causing them to stumble in the process.",
        "as_signetflare": "Erases the rune carved on a target within a [%First_Target_Valid_Distance]m radius up to the level of [%e1.SignetBurst.SignetGrade] and sets it to burst, damaging the target.\nThe amount of damage varies on the target's rune level.",
        "as_signetwave": "Deals [%e1.CarveSignet.MinDamage]~[%e1.CarveSignet.MaxDamage] physical damage on a target within [%First_Target_Valid_Distance]m, and carves runes up to level [%e1.CarveSignet.SignetGrade]. ",
        "as_silentburst": "Ignite a rune carved on a target within a [%First_Target_Valid_Distance]m radius up to level [%e1.SignetBurst.SignetGrade], causing the rune to explode inflicting damage and silencing the target for 30s. \nThe chance of silencing the target varies depending on the level of the rune carved on the target.",
        "as_stabstance": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value]% for [%e1.StatUp.RemainTime] while decreasing your [%e2.StatDown.StatName] by [%e2.StatDown.Value].",
        "as_stigma_demonicburst_dark": "Detonates up to [%e1.SignetBurst.SignetGrade] runes on a target within [%First_Target_Valid_Distance]m, inflicting damage to the target and healing you for a portion of the damage.",
        "as_stigma_moonburst_dark": "Detonates up to [%e1.SignetBurst.SignetGrade] runes on a target within [%First_Target_Valid_Distance]m dealing damage to the target and healing you for a portion of that damage.",
        "as_stigma_novaburst_light": "Detonates up to [%e1.SignetBurst.SignetGrade] runes on a target within [%First_Target_Valid_Distance]m, dealing damage, silencing the target, and reducing its Attack Speed.",
        "as_stigma_shadowwalk": "You enter advanced stealth for [%e1.Hide.RemainTime]. Your Speed decreases by [%e1.Hide.Speed]% while  in effect.\nYou may use buff magic and skills on yourself three times and still remain in stealth.\nCan't be used during battle.",
        "as_stigma_sunburst_light": "Detonates up to [%e1.SignetBurst.SignetGrade] runes on a target within [%First_Target_Valid_Distance]m, dealing damage, and also temporarily silencing the target and reducing its Attack Speed.",
        "as_stunburst": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within a [%First_Target_Valid_Distance] m radius of you, and also stuns the target.",
        "as_stunburst_2": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m. Stuns the target.",
        "as_stuningintention": "Uses 2 Scolopen Poison to apply poison to your weapon. For [%e1.Provoker.RemainTime], there is a [%e1.Provoker.ConditionProb]% chance of stunning the target with each attack.",
        "as_tigerassault": "Inflicts [%e1.CarveSignet.MinDamage]~[%e1.CarveSignet.MaxDamage] damage to the target and engraves a signet rune on the target up to the level of [%e1.CarveSignet.SignetGrade]. \nChain Skill Level 4\nBeastly Thrash - Beastly Scar",
        "as_venomslash": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage to the target, and inflicts an additional [%e1.SkillATK_Instant.AddDamage] damage and may stun the target if it is poisoned.",
        "as_venomstab": "Chance to inflict [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage and poison the target for [%e2.Poison.RemainTime]. If used on the target's back, inflicts an additional [%e1.SkillATK_Instant.AddDamage] damage.",
        "as_visiouseye": "Performs critical hit attacks up to [%e1.OneTimeBoostSkillCritical.BoostCount] times for [%e1.OneTimeBoostSkillCritical.RemainTime]. However, your [%e2.StatDown.StatName] decreases by [%e2.StatDown.Value].",
        "as_whisperofgale": "You can resist [%e1.AlwaysResist.Count] magical attacks. Lasts [%e1.AlwaysResist.RemainTime].",
        "as_windslash": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage to the target. Decreases the target's [%e2.StatDown.StatName] by [%e2.StatDown.Value] and [%e3.StatDown.StatName] by [%e3.StatDown.Value] for [%e2.StatDown.RemainTime].\nChain Skill Level 2.\nSwift Edge - Agonizing Slash",
        "ba_delayparalyze": "Paralyzes a target within a [%First_Target_Valid_Distance]m radius of you for 5 seconds after an 8 second delay.",
        "ba_focusdefence": "Increases [%e1.StatUp.StatName] by [%e1.StatUp.Value] for [%e1.StatUp.RemainTime]. You suffer less damage when attacked by another player.",
        "ba_lullaby": "Forces a target within a [%First_Target_Valid_Distance]m radius of you to fall asleep for [%e2.Sleep.RemainTime] and increases the target's [%e3.StatUp.StatName] and [%e3.StatUp.StatName2].",
        "ba_playingstyleschangea": "Boosts your [%e1.StatBoost.StatName] by [%e1.StatBoost.fixValue].",
        "ba_playingstyleschangeb": "Boosts your [%e1.StatBoost.StatName] by [%e1.StatBoost.fixValue].",
        "ba_sanctuary": "Creates a protective shield which blocks 3000 damage points for 30s while under attack. Restores 141 HP and MP every 3 seconds for 30s.",
        "ba_songofbind": "Binds a target for 5 seconds.",
        "ba_songofbless": "Removes two abnormal conditions on you and any group members within a 25 m radius of you and restores [%e2.Heal.CheckTimeHeal] HP every [%e2.Heal.CheckTime] for [%e2.Heal.RemainTime].",
        "ba_songofbrave": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value], and your [%e1.StatUp.StatName2] and [%e1.StatUp.StatName3] by [%e1.StatUp.Value2] for [%e1.StatUp.RemainTime].",
        "ba_songofearth": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within a [%First_Target_Valid_Distance] m radius of you and decreases the target's [%e2.StatDown.StatName] by [%e2.StatDown.Value] for [%e2.StatDown.RemainTime].",
        "ba_songoffirm": "Increases your [%e1.StatUp.StatName] and [%e1.StatUp.StatName3] by [%e1.StatUp.Value], and your [%e1.StatUp.StatName2] by [%e1.StatUp.Value2] for [%e1.StatUp.RemainTime].",
        "ba_songofgale": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within a [%First_Target_Valid_Distance]m radius of you.",
        "ba_songofmanareverse": "Removes up to 2 enchantments from the target.",
        "ba_songofmassheal": "Restores the HP of a target within a [%First_Target_Valid_Distance] m radius by [%e1.Heal_Instant.Heal].",
        "ba_songofmassheal_2": "Restores the HP of a target within a [%First_Target_Valid_Distance] m radius by [%e1.Heal_Instant.Heal].",
        "ba_songofmassheal_3": "Restores the HP of a target within a [%First_Target_Valid_Distance] m radius by [%e1.Heal_Instant.Heal].",
        "ba_songofpain": "Inflicts [%e1.SpellATK.Damage] damage on a target within a [%First_Target_Valid_Distance]m radius every [%e1.SpellATK.CheckTime] for [%e1.SpellATK.RemainTime]. Inflicts an additional [%e2.SpellATK.Damage] of damage [%e2.SpellATK.RemainTime] later.",
        "ba_songofregeneration": "Restores the HP of a target within a [%First_Target_Valid_Distance] m radius of you by [%e1.Heal.CheckTimeHeal] every [%e1.Heal.CheckTime] for [%e1.Heal.RemainTime].",
        "ba_songofresurrection": "Resurrects a target within [%First_Target_Valid_Distance] m of you.",
        "ba_songofserenity": "Restores the target's MP by [%e1.MpHeal_Instant.Heal] within [%First_Target_Valid_Distance] m of you.",
        "ba_songofserenity_2": "Restores the target's MP by [%e1.MpHeal_Instant.Heal] within [%First_Target_Valid_Distance] m of you.",
        "ba_songofserenity_3": "Recovers [%e1.MpHeal_Instant.Heal] MP for up to 6 allies within a 10 m radius from the target in a [%First_Target_Valid_Distance]m radius.",
        "ba_songogpeace": "Decreases the target's Enmity toward you.",
        "ch_blessprotect": "Increases [%e1.StatUp.StatName] by [%e1.StatUp.Value]%, [%e2.StatUp.StatName] by [%e2.StatUp.Value], [%e3.StatUp.StatName] by [%e3.StatUp.Value]%, and [%e1.StatUp.StatName2] by [%e1.StatUp.Value2] of a target within a [%First_Target_Valid_Distance]m radius for [%e1.StatUp.RemainTime].",
        "ch_chakra": "Restores [%e1.Heal_Instant.Heal] HP and [%e2.MPHeal_Instant.Heal] MP.",
        "ch_chant_improvedcritical": "Increases [%e1.Aura.OtherSkill.e1.StatUp.StatName] by [%e1.Aura.OtherSkill.e1.StatUp.Value], [%e1.Aura.OtherSkill.e1.StatUp.StatName2] by [%e1.Aura.OtherSkill.e1.StatUp.Value2], [%e1.Aura.OtherSkill.e2.StatUp.StatName] by [%e1.Aura.OtherSkill.e2.StatUp.Value], and [%e1.Aura.OtherSkill.e2.StatUp.StatName2] by [%e1.Aura.OtherSkill.e2.StatUp.Value2] for you and your group members within a [%e1.Aura.Range]m radius.\nActive Skill",
        "ch_chant_improvedresiststun": "Increases [%e1.Aura.OtherSkill.e1.StatUp.StatName] of you and your group members within [%e1.Aura.Range]m radius of you by [%e1.Aura.OtherSkill.e1.StatUp.Value].\nActive Skill.",
        "ch_chant_invincible": "Recovers the MP of the caster and group members within a [%e1.Aura.Range]m radius by [%e1.Aura.OtherSkill.e1.MPHeal.CheckTimeHeal], and also increases [%e1.Aura.OtherSkill.e2.StatUp.StatName], [%e1.Aura.OtherSkill.e3.StatUp.StatName], and [%e1.Aura.OtherSkill.e4.StatUp.StatName].\nActive Skill.",
        "ch_encouragerun": "Consumes your HP to increase an ally's [%e1.StatUp.StatName] within [%First_Target_Valid_Distance]m by [%e1.StatUp.Value]% for 7s.",
        "ch_harshthrust": "Gathers energy, then deals a downward blow to inflict [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage.",
        "ch_harshthrust_2": "Gathers energy, then deals a downward blow to inflict [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage.",
        "ch_harshthrust_3": "Gathers energy, then deals a downward blow to inflict [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage.",
        "ch_healingtank": "For [%e1.HealCastorOnAttacked.RemainTime], HP of the caster and group members is restored by [%e1.HealCastorOnAttacked.HealPoint] whenever the target suffers damage. But only those who stay within [%e1.HealCastorOnAttacked.EffectArea]m radius of the target can restore their HP.",
        "ch_heroicstrike": "Deals [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage to a stunned target and causes it to become [%e1.SkillATK_Instant.AddEffect].",
        "ch_imbuepower": "For [%e1.Provoker.RemainTime], there is a [%e1.Provoker.ConditionProb]% chance of inflicting additional [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] damage to the target each time you [%e1.Provoker.Condition].",
        "ch_improvedallattack": "Increases [%e1.StatUp.StatName] by [%e1.StatUp.Value], [%e2.StatUp.StatName] by [%e2.StatUp.Value], and [%e3.StatUp.StatName] by [%e3.StatUp.Value]% of your group members within a 20m radius of you for [%e1.StatUp.RemainTime].",
        "ch_improvedalldefend": "Increases [%e1.StatUp.StatName] by [%e1.StatUp.Value] and [%e2.StatUp.StatName] by [%e2.StatUp.Value] of your group members within a 20m radius of you for [%e1.StatUp.RemainTime].",
        "ch_improvedbody": "Increases the [%e1.StatUp.StatName] and [%e2.StatUp.StatName] of you and up to 6 allies within a 20m radius by [%e1.StatUp.Value] and [%e2.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "ch_improvedlifestream": "Heals all group members within 20m of you by [%e1.Heal.CheckTimeHeal] every [%e1.Heal.CheckTime] for [%e1.Heal.RemainTime].",
        "ch_mountaincrash": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage on a target within a [%First_Target_Valid_Distance]m radius, and deals periodic [%e2.SpellATK.Damage] damage every [%e2.SpellATK.CheckTime] for [%e2.SpellATK.RemainTime].",
        "ch_mpheal": "Recovers the MP of the caster or a target within a [%First_Target_Valid_Distance]m radius by [%e1.MPHeal_Instant.Heal].",
        "ch_nightwish": "For [%e1.StatUp.RemainTime], your [%e1.StatUp.StatName] increases by [%e1.StatUp.Value]%. But in the meantime, your healing skill casting time increases by 20%.",
        "ch_phoenixstep": "Removes your Stun, Knock Back, Stumble, Spin, and Aerial Thrust states and increases your [%e2.StatUp.StatName] for [%e2.StatUp.RemainTime] by [%e2.StatUp.Value].\nChain Skill Level 1",
        "ch_protectself": "Creates a protective shield for [%e1.Shield.RemainTime] that has a [%e1.Shield.ConditionProb]% chance of blocking damage whenever you are hit by [%e1.Shield.Condition], and increases your resistance to Stumble. The protective shield blocks [%e1.Shield.CoverValue]% damage from each attack.",
        "ch_shockwave": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on the target and puts it in the [%e1.SkillATK_Instant.AddEffect] state.\nStigma Skill",
        "ch_slowcrash": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage to the target, increasing the target's casting time by 50%, and decreasing the target's Attack Speed for [%e2.Slow.RemainTime].",
        "ch_soaredrock": "Inflicts [%e1.SkillATK_Instant.MinDamage] ~ [%e1.SkillATK_Instant.MaxDamage] physical damage on a stunned or stumbled target within a [%First_Target_Valid_Distance] m radius and binds it for [%e2.bind.RemainTime].",
        "ch_splashswing": "Upon successful parry, inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage to the target.",
        "ch_stigma_angelicwall_light": "Creates a shield for [%e1.Shield.RemainTime] that has a [%e1.Shield.ConditionProb]% chance of blocking damage each time you and up to 6 allies within a 20m radius receive [%e1.Shield.Condition], and also recovers [%e2.Heal.CheckTimeHeal] HP every [%e2.Heal.CheckTime] (The shield blocks [%e1.Shield.CoverValue]% of the damage you receive per attack until it blocks a total of [%e1.Shield.ShieldValue] damage).",
        "ch_stigma_angelicwish_light": "Stigma skill of an Ancient Daeva. Creates a protective shield for [%e1.Shield.RemainTime] that blocks damage with [%e1.Shield.ConditionProb]% probability each time you and allies within a 20m radius receive [%e1.Shield.Condition], and recovers HP by [%e2.Heal.CheckTimeHeal] every [%e2.Heal.CheckTime]. (The shield blocks [%e1.Shield.CoverValue]% of the damage you receive each time. It remains effective until it absorbs a total of [%e1.Shield.ShieldValue] damage.)",
        "ch_stigma_demonicwall_dark": "Creates a shield for [%e1.Shield.RemainTime] that has a [%e1.Shield.ConditionProb]% chance of blocking damage each time you and up to 6 allies within a 20m radius receive [%e1.Shield.Condition] (The shield blocks [%e1.Shield.CoverValue]% of the damage you receive per attack until it blocks a total of [%e1.Shield.ShieldValue] damage).",
        "ch_stigma_demonicwish_dark": "Stigma skill of an Ancient Daeva. Creates a protective shield for [%e1.Shield.RemainTime] that can block damage with [%e1.Shield.ConditionProb]% probability each time you and allies within a 20m radius receive [%e1.Shield.Condition]. (The shield blocks [%e1.Shield.CoverValue]% of the damage you receive each time. It remains effective until it absorbs a total of [%e1.Shield.ShieldValue] damage.)",
        "ch_stigma_recoverword": "Heals a target within [%First_Target_Valid_Distance]m of you by [%e1.Heal_Instant.Heal], and additionally heals them by [%e2.Heal.CheckTimeHeal] every [%e2.Heal.CheckTime] for [%e2.Heal.RemainTime].",
        "ch_surperiorheal": "Heals a target within [%First_Target_Valid_Distance]m of you by [%e1.Heal_Instant.Heal].",
        "ch_swordbind": "Binds and reduces the Speed of a target within [%First_Target_Valid_Distance]m for [%e1.Bind.RemainTime].",
        "ch_thruststrike": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage and stuns the target temporarily.\nChain Skill Level 2\nAnnihilation (3 Times) - Burst",
        "ch_triplethrust": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on the target.\nMulticast 3 Times\nChain Skill Level 1",
        "cl_imbuemana": "For [%e1.Provoker.RemainTime], you have a [%e1.Provoker.ConditionProb]% chance of recovering MP with each attack.",
        "el_bind": "Binds a target within [%First_Target_Valid_Distance]m for [%e1.Bind.RandomTime]~[%e1.Bind.RemainTime].",
        "el_dimisspolymorph": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m, and deals additional [%e1.SpellATK_Instant.AddDamage] damage if the target is a spirit.",
        "el_drainenergy": "Deals [%e1.SpellATKDrain_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m of you, and absorbs [%e1.SpellATKDrain_Instant.HPHeal]% of the damage as HP.",
        "el_earthguardiance": "Removes movement-related Altered States and increases resistance to abnormal movement conditions by 800 for 10s.",
        "el_elementalboost": "Increases your [%e1.StatUp.StatName], [%e1.StatUp.StatName2], and [%e1.StatUp.StatName3] by [%e1.StatUp.Value], [%e1.StatUp.Value2], [%e1.StatUp.Value3], respectively for [%e1.StatUp.RemainTime].\nStigma Skill",
        "el_elementalcharge": "Recovers the HP of a spirit within a [%First_Target_Valid_Distance]m radius by [%e1.Heal_Instant.Heal]% and removes all magical debuffs from it.",
        "el_elementtransfer": "Spends 10% of own HP to restore the MP of a targeted ally within 25m by [%e1.MPHeal_Instant.Heal].",
        "el_enchantarmor": "Increases your spirit's [%e1.StatUp.StatName] by [%e1.StatUp.Value]%, [%e1.StatUp.StatName2] by [%e1.StatUp.Value2]%, [%e1.StatUp.StatName3] by [%e1.StatUp.Value3], [%e2.StatUp.StatName] by [%e2.StatUp.Value]%, [%e2.StatUp.StatName2] by [%e2.StatUp.Value2], and [%e2.StatUp.StatName3] by [%e2.StatUp.Value3] if it is within a [%First_Target_Valid_Distance]m radius for [%e1.StatUp.RemainTime].",
        "el_enchantmentburst": "Removes up to [%e1.DispelBuffCounterATK.DispelCount] buffs from the target, inflicts [%e1.DispelBuffCounterATK.Damage] damage for the first buff removed, and inflicts a further [%e1.DispelBuffCounterATK.AddDamage] damage per each additional buff removed.\nChain Skill Level 1",
        "el_enervationcurse": "Reduces the maximum HP and maximum MP of a target within a [%First_Target_Valid_Distance]m radius by [%e1.Curse.Value] each for [%e1.Curse.RemainTime].\nIt can be removed with a Dispel Magical Debuff skill.",
        "el_enfeeblement": "Reduces the Attack Speed of target within [%First_Target_Valid_Distance]m radius for [%e1.Slow.RemainTime]. Increases targets casting time for magical skills and decreases [%e2.StatDown.StatName] by [%e2.StatDown.Value]. This effect can be removed with Dispel Magical Buff or Dispel Magical Debuff skills.",
        "el_escape": "Puts group members within 20m of you into basic stealth for [%e1.Hide.RemainTime], during which they cannot move.\nUnusable during battle.",
        "el_ethercharge": "Recovers your spirit's HP by 100%.",
        "el_fireaid": "For [%e1.Provoker.RemainTime], there is a [%e1.Provoker.ConditionProb]% chance of the caster and the group members within a 20m radius inflicting additional [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] damage on enemies with every [%e1.Provoker.Condition].",
        "el_hellcurse": "Decreases [%e1.StatDown.StatName] by [%e1.StatDown.Value], [%e2.StatDown.StatName] by [%e2.StatDown.Value], and [%e2.StatDown.StatName2] by [%e2.StatDown.Value2] for a target within a [%First_Target_Valid_Distance]m radius for [%e1.StatDown.RemainTime].",
        "el_hellpain": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within a [%First_Target_Valid_Distance]m radius, and deals periodic [%e2.SpellATK.Damage] damage every [%e2.SpellATK.CheckTime] for [%e2.SpellATK.RemainTime].",
        "el_manareverse": "Removes up to [%e1.DispelBuffCounterATK.DispelCount] buffs from the target, inflicts [%e1.DispelBuffCounterATK.Damage] damage for the first buff removed, and inflicts a further [%e1.DispelBuffCounterATK.AddDamage] damage per each additional buff removed. The target also receives [%e2.SkillLauncher.OtherSkill.e1.SpellATK.Damage] damage every [%e2.SkillLauncher.OtherSkill.e1.SpellATK.CheckTime] for [%e2.SkillLauncher.OtherSkill.e1.SpellATK.RemainTime]. It can be removed with Dispel Magical Buff or Dispel Magical Debuff skills.\nChain Skill Level 1",
        "el_order_elementalfield": "Commands the spirit to use its magical buff on up to 6 allies within a 15m radius.\n\nWater Spirit Hatchling Hatchling: Increases Magical Accuracy and Magical Resistance\nWind Spirit: Increases Accuracy and Evasion Rate\nEarth Spirit: Restores HP and cures Physical and Mental Altered States\nFire Spirit: Increases Physical Attack and reflects damage\nMagma Spirit: Restores HP and increases Physical Attack\nTempest Spirit: Increases Magical Accuracy, Magical Resistance, Accuracy and Evasion Rate.",
        "el_order_omen": "Commands the spirit to use its Altered State skills. The spirit possesses the target and puts it into sleep, reducing Attack Speed and increasing all elemental defense of the target before disappearing.",
        "el_order_protect": "Orders the spirit to protect a target within 20m.\nThe spirit casts a protective shield over the target that lasts for 20 seconds.",
        "el_order_sacrifice": "Commands the spirit to use its protection magic. The spirit receives all the damage in place of the caster.",
        "el_silence": "Silences a target within [%First_Target_Valid_Distance]m for [%e1.Silence.RandomTime]~[%e1.Silence.RemainTime].",
        "el_slave_stormservent_dark": "Summons [%e1.SummonHoming.UnitNumber] Energies of Wind to inflict wind damage on a target within a [%First_Target_Valid_Distance]m radius.",
        "el_slave_stormservent_light": "Summons [%e1.SummonHoming.UnitNumber] Energies of Wind to inflict wind damage on a target within a [%First_Target_Valid_Distance]m radius.",
        "el_sleepingspirit": "Forces a target within a [%First_Target_Valid_Distance]m radius to fall asleep for [%e1.Sleep.RemainTime] and increases its [%e2.StatUp.StatName].",
        "el_soulsteal": "Inflicts [%e1.SpellATK_Instant.FixDamage] water damage on a target within [%First_Target_Valid_Distance]m.\nMulticast 5 Times",
        "el_stigma_order_destructimpact": "Commands the spirit to attack. Each spirit has an element-specific strike skill.\n\nWater Spirit Hatchling Hatchling: Magical Water Strike\nWind Spirit: Sustainable Magical Wind Strike\nEarth Spirit: Magical Earth Strike, Reduced Movement Speed\nFire Spirit: Magical Fire Strike\nMagma Spirit: Magical Fire Strike\nTempest Spirit: Sustainable Magical Wind Strike.",
        "el_stigma_order_etheremission_light": "Commands the spirit to channel its HP into an attack spell. Each spirit has an element-specific skill that deals damage in an area of affect. It deals an additional damage if the target is an Asmodian or a Balaur.\n\nWater Spirit Hatchling Hatchling: Magical Water Strike\nWind Spirit: Magical Wind Strike\nEarth Spirit: Magical Earth Strike\nFire Spirit: Magical Fire Strike\nTempest Spirit: Magical Water Strike.",
        "el_stigma_order_ethereruption_light": "Commands the spirit to consume its HP in a magical elemental attack dealing area effect damage. It deals additional damage if the target is an Asmodian or a Balaur.\n\nWater Spirit Hatchling Hatchling: Magical Water Strike\nWind Spirit: Magical Wind Strike\nEarth Spirit: Magical Earth Strike\nFire Spirit: Magical Fire Strike\nTempest Spirit: Magical Water Strike.",
        "el_stigma_order_etherimpact_dark": "Commands the spirit to channel its HP into an attack spell. Each spirit has an element-specific skill that deals damage in an area of affect. It deals an additional damage if the target is an Elyos or a Balaur.\n\nWater Spirit Hatchling Hatchling: Magical Water Strike\nWind Spirit: Magical Wind Strike\nEarth Spirit: Magical Earth Strike\nFire Spirit: Magical Fire Strike\nMagma Spirit: Magical Earth Strike.",
        "el_stigma_order_shadoweruption_dark": "Commands the spirit to consume its HP in a magical elemental attack dealing area effect damage. It deals additional damage if the target is an Elyos or a Balaur.\n\nWater Spirit Hatchling Hatchling: Magical Water Strike\nWind Spirit: Magical Wind Strike\nEarth Spirit: Magical Earth Strike\nFire Spirit: Magical Fire Strike\nMagma Spirit: Magical Earth Strike.",
        "el_stigma_stormblade": "Deals [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m of you, and deals a further [%e2.SpellATK.Damage] damage every [%e2.SpellATK.CheckTime] for [%e2.SpellATK.RemainTime].",
        "el_sympatheticswitch": "You draw the Enmity of a target within [%First_Target_Valid_Distance]m that is currently focused on your spirit.",
        "el_terrorspirit": "Transforms enemies within a 15m radius of you into Fire Spirits for [%e1.Fear.RandomTime]~[%e1.Fear.RemainTime], and the target becomes afraid and its Speed is reduced.",
        "fi_anklegrab": "Immobilizes a target within [%First_Target_Valid_Distance]m for [%e1.Root.RemainTime] and decreases its [%e2.StatDown.StatName] by [%e2.StatDown.Value].",
        "fi_anklesnatcher": "Immobilizes a target within [%First_Target_Valid_Distance]m of you for [%e1.Root.RemainTime].",
        "fi_berserkstance": "Increases [%e1.StatUp.StatName] by [%e1.StatUp.Value]% for [%e1.StatUp.RemainTime] while decreasing [%e2.StatDown.StatName] by [%e2.StatDown.Value] and [%e3.StatDown.StatName] by [%e3.StatDown.Value]%.",
        "fi_blademode": "[%e2.StatBoost.StatName] is increased by [%e2.StatBoost.FixValue]. You deal an additional 25% damage when attacking a player.\nActive Skill",
        "fi_burserklance": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] undodgeable physical damage on the target.\nChain Skill Level 1",
        "fi_burserklance_2": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on the target.\nChain Skill Level 1.",
        "fi_burserklance_3": "Always inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on the target.\nChain Skill Level 1",
        "fi_charginghit": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage to the target.",
        "fi_charginghit_2": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on the target.",
        "fi_charginghit_3": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on the target without a miss.",
        "fi_chargingshock": "A wide swing of the weapon inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on all enemies within 7m. May also render them [%e1.SkillATK_Instant.AddEffect].\nChain Skill Level 1",
        "fi_chargingshock_2": "Swings your weapon to inflict [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on enemies within 7m.\nChain Skill Level 1",
        "fi_chargingshock_3": "Swing and inflict [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on enemies within 7m. Puts enemies in [%e1.SkillATK_Instant.AddEffect] state with a certain probability.\nChain Skill Level 1",
        "fi_cripplingcut": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on a fallen enemy.",
        "fi_drainsword": "Inflicts [%e1.SkillATKDrain_Instant.MinDamage]~[%e1.SkillATKDrain_Instant.MaxDamage] damage to the target and has a chance to absorb [%e1.SkillATKDrain_Instant.HPHeal]% of the damage as HP.\nChain Skill Level 3\nSevering Strike - Draining Sword",
        "fi_enfeeblehit": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on the target. The target's [%e2.StatDown.StatName] and [%e3.StatDown.StatName] are decreased by [%e2.StatDown.Value] and [%e3.StatDown.Value]% respectively for [%e2.StatDown.RemainTime].\nChain Skill Level 1",
        "fi_heavyimpact": "Deals [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on the enemies within a 10m radius of you and decreases their Speed for [%e2.Snare.RandomTime]~[%e2.Snare.RemainTime].",
        "fi_howling": "Lowers [%e1.StatDown.StatName] of the enemies within a 7m radius of you by [%e1.StatDown.Value] for [%e1.StatDown.RemainTime].",
        "fi_jumpattack": "Inflicts [%e1.DashATK.MinDamage]~[%e1.DashATK.MaxDamage] damage by dashing to the target within a [%First_Target_Valid_Distance]m radius.",
        "fi_kneecrash": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage to the target and immobilizes it for [%e2.Root.RemainTime].",
        "fi_lockdownimpact": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on the target. The target is bound for [%e2.Bind.RemainTime].",
        "fi_magicalbarrier": "Increases your Spell Debuff by [%e1.StatUp.Value] and decreases your Magical Resistance by [%e2.StatDown.Value] for [%e1.StatUp.RemainTime].\nStigma Skill",
        "fi_potentialhealth": "Restores your HP by [%e1.Heal_Instant.Heal]% and increases your [%e2.StatUp.StatName] by [%e2.StatUp.Value]%, [%e3.StatUp.StatName] by [%e3.StatUp.Value], and [%e4.StatUp.StatName] by [%e4.StatUp.Value] for [%e2.StatUp.RemainTime].",
        "fi_ragespirit": "For [%e1.Shield.RemainTime], a protective shield absorbs damage with a [%e1.Shield.ConditionProb]% chance whenever you are hit by [%e1.Shield.Condition]%. The protective shield remains until [%e1.Shield.CoverValue] damage is absorbed.",
        "fi_revengeslash": "Upon successful parry, inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage to the target.",
        "fi_seismicdrain": "Inflicts [%e1.SkillATKDrain_Instant.MinDamage] ~ [%e1.SkillATKDrain_Instant.MaxDamage] physical damage on enemies with 7m of you and absorbs [%e1.SkillATKDrain_Instant.HPHeal]% of the damage as HP.\nChain Skill Level 1",
        "fi_sharpnesshit": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage to the target.\nChain Skill Level 1.",
        "fi_spinningparry": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "fi_stigma_draincut": "Deals [%e1.SkillATKDrain_Instant.MinDamage]~[%e1.SkillATKDrain_Instant.MaxDamage] physical damage to a stumbled enemy and absorbs [%e1.SkillATKDrain_Instant.HPHeal]% of the damage as HP.",
        "fi_stigma_forceblast_light": "Deals [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on a target within [%First_Target_Valid_Distance]m of you and up to 5 enemies within a 10m radius of the target, and decreases their [%e2.StatDown.StatName] by [%e2.StatDown.Value] for [%e2.StatDown.RemainTime].",
        "fi_stigma_forceburst_light": "Deals [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on a target within [%First_Target_Valid_Distance]m of you and up to 18 enemies within a 10m radius of the target, and decreases their [%e2.StatDown.StatName] by [%e2.StatDown.Value] for [%e2.StatDown.RemainTime].",
        "fi_stigma_shockburst_dark": "Deals [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage to up to 18 enemies within a 10m radius, and decreases their [%e2.StatDown.StatName] by [%e2.StatDown.Value] for [%e2.StatDown.RemainTime].",
        "fi_stigma_shockimpulse_dark": "Deals [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage to up to 12 enemies within a 10m radius, and decreases their [%e2.StatDown.StatName] by [%e2.StatDown.Value] for [%e2.StatDown.RemainTime].",
        "fi_survivorstance": "Recovers HP by [%e1.Heal_Instant.Heal]% and increases [%e2.StatUp.StatName] by [%e2.StatUp.Value]% and [%e3.StatUp.StatName] by [%e3.StatUp.Value] for [%e2.StatUp.RemainTime].",
        "fi_technicalcounter": "Upon successful parry, inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage to the target and puts it in the [%e1.SkillATK_Instant.AddEffect] state.",
        "fi_vorpalhit": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage on the target.\nChain Skill Level 2\nSharp Strike - Severing Strike.",
        "fi_whirldrain": "Inflicts [%e1.SkillATKDrain_Instant.MinDamage]~[%e1.SkillATKDrain_Instant.MaxDamage] physical damage on enemies within 7m of the caster and absorbs [%e1.SkillATKDrain_Instant.HPHeal]% of the damage as HP.\nMulticast 3 Times\nChain Skill Level 1",
        "fi_whirltornado": "Inflicts [%e1.SkillATKDrain_Instant.MinDamage]~[%e1.SkillATKDrain_Instant.MaxDamage] physical damage on enemies within 7m of the caster and absorbs [%e1.SkillATKDrain_Instant.HPHeal]% of the damage as HP.\nChain Skill Level 2\nExhausting Wave (3 Times) - Revival Wave",
        "gu_antigravitycannon": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a ground target within [%First_Target_Valid_Distance]m. Put the target in a [%e1.SpellATK_Instant.AddEffect] state.",
        "gu_armorbreak": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m. The target's [%e2.StatDown.StatName] decreases by [%e2.StatDown.Value] and the recovery magic effect decreases by 50% for [%e2.StatDown.RemainTime].",
        "gu_bullseye": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "gu_empowerammo": "Has a [%e1.Provoker.ConditionProb]% chance of an additional [%e1.Provoker.OtherSkill.e1.ProcATK_Instant.Damage] damage on the target for each [%e1.Provoker.Condition]. The effect lasts for [%e1.Provoker.RemainTime], and increases attack power against PCs.",
        "gu_empowermagic": "Increases a [%e1.OneTimeBoostSkillAttack.AttackType]'s effect by [%e1.OneTimeBoostSkillAttack.BonusRate]%. Increases attack power against PCs for 5 attacks or [%e1.OneTimeBoostSkillAttack.RemainTime].",
        "gu_firechainrefresh": "Resets the cooldown time of your Gunshot, Trunk Shot, and Crosstrigger skills.",
        "gu_flamecannon": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m. Decreases the target's [%e2.StatDown.StatName] by [%e2.StatDown.Value] for [%e2.StatDown.RemainTime].",
        "gu_flamecannon_2": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m. Decreases the target's [%e2.StatDown.StatName] by [%e2.StatDown.Value] for [%e2.StatDown.RemainTime].",
        "gu_flamecannon_3": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m. Decreases the target's [%e2.StatDown.StatName] by [%e2.StatDown.Value] for [%e2.StatDown.RemainTime].",
        "gu_icecannon": "Inflicts [%e1.SpellATK_Instant.FixDamage] water damage on a target within [%First_Target_Valid_Distance]m. Immobilizes target for [%e2.Root.RemainTime].",
        "gu_magicalbreathing": "Increases [%e1.StatUp.StatName] and [%e1.StatUp.StatName2] by [%e1.StatUp.Value] and [%e1.StatUp.Value2], respectively, for [%e1.StatUp.RemainTime].",
        "gu_mentaliccannon": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m. Decreases the target's MP by [%e2.MPAttack_Instant.Damage]%.",
        "gu_mentaliccannon_2": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m. Decreases the target's MP by [%e2.MPAttack_Instant.Damage]%.",
        "gu_mentaliccannon_3": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m. Decreases the target's MP by [%e2.MPAttack_Instant.Damage]%.",
        "gu_mentalsnatcher": "Inflicts [%e1.SpellATKDrain_Instant.FixDamage] water damage on a target within [%First_Target_Valid_Distance]m. Takes [%e1.SpellATKDrain_Instant.HPHeal]% of the inflicted damage as HP and [%e1.SpellATKDrain_Instant.MPHeal]% of the inflicted damage as MP.",
        "gu_onepointrapidfire": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within [%First_Target_Valid_Distance]m.\nMulticast 5 Times",
        "gu_rapidstance": "Boosts [%e1.StatBoost.StatName] by [%e1.StatBoost.RateValue]%.\nActive Skill.",
        "gu_shockcannon": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m. Stuns the target for [%e2.Stun.RemainTime].",
        "gu_shockcannon_2": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m and on up to 2 enemies within 2m of the target. The wind's force knocks enemies backwards.",
        "gu_shockcannon_3": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m and on 3 others within 4m of the target. The wind's force knocks them backwards for 4 seconds.",
        "gu_silenceshot": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m. Silences the target for [%e2.Silence.RandomTime]~[%e2.Silence.RemainTime].",
        "gu_soulbreakcannon": "Inflicts [%e1.SpellATK_Instant.FixDamage] water damage on a target within [%First_Target_Valid_Distance]m.",
        "gu_soulbreakcannon_2": "Inflicts [%e1.SpellATK_Instant.FixDamage] water damage on a target within [%First_Target_Valid_Distance]m.",
        "gu_soulbreakcannon_3": "Inflicts [%e1.SpellATK_Instant.FixDamage] water damage on a target within [%First_Target_Valid_Distance]m.",
        "gu_sunningshot": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m. Stuns the target for [%e2.Stun.RemainTime].",
        "gu_survivalinstinct": "Removes 2 physical effects on you. Increases your [%e2.StatUp.StatName] by [%e2.StatUp.Value]% for [%e2.StatUp.RemainTime].",
        "gu_vassblaster": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m radius of you and on up to 3 enemies within 10m of the target.",
        "gu_vassblaster_2": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m and on up to 4 enemies within 10m of the target.",
        "gu_vassblaster_3": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m of you and on up to 5 enemies within 10m of the target.",
        "gu_veinsnipe": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within [%First_Target_Valid_Distance]m. Target bleeds for [%e2.Bleed.RemainTime].",
        "kn_absolutescare": "Taunts up to 4 enemies within a 10m radius of you, increasing their Enmity towards you, reducing their Speed, and fearing them for [%e2.Fear.RemainTime].",
        "kn_brainstorm": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within a [%First_Target_Valid_Distance]m radius and stuns the target for [%e2.Stun.RemainTime].",
        "kn_breakpower": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on a stumbled target, and decreases its [%e2.StatDown.StatName] by [%e2.StatDown.Value] for [%e2.StatDown.RemainTime]. While the skill is in effect, your [%e0.KN_BreakPower_G1_Buff.e1.StatUp.StatName] increases by [%e0.KN_BreakPower_G1_Buff.e1.StatUp.Value].",
        "kn_conquestmind": "Recovers your HP by [%e1.Heal.CheckTimeHeal] every [%e1.Heal.CheckTime] for [%e1.Heal.RemainTime].",
        "kn_destructshield": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on the target with no miss chance, and stumbles the enemy.\nRequires a shield.",
        "kn_destructwish": "Increases [%e1.StatUp.StatName] by [%e1.StatUp.Value]%, [%e2.StatUp.StatName] by [%e2.StatUp.Value] and [%e3.StatUp.StatName] by [%e3.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "kn_divinepower": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value]% for [%e1.StatUp.RemainTime].",
        "kn_divineslash": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] random physical damage on the target by wielding a Greatsword.",
        "kn_executionalstrike": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on the target.",
        "kn_fortitudewave": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage on up to 6 enemies within a 7m radius, and immobilizes them for [%e2.Root.RemainTime].",
        "kn_grandprotection": "For [%e1.Protect.RemainTime], you suffer [%e1.Protect.Value]% damage instead of an ally within [%e1.Protect.Range]m radius whenever ally receives [%e1.Protect.Condition].",
        "kn_highprovoke": "Taunts a target within [%First_Target_Valid_Distance]m, increase its Enmity toward you for a short time.",
        "kn_holywrath": "For [%e1.Reflector.RemainTime], you reflect [%e1.Reflector.FixedDamage] damage back to enemies within [%e1.Reflector.MaxRange]m radius when they successfully land an [%e1.Reflector.Condition] on you.",
        "kn_intimidation": "Taunts a target within a [%First_Target_Valid_Distance]m radius, increasing its Enmity towards you, and decreasing its Attack Speed.",
        "kn_invinsibleprotect": "Creates a protective shield for [%e1.Shield.RemainTime] that has a [%e1.Shield.ConditionProb]% chance of blocking damage each time the caster and up to 6 allies within a 30m radius receive [%e1.Shield.Condition]. In addition, increases [%e2.StatUp.StatName] by [%e2.StatUp.Value] (The protective shield blocks [%e1.Shield.CoverValue]% of the damage received per attack).",
        "kn_invinsibleshield": "Blocks [%e1.AlwaysBlock.Count] attacks for [%e1.AlwaysBlock.RemainTime] with shield defense.\nA shield required",
        "kn_massiveprovoke": "Taunts up to 5 enemies within a 10m radius of you to increase their Enmity.",
        "kn_movingstance": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value], [%e1.StatUp.StatName2] by [%e1.StatUp.Value2]%, [%e1.StatUp.StatName3] by [%e1.StatUp.Value3], [%e2.StatUp.StatName] by [%e2.StatUp.Value], [%e2.StatUp.StatName2] by [%e2.StatUp.Value2], and [%e2.StatUp.StatName3] by [%e2.StatUp.Value3].\nThis skill is cancelled if another skill is used. You cannot jump while using this skill.\nShield required.\nStigma Skill",
        "kn_powersink": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within a [%First_Target_Valid_Distance]m radius.\nChain Skill Level 3\nRobust Blow - Magic Smash.",
        "kn_recover": "Restores HP by [%e1.Heal_Instant.Heal].",
        "kn_reflectshield": "Increases [%e2.StatBoost.StatName] by [%e2.StatBoost.FixValue], [%e3.StatBoost.StatName] by [%e3.StatBoost.RateValue]%, [%e4.StatBoost.StatName] by [%e4.StatBoost.FixValue], and reflects [%e1.Reflector.FixedDamage] damage to the enemy that [%e1.Reflector.Condition]s you within a [%e1.Reflector.MaxRange]m radius.\nThis skill is disabled if another skill is used. You cannot jump while the skill is in effect.\nA shield required\nActive Skill.",
        "kn_revivaltouch": "Transfers your HP to a target within [%First_Target_Valid_Distance]m so that they recover [%e1.Heal_Instant.Heal].",
        "kn_sentinel": "Increases the [%e1.StatUp.StatName] of you and up to 6 allies within a 30m radius by [%e1.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "kn_stigma_demonpunishment_dark": "Deals [%e1.SkillATKDrain_Instant.MinDamage]~[%e1.SkillATKDrain_Instant.MaxDamage] physical damage to the target and absorbs [%e1.SkillATKDrain_Instant.HPHeal]% of the damage as HP.",
        "kn_stigma_drainsword_dark": "Deals [%e1.SkillATKDrain_Instant.MinDamage]~[%e1.SkillATKDrain_Instant.MaxDamage] physical damage to the target and absorbs [%e1.SkillATKDrain_Instant.HPHeal]% of the damage as HP.",
        "kn_stigma_godjudgement_light": "Deals [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage to the target and stuns it for [%e2.Stun.RemainTime].",
        "kn_stigma_godpunishment_light": "Deals [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage to the target and stuns it for [%e2.Stun.RemainTime].",
        "kn_stigma_resistarmor": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "kn_stunningsnacher": "Grabs an enemy within [%First_Target_Valid_Distance]m of you, pulling it to you, increasing its Enmity towards you, and decreasing its Speed for [%e2.Snare.RemainTime].",
        "kn_thunderblade": "Inflicts [%e1.SkillATK_Instant.MinDamage] ~ [%e1.SkillATK_Instant.MaxDamage] physical damage on a target within a [%First_Target_Valid_Distance]m radius of you.",
        "kn_triplesnacher": "Pulls up to 3 enemies within a [%First_Target_Valid_Distance]m radius before you, increases Enmity, and decreases their Speed for [%e2.Snare.RemainTime].",
        "p_equip_dual": "Allows you to use dual weapons skillfully.",
        "pr_bindingheal": "Can be used on an ally within [%First_Target_Valid_Distance]m to restore [%e1.Heal_Instant.Heal] HP.",
        "pr_blindinglight": "Blinds the target for [%e1.Blind.RemainTime].",
        "pr_calllightning": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within a [%First_Target_Valid_Distance]m radius.",
        "pr_coursewound": "Inflicts [%e1.SpellATK_Instant.FixDamage] water damage on a target within [%First_Target_Valid_Distance]m, and reduces the effect of recovery magic it receives by 50% for [%e2.DeboostHealAmount.RemainTime].",
        "pr_eternalservent_dark": "Summons a holy spirit near you. This spirit does not move from the summoned spot, and inflicts [%e0.EternalServent_G1.e1.SpellATK_Instant.FixDamage] long-range fire damage to a selected target within a 30m radius. This spirit vanishes after a while and consumes its HP with each attack.",
        "pr_eternalservent_light": "Summons a holy spirit near you. This spirit does not move from the summoned spot, and inflicts [%e0.EternalServent_G1.e1.SpellATK_Instant.FixDamage] long-range fire damage to a selected target within a 30m radius. This spirit vanishes after a while and consumes its HP with each attack.",
        "pr_firstaid": "Heals a target within [%First_Target_Valid_Distance]m of you by [%e1.Heal_Instant.Heal].",
        "pr_graceofgod": "For [%e1.BoostSkillCost.RemainTime], your MP level is preserved.",
        "pr_healershand": "[%e1.StatUp.StatName] increases by [%e1.StatUp.Value], but 10% more MP is consumed while the skill is in use.\nActive Skill",
        "pr_healinggrace": "Increases the effect of healing magic on group members within 25 m of the caster by 50% for [%e1.DeboostHealAmount.RemainTime].",
        "pr_healingservent_dark": "Summons a Healing Spirit near you. This spirit does not move from the summoned spot, and restores the HP of you and up to 6 of your alliance members within a 30m radius by [%e0.PR_Dark_Totem_HealingServent_G1.e1.Heal_Instant.Heal]. The spirit disappears after a specified time.",
        "pr_healingservent_light": "Summons a Healing Spirit near you. This spirit does not move from the summoned spot, and restores the HP of you and up to 6 of your alliance members within a 30m radius by [%e0.PR_Light_Totem_HealingServent_G1.e1.Heal_Instant.Heal]. The spirit disappears after a specified time.",
        "pr_massdispel": "Removes all debuffs from you and group members within a 25m radius.",
        "pr_massemergentheal": "Restores the HP of you and your group members within a 25m radius by [%e1.Heal_Instant.Heal].",
        "pr_memoryblur": "Decreases the Enmity of a target within a [%First_Target_Valid_Distance]m radius.",
        "pr_offensivemode": "Increases your [%e1.StatBoost.StatName] and [%e2.StatBoost.StatName] by [%e1.StatBoost.FixValue] and [%e2.StatBoost.FixValue] but reduces [%e3.StatDown.StatName] by 150.\nActive Skill",
        "pr_painlinks": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within a [%First_Target_Valid_Distance]m radius, and deals additional [%e2.SpellATK.Damage] damage every [%e2.SpellATK.CheckTime] for [%e2.SpellATK.RemainTime]. In addition, reduces the target's [%e4.StatDown.StatName] by [%e4.StatDown.Value]. If the target dies while the skill is in effect, it is resurrected at its registered Kisk or Obelisk.",
        "pr_powersmite": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within a [%First_Target_Valid_Distance]m radius.\nChain Skill Level 1",
        "pr_purgatory": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within a [%First_Target_Valid_Distance]m radius, and deals periodic [%e2.SpellATK.Damage] damage every [%e2.SpellATK.CheckTime] for [%e2.SpellATK.RemainTime].",
        "pr_regeneraitionshine": "Instantly recovers the HP of a target within a [%First_Target_Valid_Distance]m radius by [%e1.Heal_Instant.Heal], and recovers its HP by [%e2.Heal.CheckTimeHeal] every [%e2.Heal.CheckTime] for [%e2.Heal.RemainTime]. [%e3.StatUp.StatName] also increases by [%e3.StatUp.Value].",
        "pr_restorelife": "Recovers the target's HP by [%e1.CaseHeal.Heal] if the target's HP falls below 50% within one minute of casting.",
        "pr_reversecondition": "Exchanges your current HP with your MP.",
        "pr_revivehand": "Grants a blessing to a group member within a [%First_Target_Valid_Distance]m radius that lasts for [%e1.Rebirth.RemainTime]. If the group member dies while the blessing is in effect, they are resurrected with their HP and MP at [%e1.Rebirth.CurrentHPMP]%.",
        "pr_sageswisdom": "Reduces the casting time of all your magic skills by [%e1.BoostSkillCastingTime.CastingBonus]% for [%e1.BoostSkillCastingTime.RemainTime].",
        "pr_sprint": "Increases your Speed by 30% for up to 10s.",
        "pr_stigma_abysalcircle_dark": "Stigma skill of an Ancient Daeva. Recovers the HP of a target within a [%First_Target_Valid_Distance]m radius of you and that of up to 6 allies within a 25m radius of the target by [%e1.Heal_Instant.Heal], and forms a protective shield for [%e2.Shield.RemainTime] that can block [%e2.Shield.CoverValue] damage each time, up to [%e2.Shield.ShieldValue] damage, whenever you receive [%e2.Shield.Condition].",
        "pr_stigma_abysalsanctuary_dark": "Recovers the HP of a target within a [%First_Target_Valid_Distance]m radius of you and up to 6 allies within a 25m radius of the target by [%e1.Heal_Instant.Heal], and forms a shield for [%e2.Shield.RemainTime] that can block [%e2.Shield.CoverValue] damage each time, up to [%e2.Shield.ShieldValue] damage, whenever you receive [%e2.Shield.Condition].",
        "pr_stigma_divinecircle_light": "Stigma skill of an Ancient Daeva. Instantly recovers HP of target within a [%First_Target_Valid_Distance]m radius of you and that of up to 6 allies within a 25m radius of the target by [%e1.Heal_Instant.Heal], and additionally recovers their HP by [%e2.Heal.CheckTimeHeal] every [%e2.Heal.CheckTime] for [%e2.Heal.RemainTime].",
        "pr_stigma_divinesanctuary_light": "Instantly recovers the HP of a target within a [%First_Target_Valid_Distance]m radius of you and up to 6 allies within a 25m radius of the target by [%e1.Heal_Instant.Heal], and additionally recovers their HP by [%e2.Heal.CheckTimeHeal] every [%e2.Heal.CheckTime] for [%e2.Heal.RemainTime].",
        "pr_stigma_suggestion": "Calms a target within [%First_Target_Valid_Distance]m of you and up to 6 enemies within 20m of the target, reducing their Enmity towards you.",
        "pr_suffermemory": "Instantly inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within a [%First_Target_Valid_Distance]m radius, and inflicts periodic [%e2.SpellATK.Damage] earth damage to it every [%e2.SpellATK.CheckTime] for [%e2.SpellATK.RemainTime], while reducing its [%e3.StatDown.StatName] by [%e3.StatDown.Value].",
        "pr_thunderofpunishment": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within a [%First_Target_Valid_Distance]m radius of you.",
        "pr_tranquility": "Removes up to 3 altered states cast on you and up to 6 allies within a 20m radius of you, and also recovers HP by [%e2.Heal.CheckTimeHeal].",
        "ra_backdashstab": "Inflicts [%e1.BackDashATK.MinDamage]~[%e1.BackDashATK.MaxDamage] physical damage on the target, and you are pushed back 25m. The target is sometimes stunned for [%e2.Stun.RemainTime].",
        "ra_blazingtrap_dark": "Uses 20 Tripeed Seeds to set a trap. The trap lasts for [%e1.SummonTrap.SummonTime] and when an enemy approaches, it explodes, inflicting damage on one enemy who wanders within 5m of it.",
        "ra_blazingtrap_light": "Uses 20 Tripeed Seeds to set a trap. The trap lasts for [%e1.SummonTrap.SummonTime] and when an enemy approaches, it explodes, inflicting damage on one enemy who wanders within 5m of it.",
        "ra_breathofnature": "Increases your [%e1.StatUp.StatName] and [%e1.StatUp.StatName2] by [%e1.StatUp.Value] and [%e1.StatUp.Value2] respectively for [%e1.StatUp.RemainTime].",
        "ra_callcompanion_dark": "Summons [%e1.SummonHoming.UnitNumber] Gryphu, which inflicts damage on enemies within a [%First_Target_Valid_Distance]m radius. Each time the Gryphu attacks a target, the target is slowed.",
        "ra_callcompanion_light": "Summons [%e1.SummonHoming.UnitNumber] Gryphu, which inflicts damage on enemies within a [%First_Target_Valid_Distance]m radius. Each time the Gryphu attacks a target, the target is slowed.",
        "ra_draineye": "For [%e1.Provoker.RemainTime], there is a [%e1.Provoker.ConditionProb]% chance of recovering your MP with each attack.",
        "ra_enchantbow": "Increases [%e1.WeaponStatUp.StatName] of [%e1.WeaponStatUp.WeaponCategory] by [%e1.WeaponStatUp.Value]% for [%e1.WeaponStatUp.RemainTime].",
        "ra_explosionarrow": "Deals [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage on a target within a [%First_Target_Valid_Distance]m radius.",
        "ra_fairyflare_dark": "Sets up a ranged trap in a spot within a [%First_Target_Valid_Distance]m radius. The trap remains effective for [%e1.SummonTrap.SummonTime]. When an enemy approaches within a 10m radius, it explodes to break the enemy's hiding status.",
        "ra_fairyflare_light": "Sets up a ranged trap in a spot within a [%First_Target_Valid_Distance]m radius. The trap remains effective for [%e1.SummonTrap.SummonTime]. When an enemy approaches within a 10m radius, it explodes to break the enemy's hiding status.",
        "ra_heavenstrap_dark": "Uses 3 Tripeed seeds to set up a single trap around you. The trap remains effective for [%e1.SummonTrap.SummonTime]. When an enemy approaches within a 5m radius, it explodes to immobilize the enemy in mid-air.",
        "ra_heavenstrap_light": "Uses 3 Tripeed seeds to set up a single trap around you. The trap remains effective for [%e1.SummonTrap.SummonTime]. When an enemy approaches within a 5m radius, it explodes to immobilize the enemy in mid-air.",
        "ra_huntermind": "Performs critical hit attacks up to [%e1.OneTimeBoostSkillCritical.BoostCount] times for [%e1.OneTimeBoostSkillCritical.RemainTime]. In addition, the [%e2.WeaponStatUp.StatName] of your [%e2.WeaponStatUp.WeaponCategory] is reduced by 5m.",
        "ra_instantsprint": "Removes any Altered State related to movement and teleports you forward 10m.",
        "ra_lightningshot": "Fires an arrow that briefly stuns and inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage on a target within a [%First_Target_Valid_Distance]m radius.",
        "ra_marksmanmode": "[%e1.WeaponStatBoost.StatName] of [%e1.WeaponStatBoost.WeaponCategory] increases by [%e1.WeaponStatBoost.RateValue]%. You move at a very low speed while the skill is in effect.\nActive Skill\nStigma Skill",
        "ra_massexplosionarrow": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage on a target within a [%First_Target_Valid_Distance]m radius.",
        "ra_movingshot": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage on a target within a [%First_Target_Valid_Distance]m radius.",
        "ra_painarrow": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage on a target within a [%First_Target_Valid_Distance]m radius and poisons it for [%e2.Poison.RemainTime].",
        "ra_panthermove": "Increases [%e1.StatUp.StatName] by [%e1.StatUp.Value]%, [%e2.StatUp.StatName] by [%e2.StatUp.Value], and the [%e3.WeaponStatUp.StatName] of [%e3.WeaponStatUp.WeaponCategory] by [%e3.WeaponStatUp.Value]% for [%e1.StatUp.RemainTime].",
        "ra_paralyzearrow": "Forces a target within [%First_Target_Valid_Distance]m to fall asleep for [%e1.Sleep.RemainTime]. However, the target's [%e2.StatUp.StatName] increases by [%e2.StatUp.Value].",
        "ra_rapidshot": "Inflicts [%e1.SkillATK_Instant.MinDamage]-[%e1.SkillATK_Instant.MaxDamage] physical damage on a target that is stunned, knocked back, stumbled, spun, and immobilized in mid-air within a [%First_Target_Valid_Distance]m radius.",
        "ra_resistmind": "Removes 1 physical debuff on you and enables you to resist [%e2.AlwaysResist.Count] magical attacks within [%e2.AlwaysResist.RemainTime].",
        "ra_sealingarrow": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on a target within [%First_Target_Valid_Distance]m. Lengthens target's magic casting time by 100% for [%e2.BoostSkillCastingTime.RandomTime]~[%e2.BoostSkillCastingTime.RemainTime]. Reduces target's Attack Speed.",
        "ra_shadowarrow": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] damage on a target within a [%First_Target_Valid_Distance]m radius with a higher chance of inflicting a critical hit.",
        "ra_silentarrow": "Fires an arrow at a target within [%First_Target_Valid_Distance]m to inflict [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage, and silences the target for [%e2.Silence.RandomTime]~[%e2.Silence.RemainTime].",
        "ra_snakebitetrap_dark": "Sets up a ranged trap around you. The trap remains active for [%e1.SummonTrap.SummonTime] and inflicts damage on up to 4 enemies once an enemy gets within 10m. Those struck by the trap are also immobilized in mid-air.",
        "ra_snakebitetrap_light": "Sets up a ranged trap around you. The trap remains active for [%e1.SummonTrap.SummonTime] and inflicts damage on up to 4 enemies once an enemy gets within 10m. Those struck by the trap are also immobilized in mid-air.",
        "ra_spoutarrow": "Inflicts [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage on a target within a [%First_Target_Valid_Distance]m radius of you and up to 3 other enemies within a 5m radius of the target.",
        "ra_stigma_ancientarrow_light": "Fires an arrow at a target within [%First_Target_Valid_Distance]m to inflict [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage. This attack has low accuracy.",
        "ra_stigma_destructarrow_dark": "Fires an arrow at a target within [%First_Target_Valid_Distance]m to deal [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage. This attack has low accuracy.",
        "ra_stigma_mysticarrow_dark": "Fires an arrow at a target within [%First_Target_Valid_Distance]m to inflict [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage. This attack has low accuracy.",
        "ra_stigma_phoenixarrow_light": "Fires an arrow at a target within [%First_Target_Valid_Distance]m to deal [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage. This attack has low accuracy.",
        "ra_stigma_tigereye": "For [%e1.WeaponStatUp.RemainTime], the [%e1.WeaponStatUp.StatName] of [%e1.WeaponStatUp.WeaponCategory]s decreases by 10m while [%e2.WeaponStatUp.StatName] increases by [%e2.WeaponStatUp.Value]% and [%e3.WeaponStatUp.StatName] increases by [%e3.WeaponStatUp.Value]%.",
        "ra_throwingtrap_dark": "Uses 3 Tripeed seeds to set a trap. The trap lasts for [%e1.SummonTrap.SummonTime], and when an enemy approaches within 5m radius, it explodes, immobilizing the enemy and reducing its Evasion.",
        "ra_throwingtrap_light": "Uses 3 Tripeed seeds to set a trap. The trap lasts for [%e1.SummonTrap.SummonTime], and when an enemy approaches within 5m radius, it explodes, immobilizing the enemy and reducing its Evasion.",
        "ra_trackermind": "[%e1.WeaponStatUp.StatName] of [%e1.WeaponStatUp.WeaponCategory] increases by [%e1.WeaponStatUp.Value]%, but 10% more MP is consumed while the skill is in use.\nActive Skill.",
        "ri_bindingslam": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m and binds them for [%e2.Root.RemainTime].",
        "ri_chainfire": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m.\nChain Skill Level 2 \nCinder Cannon - Gattling Gun",
        "ri_eathiumblast": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m.",
        "ri_eathiumblast_2": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m.",
        "ri_eathiumblast_3": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m and up to 6 enemies within a 5m radius of the target. ",
        "ri_eathiumcompress": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value], [%e1.StatUp.StatName2] by [%e1.StatUp.Value2], and [%e1.StatUp.StatName3] by [%e1.StatUp.Value3] for [%e1.StatUp.RemainTime].",
        "ri_eathiumcurtain": "Resists the next magical attack or parries the next physical attack that occurs within [%e1.AlwaysResist.RemainTime].",
        "ri_eathiumreactive": "Restores [%e1.MpHeal_Instant.Heal] HP.",
        "ri_eathiumreactive_2": "Recovers [%e1.MpHeal_Instant.Heal] MP.",
        "ri_eathiumreactive_3": "Recovers [%e1.MpHeal_Instant.Heal] MP.",
        "ri_eathiumwall": "Forms a protective shield that has a [%e1.MPShield.ConditionProb]% chance to block up to [%e1.MPShield.CoverValue]% of damage each time you receive [%e1.MPShield.Condition] for up to 30 seconds. The shield remains until it absorbs [%e1.MPShield.ShieldValue] damage, and consumes MP up to [%e1.MPShield.LoseMP]% of the damage blocked.\nDuring that time, your stun resistance is increased by [%e2.StatUp.Value], and [%e2.StatUp.StatName2] by [%e2.StatUp.Value2], but your sleep resistance is decreased by [%e3.StatDown.Value].\nActive Skill",
        "ri_flamethrow": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on up to 3 enemies within a 15m fan-shaped radius in front of you.",
        "ri_flamethrow_2": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on up to 4 enemies within a 15m fan-shaped radius in front of you and has a chance to stun the target.",
        "ri_flamethrow_3": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on up to 6 enemies within a 15m fan-shaped radius in front of you and has a chance to stun the target.",
        "ri_forwardstrike": "Inflicts [%e1.SpellATK_Instant.FixDamage] water damage on enemies within a 15m fan-shaped radius in front of you.\nChain Skill Level 2\nChilling Wave - Riplash",
        "ri_itheumreflector": "Decreases the target's MP by [%e1.Provoker.OtherSkill.e1.MPAttack_Instant.Damage] for [%e1.Provoker.RemainTime] each time you are under attack.",
        "ri_magneticfield": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value] and increases resistance to Stun, Bind, and Fear by [%e2.StatUp.Value] for [%e1.StatUp.RemainTime]. Reduced damage received in PvP.",
        "ri_overcharge": "Increases your [%e1.StatUp.StatName]  by [%e1.StatUp.Value]% and [%e1.StatUp.StatName2] by [%e1.StatUp.Value2] for [%e1.StatUp.RemainTime]. Additional damage inflicted in PvP.",
        "ri_poweroverdrive": "Removes any Attack Speed debuff inflicted on you. For up to 30 seconds, your stun resistance increases by [%e1.StatUp.Value], [%e1.StatUp.StatName2] increases by [%e1.StatUp.Value2], and resistance to movement debuffs increases by [%e2.StatUp.Value].\nActive Skill",
        "ri_powerslam": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m.",
        "ri_rapidattack": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within [%First_Target_Valid_Distance]m.\nRepeat Activation 3 times.\nChain Skill Level 2\nSundering Blade - Rain of Knuckles",
        "ri_rapidcharge": "Recovers [%e1.MPHeal_Instant.Heal] MP.",
        "ri_shielddestroyer": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within [%First_Target_Valid_Distance]m stuns the target. Removes target's protective buffs.",
        "ri_speedoverdrive": "Increases your Speed or Flight Speed by [%e1.StatUp.Value]%, and your [%e3.StatUp.StatName] increases by [%e3.Statup.Value], but your[%e2.StatDown.StatName] decreases by [%e2.StatDown.Value], and your [%e2.StatDown.StatName3] decreases by [%e2.StatDown.Value3] for up to 10 seconds.\nActive Skill",
        "ri_tunesensor": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "ri_weaponsmash": "Instantly inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m and decreases their [%e2.StatDown.StatName] by [%e2.StatDown.Value], and [%e2.StatDown.StatName2] by [%e2.StatDown.Value2], for [%e2.StatDown.RemainTime].",
        "sc_trueshotmind": "Boosts your [%e1.OneTimeBoostSkillAttack.AttackType] by [%e1.OneTimeBoostSkillAttack.BonusRate]% for your next [%e1.OneTimeBoostSkillAttack.AttackCount] attacks within [%e1.OneTimeBoostSkillAttack.RemainTime]. Decreases your [%e2.StatDown.StatName] by [%e2.StatDown.Value]%.",
        "wa_gatecrush": "Deals [%e1.SkillATK_Instant.MinDamage]~[%e1.SkillATK_Instant.MaxDamage] physical damage to the target. Deals an extra [%e1.SkillATK_Instant.AddDamage] physical damage to castle gates.",
        "wa_steadiness": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "wi_arcaneboost": "Spell casting time decreased by [%e1.BoostSkillCastingTime.CastingBonus]% for [%e1.BoostSkillCastingTime.RemainTime].",
        "wi_arcanepower": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "wi_arcanewisdom": "For [%e1.BoostSkillCost.RemainTime], you can use skills with only [%e1.BoostSkillCost.BonusRate]% of the required MP.",
        "wi_countermagic": "Curses a target within [%First_Target_Valid_Distance]m. For [%e1.MagicCounterATK.RemainTime], each time they use magical skills, they take magic damage equal to [%e1.MagicCounterATK.Damage]% of their Max HP. This damage will not exceed [%e1.MagicCounterATK.MaxDamage].",
        "wi_cursedtree": "Transforms the target into a tree for [%e1.Deform.RemainTime]. The transformed target cannot move or act, and its [%e3.StatUp.StatName] increases. Once the target is attacked, the effect disappears immediately.",
        "wi_cyclonestrike": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within [%First_Target_Valid_Distance]m.",
        "wi_deepsleep": "Forces a target within [%First_Target_Valid_Distance]m to sleep for [%e2.Sleep.RemainTime]. Increases the target's [%e3.StatUp.StatName].",
        "wi_deepsleep_2": "Forces a target within [%First_Target_Valid_Distance]m to sleep for [%e2.Sleep.RemainTime]. Increases the target's [%e3.StatUp.StatName].",
        "wi_deepsleep_3": "Forces a target within [%First_Target_Valid_Distance]m to sleep for [%e2.Sleep.RemainTime]. Increases the target's [%e3.StatUp.StatName].",
        "wi_elementalseal": "Increases [%e1.StatUp.StatName] by [%e1.StatUp.Value] and [%e2.StatUp.StatName] by [%e2.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "wi_flamestrike": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within a [%First_Target_Valid_Distance]m radius.",
        "wi_frostpillar_dark": "Inflicts water damage on up to 6 enemies within a selected area and reduces their Speed for 20 seconds.",
        "wi_frostpillar_light": "Inflicts water damage on up to 6 enemies within a selected area and reduces their Speed for 20 seconds.",
        "wi_hibernation": "Freezes and stuns a targets within [%First_Target_Valid_Distance]m, preventing them from being attacked for [%e1.stun.RandomTime]~[%e1.stun.RemainTime].",
        "wi_hpmpexchange": "Exchanges your current HP with your MP.",
        "wi_icebarrier": "Creates a shield that blocks [%e1.Shield.CoverValue] damage for [%e1.Shield.RemainTime] each time the caster receives [%e1.Shield.Condition]. The caster is stunned.",
        "wi_icyshield": "If an enemy within a [%e1.Reflector.MaxRange]m radius [%e1.Reflector.Condition]s you, you reflect [%e1.Reflector.FixedDamage] damage to the enemy for [%e1.Reflector.RemainTime] and decrease its movement and Attack Speed for [%e2.Provoker.OtherSkill.e1.Snare.RemainTime].",
        "wi_icyveins_dark": "Reduces the casting time of all your magic skills by [%e1.BoostSkillCastingTime.CastingBonus]% for [%e1.BoostSkillCastingTime.RemainTime].",
        "wi_icyveins_light": "Increases your [%e1.StatUp.StatName] by [%e1.StatUp.Value] and [%e1.StatUp.StatName2] by [%e1.StatUp.Value2] for [%e1.StatUp.RemainTime].",
        "wi_illusiondance": "Removes one abnormal physical condition, and allows the caster to evade [%e2.AlwaysDodge.Count] physical attacks for [%e2.AlwaysDodge.RemainTime].",
        "wi_illusionstorm": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on up to 6 targets within a 10m radius. Targets are stunned for [%e2.Stun.RemainTime].",
        "wi_massexplosion": "Inflicts [%e1.SpellATK_Instant.FixDamage] fire damage on a target within [%First_Target_Valid_Distance]m of you and on up to 6 enemies within a 5m radius of the target.",
        "wi_rockfall": "Inflicts [%e1.SpellATK_Instant.FixDamage] earth damage on a target within a [%First_Target_Valid_Distance]m radius.",
        "wi_sleepingstorm": "Forces a target within a [%First_Target_Valid_Distance]m radius and up to 6 enemies within a 12m radius of the target to fall asleep for [%e1.Sleep.RemainTime] and increases their [%e2.StatUp.StatName].",
        "wi_soulgain": "Increases [%e1.StatUp.StatName] by [%e1.StatUp.Value] for [%e1.StatUp.RemainTime].",
        "wi_stigma_atomicenergy_dark": "Deals [%e1.DelayedSpellATK_Instant.Damage] fire damage on a target within [%First_Target_Valid_Distance]m and up to 6 enemies within a 10m radius of the target after [%e1.DelayedSpellATK_Instant.DelayedTime].",
        "wi_stigma_atomicenergy_light": "Deals [%e1.DelayedSpellATK_Instant.Damage] fire damage on a target within [%First_Target_Valid_Distance]m and up to 6 enemies within a 10m radius of the target after [%e1.DelayedSpellATK_Instant.DelayedTime].",
        "wi_stigma_icelance": "Deals [%e1.SpellATK_Instant.FixDamage] water damage on a target within [%First_Target_Valid_Distance]m of you.",
        "wi_stigma_lavawave_dark": "Deals [%e1.DelayedSpellATK_Instant.Damage] fire damage on a target within [%First_Target_Valid_Distance]m and up to 6 enemies within a 10m radius of the target after [%e1.DelayedSpellATK_Instant.DelayedTime].",
        "wi_stigma_volcanicflame_light": "Deals [%e1.DelayedSpellATK_Instant.Damage] fire damage on a target within [%First_Target_Valid_Distance]m and up to 6 enemies within a 10m radius of the target after [%e1.DelayedSpellATK_Instant.DelayedTime].",
        "wi_stormshock": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within a [%First_Target_Valid_Distance]m radius, and stuns the target for a short time.",
        "wi_summontornado_dark": "Summons a tempest that remains on a spot within [%First_Target_Valid_Distance] m of you for [%e1.SummonSkillArea.SummonTime]. It inflicts continuous wind damage on up to 6 enemies within a 10 m radius and temporarily stuns them.",
        "wi_summontornado_light": "Summons a tempest that remains on a spot within [%First_Target_Valid_Distance] m of you for [%e1.SummonSkillArea.SummonTime]. It inflicts continuous wind damage on up to 6 enemies within a 10 m radius and temporarily stuns them.",
        "wi_wakeup": "Awakens any sleeping allies within a [%First_Target_Valid_Distance]m radius of you.",
        "wi_windcutter": "Inflicts [%e1.SpellATK_Instant.FixDamage] wind damage on a target within a [%First_Target_Valid_Distance]m radius of and causes it to bleed for [%e2.Bleed.RemainTime].",
        "wi_zeropoint": "Deals [%e1.SpellATK_Instant.FixDamage] water damage on a target within [%First_Target_Valid_Distance]m of you."
    }
});
